import {defineConfig,devices} from '@playwright/test';
import {mkdtempSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
const port=Number(process.env.SHIGUANG_E2E_PORT||4432);
if(!Number.isInteger(port)||port<1024||port>65535)throw new Error('SHIGUANG_E2E_PORT must be 1024–65535');
const baseURL=`http://127.0.0.1:${port}`;
const dataDir=mkdtempSync(join(tmpdir(),'shiguang-e2e-'));
const serverEntry=process.env.SHIGUANG_E2E_LIBRARY_FLOW==='1'?'tests/fixtures/library-flow-web-server.mjs':process.env.SHIGUANG_E2E_EVENT_LIVE==='1'?'tests/fixtures/event-live-web-server.mjs':(process.env.SHIGUANG_E2E_AUDIO_LIVE==='1'||process.env.SHIGUANG_E2E_ACCOUNTING_LIVE==='1')?'tests/fixtures/audio-live-web-server.mjs':process.env.SHIGUANG_E2E_ARTIFACT_LIVE==='1'?'tests/fixtures/artifact-live-web-server.mjs':process.env.SHIGUANG_E2E_PET_SOURCES==='1'?'tests/fixtures/pet-sources-web-server.mjs':process.env.SHIGUANG_E2E_CHAT_LIVE==='1'?'tests/fixtures/chat-live-web-server.mjs':process.env.SHIGUANG_E2E_SUP_AUDIO==='1'?'tests/fixtures/supervision-audio-web-server.mjs':process.env.SHIGUANG_E2E_RESEARCH==='1'?'tests/fixtures/research-web-server.mjs':'server/index.mjs';
export default defineConfig({testDir:'./tests/e2e',fullyParallel:false,workers:1,timeout:45000,expect:{timeout:10000},reporter:[['list'],['html',{open:'never'}]],use:{baseURL,trace:'retain-on-failure',screenshot:'only-on-failure'},webServer:{command:`PORT=${port} DATA_DIR=${dataDir} node ${serverEntry}`,url:baseURL+'/api/health',reuseExistingServer:false,timeout:60000},projects:[{name:'desktop',use:{...devices['Desktop Chrome'],viewport:{width:1440,height:1000}}},{name:'android',use:{...devices['Pixel 7']}}]});
