import {test,expect} from '@playwright/test';

test('a chat turn can cite an existing note and event on desktop and mobile',async({page})=>{
 const suffix=Date.now()+Math.random().toString(36).slice(2,6);
 const noteTitle='海边记录 '+suffix,eventTitle='海边要事 '+suffix;
 await page.goto('/');await page.getByRole('button',{name:'进入演示空间'}).click();await expect(page.locator('.app-shell')).toBeVisible();
 expect((await page.request.post('/api/notes',{data:{title:noteTitle,content:'去海边前查询潮汐时间，带好雨具。',project:'生活',tags:[]}})).ok()).toBe(true);
 expect((await page.request.post('/api/events',{data:{title:eventTitle,summary:'出发前确认交通和潮汐。',project:'生活',tags:[],priority:'normal',dueAt:''}})).ok()).toBe(true);
 await page.goto('/#assistant');
 await page.getByRole('button',{name:'引用记录或要事'}).click();
 const picker=page.getByRole('dialog',{name:'引用记录或要事'});
 await picker.getByLabel('搜索可引用资料').fill(noteTitle);
 await picker.getByRole('button',{name:new RegExp(noteTitle)}).click();
 await picker.getByRole('button',{name:/要事 ·/}).click();
 await picker.getByLabel('搜索可引用资料').fill(eventTitle);
 await picker.getByRole('button',{name:new RegExp(eventTitle)}).click();
 await picker.getByRole('button',{name:'完成引用'}).click();
 await expect(page.locator('.composer-references')).toContainText(noteTitle);
 await expect(page.locator('.composer-references')).toContainText(eventTitle);
 await page.getByLabel('向助手提问').fill('这件事出发前要做什么？');
 await page.getByRole('button',{name:/整理搜索简报/}).click();
 const brief=page.getByRole('dialog',{name:'DeepSeek 联网搜索简报'});
 await expect(brief.getByLabel('搜索简报内容')).toHaveValue(/请严格按此格式回答/);
 await expect(brief.getByLabel('搜索简报内容')).toHaveValue(new RegExp(noteTitle));
 await brief.getByLabel('关闭窗口').click();
 await page.getByLabel('发送问题').click();
 const answer=page.locator('.answer-card').last();
 await expect(answer).toContainText(noteTitle);
 await expect(answer).toContainText(eventTitle);
 await expect(answer.locator('.source-item')).toHaveCount(2);
 await page.reload();
 await page.locator('.history-item').filter({hasText:'这件事出发前要做什么？'}).getByRole('button').first().click();
 await expect(page.locator('.composer-references')).toContainText(noteTitle);
 await expect(page.locator('.composer-references')).toContainText(eventTitle);
 await page.getByLabel('向助手提问').fill('还有什么要确认？');
 await page.getByLabel('发送问题').click();
 await expect(page.locator('.answer-card').last().locator('.source-item')).toContainText([noteTitle,eventTitle]);
 await answer.locator('.source-item').filter({hasText:eventTitle}).click();
 await expect(page.locator('.event-card').filter({hasText:eventTitle})).toBeInViewport();
});
