import {test,expect} from '@playwright/test';
test('unavailable event selections can be removed and task selections survive paging, search and failed save',async({page})=>{
 let event:any={id:'relations-event',revision:1,title:'关联选择',summary:'原摘要',eventType:'long_term',priority:'normal',status:'open',lifecycleStatus:'ongoing',dueAt:'',tags:[],project:'',relatedEventIds:['deleted-event'],relatedTaskIds:[],createdAt:'2026-09-29T00:00:00Z'},fail=true;
 await page.route('**/api/bootstrap',async route=>{const response=await route.fetch(),data=await response.json();await route.fulfill({json:{...data,events:[event]}});});
 await page.route('**/api/event-references?**',route=>{const url=new URL(route.request().url()),kind=url.searchParams.get('kind'),offset=Number(url.searchParams.get('offset'));return route.fulfill({json:kind==='workTask'&&!url.searchParams.get('q')?{items:Array.from({length:offset?1:20},(_,i)=>({id:'task-'+(i+offset),title:'任务'+(i+offset)})),total:21}:{items:[],total:0}});});
 await page.route('**/api/event-references/resolve',route=>{const {kind,ids}=route.request().postDataJSON();return route.fulfill({json:{items:ids.map((id:string)=>({id,title:kind==='workTask'?'任务'+id.split('-')[1]:id,invalid:kind==='event'?'来源已删除或失效':''}))}});});
 await page.route('**/api/events/relations-event',route=>{const body=route.request().postDataJSON();expect(body.relatedEventIds).toEqual([]);expect(body.relatedTaskIds).toEqual(['task-20']);if(fail){fail=false;return route.fulfill({status:500,json:{error:'保存测试失败，请重试'}});}event={...event,...body,revision:2};return route.fulfill({json:event});});
 await page.goto('/#events');await page.getByRole('button',{name:'进入演示空间'}).click();await page.locator('#event-relations-event').getByRole('button',{name:'编辑',exact:true}).click();let dialog=page.getByRole('dialog',{name:'编辑要事'});
 await expect(dialog).toContainText('来源已删除或失效');await dialog.getByRole('button',{name:'移除deleted-event',exact:true}).click();
 await dialog.getByRole('button',{name:'下一页关联任务'}).click();await dialog.getByRole('checkbox',{name:'任务20',exact:true}).check();await dialog.getByRole('button',{name:'上一页关联任务'}).click();await dialog.getByLabel('搜索关联任务').fill('不匹配');await expect(dialog.getByLabel('已选关联任务')).toContainText('任务20');
 await dialog.getByRole('button',{name:'确认并保存要事'}).click();await expect(dialog).toContainText('保存测试失败');await expect(dialog.getByLabel('已选关联任务')).toContainText('任务20');await expect(dialog.getByLabel('摘要')).toHaveValue('原摘要');
 await dialog.getByRole('button',{name:'确认并保存要事'}).click();await expect(dialog).toHaveCount(0);await page.reload();await page.locator('#event-relations-event').getByRole('button',{name:'编辑',exact:true}).click();dialog=page.getByRole('dialog',{name:'编辑要事'});await expect(dialog.getByLabel('已选关联任务')).toContainText('任务20');
});
