import {test,expect} from '@playwright/test';
async function login(page){await page.goto('/');await page.getByRole('button',{name:'进入演示空间'}).click();await expect(page.locator('.app-shell')).toBeVisible();await page.goto('/#assistant');}
test('lost send response retries one operation and preserves the input',async({page})=>{
 await login(page);let lose=true;const operations:string[]=[];await page.route('**/api/v1/ask',async route=>{operations.push(route.request().postDataJSON().opId);if(lose){lose=false;await route.fetch();await route.abort('failed');}else await route.continue();});
 await page.getByLabel('向助手提问').fill('丢响应后的同一个问题');await page.getByRole('button',{name:'发送问题',exact:true}).click();await expect(page.getByRole('alert')).toContainText('连接暂时中断');await expect(page.getByLabel('向助手提问')).toHaveValue('丢响应后的同一个问题');await page.reload();await expect(page.getByLabel('向助手提问')).toHaveValue('丢响应后的同一个问题');await page.getByRole('button',{name:'发送问题',exact:true}).click();await expect(page.locator('.answer-card')).toHaveCount(1);expect(operations).toHaveLength(2);expect(operations[0]).toBeTruthy();expect(operations[0]).toBe(operations[1]);const boot=await (await page.request.get('/api/v1/bootstrap')).json();expect(boot.conversations.filter((c:{query:string})=>c.query==='丢响应后的同一个问题')).toHaveLength(1);
});
test('late response stays in original topic and cannot clear new typing after a switch',async({page})=>{
 await login(page);const a=await (await page.request.post('/api/v1/ask',{data:{query:'请求目标甲'}})).json(),b=await (await page.request.post('/api/v1/ask',{data:{query:'请求目标乙'}})).json();await page.reload();await page.locator('.history-item button').filter({hasText:'请求目标甲'}).click();await expect(page.locator('.answer-card')).toHaveCount(1);
 let release,arrived;const gate=new Promise<void>(r=>release=r),seen=new Promise<void>(r=>arrived=r);await page.route('**/api/v1/ask',async route=>{const response=await route.fetch();arrived();await gate;await route.fulfill({response});});
 await page.getByLabel('向助手提问').fill('只发给甲的问题');await page.getByRole('button',{name:'发送问题',exact:true}).click();await seen;await page.locator('.history-item button').filter({hasText:'请求目标乙'}).click();await page.getByLabel('向助手提问').fill('乙话题的新草稿');release();await expect(page.getByRole('button',{name:'发送问题',exact:true})).toBeEnabled();await expect(page.getByLabel('向助手提问')).toHaveValue('乙话题的新草稿');await expect(page.locator('.history-item.selected')).toContainText('请求目标乙');await expect(page.locator('.answer-card')).not.toContainText('只发给甲的问题');
 const boot=await (await page.request.get('/api/v1/bootstrap')).json();const sent=boot.conversations.find((c:{query:string})=>c.query==='只发给甲的问题');expect(sent.threadId).toBe(a.threadId);expect(sent.threadId).not.toBe(b.threadId);
});
