import {test,expect} from '@playwright/test';
test('record discussion retries history loading and returns to the same conversation after source edits',async({page})=>{
 await page.goto('/');await page.getByRole('button',{name:'进入演示空间'}).click();await expect(page.locator('.app-shell')).toBeVisible();
 const note=await (await page.request.post('/api/v1/notes',{data:{title:'固定讨论验收',content:'计划后天整理读书笔记，还没有完成。'}})).json();
 await page.reload();await page.locator('.note-card').filter({hasText:'固定讨论验收'}).locator('.note-card-body').click();
 let fail=true;await page.route('**/api/v1/threads/*/turns*',async route=>{if(fail){fail=false;await route.fulfill({status:503,json:{error:'历史暂不可用'}});}else await route.continue();});
 await page.getByRole('button',{name:'与搭子讨论',exact:true}).click();await expect(page.getByLabel('本轮引用的资料')).toContainText('固定讨论验收');await expect(page.getByRole('alert')).toContainText('历史暂不可用');await page.getByLabel('向助手提问').fill('我计划什么时候整理？');await expect(page.getByRole('button',{name:'发送问题',exact:true})).toBeDisabled();await page.getByRole('button',{name:'重试加载话题'}).click();await expect(page.getByRole('button',{name:'发送问题',exact:true})).toBeEnabled();await page.getByRole('button',{name:'发送问题',exact:true}).click();await expect(page.locator('.answer-card')).toHaveCount(1);
 const first=await (await page.request.get('/api/v1/bootstrap')).json();const turn=first.conversations.find((c:{query:string})=>c.query==='我计划什么时候整理？');const current=first.notes.find((n:{id:string})=>n.id===note.id);await page.request.patch('/api/v1/notes/'+note.id,{data:{revision:current.revision,title:'改名后的固定讨论',content:'计划改为下周整理，仍然未完成。'}});
 await page.goto('/#library');await page.locator('.note-card').filter({hasText:'改名后的固定讨论'}).locator('.note-card-body').click();await page.getByRole('button',{name:'与搭子讨论',exact:true}).click();await expect(page.locator('.answer-card')).toHaveCount(1);await expect(page.getByLabel('本轮引用的资料')).toContainText('改名后的固定讨论');await expect(page.locator('.answer-reference-list')).toContainText('固定讨论验收');await page.getByLabel('向助手提问').fill('现在计划变成什么时候？');await page.getByRole('button',{name:'发送问题',exact:true}).click();await expect(page.locator('.answer-card')).toHaveCount(2);
 const final=await (await page.request.get('/api/v1/bootstrap')).json();const turns=final.conversations.filter((c:{threadId:string})=>c.threadId===turn.threadId);expect(turns).toHaveLength(2);expect(turns.some((c:{references:{title:string}[]})=>c.references[0]?.title==='改名后的固定讨论')).toBe(true);
});
