import {test,expect} from '@playwright/test';
test('failed reminder is visible and unknown-response retry keeps the original operation',async({page})=>{
 const day=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date()),jobId='a'.repeat(64);
 const task={id:'retry-task',title:'提醒恢复测试',status:'supervising',supervisionStatus:'active',repeat:'once',minutes:0,time:'20:00',requirement:'心得',plan:{goal:'阅读',conditions:'资料',steps:[],deliverable:'心得'},logs:[],outputs:[]};
 let state='failed',opId='',requests=0;const run=()=>({id:'retry-run',taskId:task.id,day,status:'open',seconds:0,timerAt:null,evidence:'',artifactId:'',reminderJob:{id:jobId,state,dueAt:new Date().toISOString(),attempts:1,error:'提醒处理失败，尚未确认送达。',overdue:false}});
 await page.route('**/api/v1/work-runs/retry-run/evidence-**',route=>route.fulfill({json:{items:[],total:0}}));
 await page.route('**/api/v1/work-tasks',route=>route.fulfill({json:{tasks:[task],runs:[run()]}}));
 await page.route('**/api/v1/pet/reminders',route=>route.fulfill({json:{snapshot:state,cursor:1,total:state==='failed'?1:0,items:state==='failed'?[{id:'retry-prompt',sourceKind:'workRun',sourceId:'retry-run',title:task.title,message:'这次提醒处理失败了，可以重试哦。',count:1,actionTarget:{page:'workTasks',id:task.id,runId:'retry-run'}}]:[]}}));
 await page.route('**/api/v1/work-runs/retry-run/action',async route=>{const body=route.request().postDataJSON();expect(body.action).toBe('retry-reminder');expect(body.jobId).toBe(jobId);expect(body.scheduleVersion).toBeUndefined();if(!opId)opId=body.opId;expect(body.opId).toBe(opId);requests++;state='pending';if(requests===1)await route.abort('failed');else await route.fulfill({json:{id:jobId,state}});});
 await page.goto('/#workTasks');await page.getByRole('button',{name:'进入演示空间'}).click();await expect(page.locator('.app-shell')).toBeVisible();await expect(page.locator('#main-content').getByText('小九：这次提醒处理失败了，可以重试哦。',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:/小九现在/}).hover();await page.getByLabel('小九提示表').getByRole('button',{name:'查看：提醒恢复测试',exact:true}).click();const dialog=page.getByRole('dialog',{name:'本次执行证据'});await dialog.getByRole('button',{name:'重试提醒',exact:true}).click();await expect(dialog.getByRole('alert')).toContainText('连接暂时中断');await page.reload();await page.getByRole('button',{name:'重试任务操作',exact:true}).click();await expect(page.getByRole('button',{name:'重试任务操作',exact:true})).toHaveCount(0);await expect(page.getByText('提醒进度：等待后台处理 · 已尝试 1 次')).toBeVisible();expect(requests).toBe(2);
});
