import {test,expect} from '@playwright/test';import {createServer} from 'node:http';
test('user edits individual conditions before start; lost response retries once and future edits preserve current run',async({page})=>{
 let recapCalls=0;
 const model=createServer(async(req,res)=>{let raw='';for await(const chunk of req)raw+=chunk;const data=JSON.parse(raw),system=data.messages[0].content,result=system.includes('规划助手')?{goal:'阅读',conditions:'资料',steps:['读书'],deliverable:'三条心得'}:system.includes('每日复盘助手')?++recapCalls===1?{items:[]}:{items:JSON.parse(data.messages[1].content).items.map((item:any)=>({runId:item.id,advice:'建议先补交学习心得，再决定下一步。'}))}:{tool:'wait_external',reason:'等待用户学习'};res.setHeader('Content-Type','application/json');res.end(JSON.stringify({choices:[{message:{content:JSON.stringify(result)},finish_reason:'stop'}]}));});
 await new Promise<void>(resolve=>model.listen(0,'127.0.0.1',resolve));const address=model.address() as {port:number};
 try{
  await page.goto('/#workTasks');await page.getByRole('button',{name:'进入演示空间'}).click();await expect(page.locator('.app-shell')).toBeVisible();
  await page.request.patch('/api/settings',{data:{provider:{baseUrl:`http://127.0.0.1:${address.port}`,model:'test-conditions',apiKey:'test-key'}}});
  const task=await (await page.request.post('/api/work-tasks',{data:{goal:'每日多条件阅读',minutes:30,repeat:'daily',requirement:'三条心得'}})).json();await page.reload();await page.getByRole('button',{name:'每日多条件阅读',exact:true}).click();let dialog=page.getByRole('dialog',{name:'每日多条件阅读'});
  await dialog.getByRole('button',{name:'编辑完成条件',exact:true}).click();await dialog.getByRole('button',{name:'添加完成条件'}).click();await dialog.getByRole('textbox',{name:'完成条件 2',exact:true}).fill('一个实践例子');await dialog.getByRole('spinbutton',{name:'最少投入分钟'}).fill('45');await expect(dialog.getByRole('button',{name:'确认计划并开始'})).toBeDisabled();
  let dropped=false;await page.route('**/api/work-tasks/*/conditions',async route=>{if(!dropped){dropped=true;const response=await route.fetch();expect(response.ok()).toBe(true);await route.abort('failed');}else await route.continue();});
  await dialog.getByRole('button',{name:'确认保存完成条件'}).click();await expect(dialog.getByRole('alert')).toContainText('连接暂时中断');await page.reload();await page.getByRole('button',{name:'每日多条件阅读',exact:true}).click();dialog=page.getByRole('dialog',{name:'每日多条件阅读'});await dialog.getByRole('button',{name:'重试保存完成条件'}).click();await expect(dialog.getByRole('button',{name:'编辑完成条件',exact:true})).toBeVisible();expect((await page.request.post('/api/work-tasks/'+task.id+'/action',{data:{action:'start',planVersion:1}})).status()).toBe(409);await dialog.getByRole('button',{name:'确认计划并开始'}).click();
  await expect.poll(async()=>{const data=await (await page.request.get('/api/work-tasks')).json();return data.runs.find((r:any)=>r.taskId===task.id)?.conditionsSnapshot.conditions.length;}).toBe(2);
  await dialog.getByRole('button',{name:'编辑完成条件',exact:true}).click();await dialog.getByRole('textbox',{name:'完成条件 1',exact:true}).fill('明天的新要求');await dialog.getByRole('button',{name:'确认保存完成条件'}).click();
  const state=await (await page.request.get('/api/work-tasks')).json(),saved=state.tasks.find((t:any)=>t.id===task.id),run=state.runs.find((r:any)=>r.taskId===task.id);expect(saved.planVersion).toBe(3);expect(saved.conditionChanges).toHaveLength(2);expect(saved.completionConditions[0].description).toBe('明天的新要求');expect(run.conditionsSnapshot.conditions.map((c:any)=>c.description)).toEqual(['三条心得','一个实践例子']);expect(run.conditionsSnapshot.minimumSeconds).toBe(2700);
  await page.reload();const card=page.locator('.phase-card').filter({hasText:'本次完成要求：三条心得；一个实践例子'});await card.getByRole('button',{name:'提交证据 / 调整',exact:true}).click();const evidenceDialog=page.getByRole('dialog',{name:'本次执行证据'});
  let scheduleDropped=false;await page.route('**/api/work-runs/*/action',async route=>{if(route.request().postDataJSON().action==='snooze'&&!scheduleDropped){scheduleDropped=true;const response=await route.fetch();expect(response.ok()).toBe(true);await route.abort('failed');}else await route.continue();});
  await evidenceDialog.getByLabel('稍后检查时间',{exact:true}).fill('2099-01-02T12:00');await evidenceDialog.getByRole('button',{name:'安排稍后检查',exact:true}).click();await expect(evidenceDialog.getByRole('alert')).toContainText('连接暂时中断');await page.reload();await page.getByRole('button',{name:'重试任务操作',exact:true}).click();await expect(page.getByRole('button',{name:'重试任务操作',exact:true})).toHaveCount(0);
  const movedState=await (await page.request.get('/api/work-tasks')).json(),moved=movedState.runs.find((r:any)=>r.id===run.id);expect(moved.scheduleVersion).toBe(2);expect(moved.scheduleHistory).toHaveLength(1);expect(moved.logicalDay).toBe(run.logicalDay);expect(moved.evidenceRevision).toBe(run.evidenceRevision);expect(moved.scheduledDueAt).toBe(moved.snoozedUntil);await card.getByText('约定调整历史',{exact:true}).click();await expect(card).toContainText('2099');
  await page.getByText('每日复盘',{exact:true}).click();const recap=page.locator('details').filter({has:page.locator('summary').getByText('每日复盘',{exact:true})});await expect(recap).toContainText('计划 1 项 · 已确认完成 0 项 · 待处理 1 项');await recap.getByRole('button',{name:'生成 AI 复盘建议'}).click();await expect(recap.getByRole('alert')).toContainText('AI 复盘建议格式无效');await recap.getByRole('button',{name:'生成 AI 复盘建议'}).click();await expect(recap).toContainText('建议先补交学习心得');expect(recapCalls).toBe(2);
  expect((await page.request.post('/api/work-runs/'+run.id+'/action',{data:{action:'skip',opId:'recap-browser-skip',scheduleVersion:2,reason:'临时有事'}})).ok()).toBe(true);await recap.getByRole('button',{name:'刷新复盘事实'}).click();await expect(recap).toContainText('已有 AI 建议依据的记录已变化');await expect(recap).toContainText('已记录原因：临时有事');await expect(recap).toContainText('跳过 1 项');


 }finally{await page.request.patch('/api/settings',{data:{provider:{baseUrl:'',model:'',clearKey:true}}}).catch(()=>{});model.closeAllConnections();await new Promise<void>(resolve=>model.close(()=>resolve()));}
});
