import {test,expect} from '@playwright/test';
test('pet overdue summary opens only that task history, with access back to all records',async({page})=>{
 const base={revision:1,goal:'阅读',status:'running',supervisionStatus:'active',repeat:'daily',minutes:30,time:'20:00',requirement:'心得',plan:{goal:'阅读',conditions:'资料',steps:[],deliverable:'心得'},logs:[],outputs:[]};
 const tasks=[{...base,id:'history-task',title:'历史阅读任务'},{...base,id:'other-task',title:'另一个任务'}];
 const runs=[{id:'old-one',taskId:'history-task',day:'2026-01-01',status:'open',seconds:0,evidence:'',artifactId:'',timerAt:null,snapshotNotice:'服务恢复后补建'},{id:'old-two',taskId:'history-task',day:'2026-01-02',status:'open',seconds:0,evidence:'',artifactId:'',timerAt:null},{id:'other-run',taskId:'other-task',day:'2026-01-01',status:'open',seconds:0,evidence:'',artifactId:'',timerAt:null}];
 await page.route('**/api/v1/work-tasks',route=>route.fulfill({json:{tasks,runs}}));
 await page.route('**/api/v1/pet/reminders',route=>route.fulfill({json:{snapshot:'history',cursor:1,total:1,items:[{id:'workTask:history-task:overdue',sourceKind:'workTask',sourceId:'history-task',sourceRevision:1,occurrenceKey:'overdue',title:'历史阅读任务',message:'之前有 2 次任务记录还待处理',count:2,actionTarget:{page:'workTasks',id:'history-task',history:true}}]}}));
 await page.goto('/');await page.getByRole('button',{name:'进入演示空间'}).click();await expect(page.locator('.app-shell')).toBeVisible();await page.getByRole('button',{name:/小九现在/}).hover();await page.getByLabel('小九提示表').getByRole('button',{name:'查看：历史阅读任务',exact:true}).click();
 await expect(page.getByRole('heading',{name:'执行历史',exact:true})).toBeVisible();await expect(page.getByText('正在查看：历史阅读任务')).toBeVisible();await expect(page.getByText('服务恢复后补建',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'提交证据 / 调整',exact:true})).toHaveCount(2);await expect(page.getByRole('dialog')).toHaveCount(0);await page.getByRole('button',{name:'查看全部任务记录'}).click();await expect(page.getByRole('button',{name:'提交证据 / 调整',exact:true})).toHaveCount(3);
});
