import {test,expect} from '@playwright/test';import {createServer} from 'node:http';
test('evidence review shows cited conditions, cannot bypass duration and completes only after user confirmation',async({page})=>{
 let reviews=0;
 const model=createServer(async(req,res)=>{let raw='';for await(const chunk of req)raw+=chunk;const data=JSON.parse(raw),system=data.messages[0].content,input=system.includes('验收任务证据')?JSON.parse(data.messages[1].content):null;const result=system.includes('规划助手')?{goal:'阅读',conditions:'资料',steps:['读书'],deliverable:'三条心得'}:system.includes('验收任务证据')?++reviews===1?{results:[]}:{results:input.conditions.map((condition:any)=>({conditionId:condition.id,status:'satisfied',reason:'已找到三条心得与实践例子',evidence:[{sourceId:'text',quote:input.sources.find((s:any)=>s.id==='text').content}]}))}:{tool:'wait_external',reason:'等待用户学习'};res.setHeader('Content-Type','application/json');res.end(JSON.stringify({choices:[{message:{content:JSON.stringify(result)},finish_reason:'stop'}]}));});
 await new Promise<void>(resolve=>model.listen(0,'127.0.0.1',resolve));const address=model.address() as {port:number};
 try{
  await page.goto('/#workTasks');await page.getByRole('button',{name:'进入演示空间'}).click();await expect(page.locator('.app-shell')).toBeVisible();
  await page.request.patch('/api/v1/settings',{data:{provider:{baseUrl:`http://127.0.0.1:${address.port}`,model:'test-evidence',apiKey:'test-key'}}});
  const note=await (await page.request.post('/api/v1/notes',{data:{title:'验收引用笔记',content:'原始学习笔记'}})).json();
  const created=await page.request.post('/api/v1/work-tasks',{data:{goal:'双条件验收测试',minutes:45,repeat:'once',requirement:'三条心得与实践例子'}});expect(created.ok()).toBe(true);const task=await created.json();await page.request.post('/api/v1/work-tasks/'+task.id+'/action',{data:{action:'start'}});await page.reload();
  const card=page.locator('.phase-card').filter({hasText:'本次完成要求：三条心得与实践例子'});await expect(card.getByRole('button',{name:'确认完成',exact:true})).toBeDisabled();
  await card.getByRole('button',{name:'提交证据 / 调整',exact:true}).click();let dialog=page.getByRole('dialog',{name:'本次执行证据'});await dialog.getByRole('checkbox',{name:/验收引用笔记/}).check();await page.request.patch('/api/v1/notes/'+note.id,{data:{revision:note.revision,content:'改版后的学习笔记'}});await dialog.getByRole('button',{name:'刷新证据列表'}).click();await expect(dialog.getByRole('alert')).toContainText('版本已变化');await expect(dialog.getByLabel('已选证据')).toContainText('版本 '+note.revision);await dialog.getByRole('button',{name:'移除 验收引用笔记'}).click();await dialog.getByRole('checkbox',{name:/验收引用笔记/}).check();await expect(dialog.getByLabel('已选证据')).toContainText('版本 '+(note.revision+1));await dialog.getByRole('textbox',{name:'说明与总结',exact:true}).fill('三条心得：甲、乙、丙。实践例子：完成演示。');await dialog.getByRole('button',{name:'检查证据',exact:true}).click();await expect(dialog.getByRole('alert')).toContainText('AI 验收结果格式无效');await expect(dialog.getByRole('textbox',{name:'说明与总结',exact:true})).toHaveValue('三条心得：甲、乙、丙。实践例子：完成演示。');await dialog.getByRole('textbox',{name:'说明与总结',exact:true}).fill('修订：三条心得：甲、乙、丙。实践例子：完成演示。');await dialog.getByRole('button',{name:'检查证据',exact:true}).click();await expect(dialog).toHaveCount(0);
  await card.getByText('三条心得与实践例子 · 满足',{exact:true}).click();await expect(card).toContainText('证据 本次文字说明 · 第 1');await card.getByRole('button',{name:'确认完成',exact:true}).click();await expect(page.getByRole('alert')).toContainText('投入时长未达到');
  await card.getByRole('button',{name:'提交证据 / 调整',exact:true}).click();dialog=page.getByRole('dialog',{name:'本次执行证据'});await dialog.getByLabel('补记开始时间',{exact:true}).fill('2020-01-01T09:00');await dialog.getByLabel('补记结束时间',{exact:true}).fill('2020-01-01T09:45');await dialog.getByPlaceholder('补记原因',{exact:true}).fill('离线读书投入');await dialog.getByRole('button',{name:'补记',exact:true}).click();await expect(dialog).toHaveCount(0);
  await card.getByRole('button',{name:'确认完成',exact:true}).click();await expect(card).toContainText('已确认完成');await expect(card.getByRole('button',{name:'确认完成',exact:true})).toBeDisabled();await expect(page.getByRole('button',{name:/小九现在/})).toHaveAttribute('aria-label',/开心地贴贴/);await expect(page.locator('.pet-buddy-speech')).toContainText('已经由你确认完成');
  const state=await (await page.request.get('/api/v1/work-tasks')).json(),run=state.runs.find((r:any)=>r.taskId===task.id);expect(run.status).toBe('completed');expect(run.assessment.version).toBe(2);expect(run.seconds).toBe(2700);expect(run.evidenceRevision).toBe(2);expect(run.evidenceRefs).toEqual([{kind:'note',id:note.id,revision:note.revision+1}]);
  await page.request.patch('/api/v1/notes/'+note.id,{data:{revision:note.revision+1,content:'检查完成后再次修改的笔记'}});
  await page.reload();await card.getByText('证据检查历史',{exact:true}).click();const history=card.getByLabel('证据检查历史',{exact:true});
  await history.getByRole('button',{name:/检查失败/}).click();let details=history.getByLabel('检查历史详情',{exact:true});await expect(details).toContainText('AI 验收结果格式无效');await details.getByText('当时提交的文字',{exact:true}).click();await expect(details).toContainText('三条心得：甲、乙、丙。实践例子：完成演示。');await expect(details).not.toContainText('修订：');
  await history.getByRole('button',{name:/检查结果已保存/}).click();details=history.getByLabel('检查历史详情',{exact:true});await expect(details).toContainText('来源已修改');await details.getByText('当时提交的文字',{exact:true}).click();await expect(details).toContainText('修订：三条心得');await details.getByText(/验收引用笔记 · 版本/).click();await expect(details.getByText('改版后的学习笔记',{exact:true})).toBeVisible();await expect(details).not.toContainText('检查完成后再次修改的笔记');await expect(card).toContainText('已确认完成');expect(reviews).toBe(2);

 }finally{await page.request.patch('/api/v1/settings',{data:{provider:{baseUrl:'',model:'',clearKey:true}}}).catch(()=>{});model.closeAllConnections();await new Promise<void>(resolve=>model.close(()=>resolve()));}
});
