import {test,expect} from '@playwright/test';import {createServer} from 'node:http';
test('todo upgrade requires conditions, recovers a lost response and completes only through supervision',async({page})=>{
 let calls=0;const model=createServer(async(req,res)=>{let raw='';for await(const chunk of req)raw+=chunk;calls++;const data=JSON.parse(raw),input=JSON.parse(data.messages[1].content);res.setHeader('Content-Type','application/json');res.end(JSON.stringify({choices:[{message:{content:JSON.stringify({results:input.conditions.map((condition:any)=>({conditionId:condition.id,status:'satisfied',reason:'已提供心得',evidence:[{sourceId:'text',quote:input.sources.find((s:any)=>s.id==='text').content}]}))})},finish_reason:'stop'}]}));});await new Promise<void>(resolve=>model.listen(0,'127.0.0.1',resolve));const port=(model.address() as {port:number}).port;
 try{
  await page.goto('/');await page.getByRole('button',{name:'进入演示空间'}).click();await expect(page.locator('.app-shell')).toBeVisible();
  const todo=await (await page.request.post('/api/todos',{data:{title:'监督升级验收'}})).json();await page.reload();await page.locator('#todo-'+todo.id).getByRole('button',{name:'升级监督'}).click();let dialog=page.getByRole('dialog',{name:'升级为监督任务'});await dialog.getByRole('textbox',{name:'完成要求 1',exact:true}).fill('写一条学习心得');await dialog.getByRole('spinbutton',{name:'最低投入分钟'}).fill('0');
  let dropped=false;await page.route('**/api/todos/*/upgrade',async route=>{if(!dropped){dropped=true;const response=await route.fetch();expect(response.ok()).toBe(true);await route.abort('failed');}else await route.continue();});await dialog.getByRole('button',{name:'确认条件并开始监督'}).click();await expect(dialog.getByRole('alert')).toContainText('连接暂时中断');await page.reload();dialog=page.getByRole('dialog',{name:'升级为监督任务'});await dialog.getByRole('button',{name:'重试升级'}).click();await expect(page.getByRole('dialog',{name:'本次执行证据'})).toBeVisible();
  let state=await (await page.request.get('/api/work-tasks')).json();const tasks=state.tasks.filter((t:any)=>t.sourceTodoId===todo.id);expect(tasks).toHaveLength(1);expect(tasks[0].executionMode).toBe('supervision');expect(tasks[0].calls).toBe(0);expect(state.runs.filter((r:any)=>r.taskId===tasks[0].id)).toHaveLength(1);expect(calls).toBe(0);expect((await page.request.post('/api/work-tasks/'+tasks[0].id+'/action',{data:{action:'pause'}})).ok()).toBe(true);expect((await page.request.post('/api/work-tasks/'+tasks[0].id+'/action',{data:{action:'start',planVersion:1}})).ok()).toBe(true);state=await (await page.request.get('/api/work-tasks')).json();expect(state.tasks.find((t:any)=>t.id===tasks[0].id).status).toBe('supervising');expect(calls).toBe(0);
  let linked=(await (await page.request.get('/api/bootstrap')).json()).todos.find((t:any)=>t.id===todo.id);expect((await page.request.patch('/api/todos/'+todo.id,{data:{revision:linked.revision,done:true}})).status()).toBe(409);expect((await page.request.delete('/api/todos/'+todo.id,{data:{revision:linked.revision}})).status()).toBe(409);expect((await (await page.request.get('/api/pet/reminders')).json()).items.some((item:any)=>item.sourceKind==='todo'&&item.sourceId===todo.id)).toBe(false);
  await page.request.patch('/api/settings',{data:{provider:{baseUrl:`http://127.0.0.1:${port}`,model:'test-upgrade',apiKey:'test-key'}}});const evidence=page.getByRole('dialog',{name:'本次执行证据'});await evidence.getByRole('textbox',{name:'说明与总结',exact:true}).fill('我的心得：先理解再实践。');await evidence.getByRole('button',{name:'检查证据',exact:true}).click();await expect(evidence).toHaveCount(0);linked=(await (await page.request.get('/api/bootstrap')).json()).todos.find((t:any)=>t.id===todo.id);expect(linked.done).toBe(false);
  await page.locator('.phase-card').filter({hasText:'本次完成要求：写一条学习心得'}).getByRole('button',{name:'确认完成',exact:true}).click();await expect.poll(async()=>((await (await page.request.get('/api/bootstrap')).json()).todos.find((t:any)=>t.id===todo.id).done)).toBe(true);expect(calls).toBe(1);await page.getByRole('button',{name:'监督升级验收',exact:true}).click();await page.getByRole('button',{name:/查看来源待办/}).click();await expect(page.locator('#todo-'+todo.id)).toBeFocused();await expect(page.locator('#todo-'+todo.id).getByRole('button',{name:'重新打开：监督升级验收'})).toBeDisabled();
 }finally{await page.request.patch('/api/settings',{data:{provider:{baseUrl:'',model:'',clearKey:true}}}).catch(()=>{});model.closeAllConnections();await new Promise<void>(resolve=>model.close(()=>resolve()));}
});
