import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import os from 'node:os';import path from 'node:path';
import express from 'express';
test('categories and project IDs preserve sources and manual correction is atomic and idempotent',async()=>{
 const directory=await mkdtemp(path.join(os.tmpdir(),'shiguang-categories-'));process.env.DATA_DIR=directory;process.env.SEED_DEMO='false';process.env.WORKER_MODE='true';
 const {db,save,get,all}=await import('../server/store.mjs');const {installCategories,ensureCategories,categories,setCategories}=await import('../server/categories.mjs');
 const app=express();app.use(express.json());installCategories(app);app.use((e,req,res,next)=>res.status(e.status||500).json({error:e.message}));const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const base=`http://127.0.0.1:${server.address().port}/api`;
 const call=async(url,method='GET',body)=>{const r=await fetch(base+url,{method,headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});return {status:r.status,data:await r.json()};};
 try{
  const ids=categories().map(c=>c.id);ensureCategories();assert.deepEqual(categories().map(c=>c.id),ids);assert.deepEqual(categories().map(c=>c.name),['日记','理财','读书笔记','个人工作','生活','感悟','灵感','study plan','Q（问题）']);
  const a=save('note',{title:'旧笔记',content:'完整原文\n第二行',project:'PersonalAgent',attachments:[{id:'photo',key:'original.png'}],threadId:'fixed-thread'}),b=save('note',{title:'另一笔记',content:'其他内容'});
  const p1=(await call('/projects','POST',{name:'PersonalAgent',opId:'project-create-1'})).data,p2=(await call('/projects','POST',{name:'PersonalAgent'})).data;assert.notEqual(p1.id,p2.id);assert.equal((await call('/projects','POST',{name:'PersonalAgent',opId:'project-create-1'})).data.id,p1.id);assert.equal((await call('/projects','POST',{name:'改过的项目',opId:'project-create-1'})).status,409);
  const category=(await call('/categories','POST',{name:'PersonalAgent',projectId:p1.id})).data;assert.equal((await call('/categories','POST',{name:' personalagent ',projectId:p1.id})).status,409);
  const input={opId:'manual-operation-1',categoryId:category.id,notes:[{id:a.id,revision:a.revision}],reason:'项目笔记'};const first=setCategories(input);assert.deepEqual(setCategories(input),first);assert.equal(all('classificationCorrection').length,1);
  assert.throws(()=>setCategories({...input,categoryId:'category-life'}),/不同分类修改/);
  const current=get(a.id,'note');assert.equal(current.content,a.content);assert.deepEqual(current.attachments,a.attachments);assert.equal(current.threadId,a.threadId);assert.equal(current.categoryId,category.id);assert.equal(current.projectId,undefined);
  assert.throws(()=>setCategories({opId:'manual-operation-2',categoryId:'category-life',notes:[{id:b.id,revision:b.revision},{id:a.id,revision:a.revision}]}),/已更新/);assert.equal(get(b.id,'note').revision,b.revision);assert.equal(all('classificationCorrection').length,1);
  assert.equal((await call(`/projects/${p1.id}/items?kind=note`)).data.total,1,'explicit project category includes note');
  assert.equal((await call(`/projects/${p2.id}/items?kind=note`)).data.total,0,'same name does not merge');
  const event=save('event',{title:'项目要事',summary:'保留摘要',threadId:'event-thread'});
  const candidate=await call(`/projects/${p1.id}/candidates?kind=event&q=${encodeURIComponent('项目')}`);assert.equal(candidate.data.total,1);assert.equal(candidate.data.items[0].id,event.id);
  assert.equal((await call(`/projects/${p1.id}/links`,'POST',{kind:'event',id:event.id,revision:event.revision+1})).status,409);
  assert.equal((await call(`/projects/${p1.id}/links`,'POST',{kind:'event',id:event.id,revision:event.revision})).status,200);
  assert.equal(get(event.id,'event').threadId,'event-thread');assert.equal((await call(`/projects/${p1.id}/candidates?kind=event`)).data.total,0);
  assert.equal((await call(`/projects/${p1.id}/items?kind=event&offset=1&limit=1`)).data.items.length,0);
  assert.equal((await call(`/projects/${p1.id}/items?kind=unknown`)).status,400);
  const explicit=save('note',{title:'独立关联优先',categoryId:category.id,projectId:p2.id});
  assert.equal((await call(`/projects/${p2.id}/items?kind=note`)).data.items[0].id,explicit.id);
  assert.equal((await call(`/projects/${p1.id}/links`,'POST',{kind:'note',id:a.id,revision:current.revision})).status,200);
  assert.equal((await call(`/projects/${p1.id}/items?kind=note`)).data.total,1);assert.equal((await call(`/projects/${p2.id}/items?kind=note`)).data.total,1);
  const projectMemory=save('memory',{content:'项目约束：使用独立会话',scopeKind:'project',scopeId:p1.id,status:'candidate',scope:'周报',sourceId:'missing-source'});
  save('memory',{content:'同名另一个项目',scopeKind:'project',scopeId:p2.id,status:'active'});
  save('memory',{content:'全局不因残留项目字段归入',scopeKind:'global',scopeId:'',projectId:p1.id,status:'active'});
  save('memory',{content:'旧文字不推测关联',project:'PersonalAgent',status:'active'});
  const memoryGroup=(await call(`/projects/${p1.id}/items?kind=memory&limit=1`)).data;
  assert.equal(memoryGroup.total,1);assert.equal(memoryGroup.items[0].id,projectMemory.id);assert.equal(memoryGroup.items[0].status,'candidate');assert.ok(memoryGroup.items[0].sourceIssue);
  assert.equal((await call(`/projects/${p1.id}/items?kind=memory&offset=1&limit=1`)).data.items.length,0);
  assert.equal((await call(`/projects/${p2.id}/items?kind=memory`)).data.total,1);
  assert.equal((await call(`/projects/${p2.id}/links`,'POST',{kind:'memory',id:projectMemory.id,revision:projectMemory.revision})).status,400,'generic linking must not bypass memory scope confirmation');
  assert.equal(get(projectMemory.id,'memory').revision,projectMemory.revision);
  const renamed=await call(`/projects/${p1.id}`,'PATCH',{name:'拾光项目',revision:p1.revision});assert.equal(renamed.status,200);assert.equal((await call(`/projects/${p1.id}/items?kind=memory`)).data.items[0].id,projectMemory.id);assert.equal(get(a.id,'note').projectId,p1.id);assert.equal(get(a.id,'note').project,'PersonalAgent');
  assert.equal((await call(`/categories/${category.id}`,'PATCH',{name:'拾光开发',revision:category.revision})).status,200);assert.equal(get(a.id,'note').categoryId,category.id);
  assert.equal((await call('/categories/category-diary','PATCH',{name:'替换固定类别',revision:1})).status,422);
  const correction=all('classificationCorrection')[0];assert.equal((await call(`/classification-corrections/${correction.id}`,'PATCH',{revision:correction.revision,status:'resolved',resolution:'已核对'})).status,200);assert.equal((await call('/classification-corrections?status=open')).data.total,0);assert.equal(all('classificationCorrection').length,1);
  const resolved=all('classificationCorrection')[0];assert.equal(resolved.sourceTitle,'旧笔记');assert.equal(resolved.newCategoryName,'PersonalAgent');assert.equal(resolved.history.length,1);
  assert.equal((await call(`/classification-corrections/${resolved.id}`,'PATCH',{revision:resolved.revision,status:'open',resolution:'需继续排查'})).status,200);
  const reopened=all('classificationCorrection')[0];assert.equal(reopened.history.length,2);assert.equal(reopened.history[0].resolution,'已核对');assert.equal(reopened.history[1].resolution,'需继续排查');
 }finally{await new Promise(r=>server.close(r));db.close();await rm(directory,{recursive:true,force:true});}
});
