import {test} from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,rm} from 'node:fs/promises';import {createServer} from 'node:http';import os from 'node:os';import path from 'node:path';
test('AI classification accepts only existing categories and cannot override manual choices or newer sources',async()=>{
 const dir=await mkdtemp(path.join(os.tmpdir(),'shiguang-classifier-'));process.env.DATA_DIR=dir;process.env.SEED_DEMO='false';process.env.WORKER_MODE='true';
 const {db,save,get,setSetting,all}=await import('../server/store.mjs');const {ensureCategories,setCategories}=await import('../server/domain/notes/categories.mjs');const {fileJobs}=await import('../server/jobs/file-jobs.mjs');const {enqueueClassification,classificationHandlers}=await import('../server/domain/notes/classification.mjs');ensureCategories();
 let output=JSON.stringify({categoryId:'category-idea',reason:'新的产品灵感'});
 const server=createServer(async(req,res)=>{for await(const chunk of req){}res.setHeader('Content-Type','application/json');res.end(JSON.stringify({choices:[{message:{content:output},finish_reason:'stop'}]}));});await new Promise(r=>server.listen(0,'127.0.0.1',r));setSetting('provider',{baseUrl:`http://127.0.0.1:${server.address().port}`,model:'fixture-classifier'});
 const create=()=>save('note',{title:'新的想法',content:'设计一个方便记录的工具',attachments:[]});const handler=classificationHandlers['classify-note'];
 try{
  const note=create(),job=enqueueClassification(note);fileJobs.claim(job.id,'one',60000);const result=await handler.run(job);assert.equal(fileJobs.finish(job.id,'one',result,handler.commit),true);const classified=get(note.id,'note');assert.equal(classified.categoryId,'category-idea');assert.equal(classified.classification.model,'fixture-classifier');assert.equal(classified.content,note.content);
  const race=create(),late=enqueueClassification(race);fileJobs.claim(late.id,'late',60000);const oldResult=await handler.run(late);setCategories({opId:'manual-wins-123',categoryId:'category-work',notes:[{id:race.id,revision:race.revision}]});assert.throws(()=>fileJobs.finish(late.id,'late',oldResult,handler.commit),/人工归类/);assert.equal(get(race.id,'note').categoryId,'category-work');assert.equal(enqueueClassification(get(race.id,'note')),null);assert.equal(all('classificationCorrection').length,1);
  for(const invalid of [{categoryId:'invented',reason:'不存在'}, {categoryId:'category-life',reason:'x',confirmed:true},null]){const n=create(),j=enqueueClassification(n);output=JSON.stringify(invalid);await assert.rejects(()=>handler.run(j));assert.equal(get(n.id,'note').revision,n.revision);assert.equal(get(n.id,'note').categoryId,undefined);}
  output=JSON.stringify({categoryId:'category-idea',reason:'灵感'});const edited=create(),pending=enqueueClassification(edited);const draft=await handler.run(pending);save('note',{...edited,content:'用户改了正文'},edited.revision);assert.throws(()=>handler.commit(pending,draft),/已修改/);assert.equal(get(edited.id,'note').categoryId,undefined);
 }finally{await new Promise(r=>server.close(r));db.close();await rm(dir,{recursive:true,force:true});}
});
