import {test} from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,rm} from 'node:fs/promises';import path from 'node:path';import os from 'node:os';
test('context compression resumes completed pieces, preserves role boundaries, and rejects stale partials',async()=>{
 const dir=await mkdtemp(path.join(os.tmpdir(),'shiguang-context-parts-'));process.env.DATA_DIR=dir;process.env.SEED_DEMO='false';process.env.WORKER_MODE='true';const {db,getSetting}=await import('../server/store.mjs');const {compressContextBatch}=await import('../server/agent/context-compression.mjs');
 try{const body='甲'.repeat(18000)+'最后约束：周五确认，尚未完成。';const batch=[{id:'turn1',query:'我的预算是100元，不接受付费工具。',body,references:[{id:'note',revision:1}]}];const calls=[];let fail=true;const generate=async(_system,prompt)=>{const value=JSON.parse(prompt);calls.push(value);if(value.role==='助手'&&value.part===2&&fail){fail=false;throw new Error('服务中断');}return value.segments?'用户预算100元；助手建议尚未确认；周五确认，尚未完成。':value.role==='用户'?'用户约束：预算100元，不接受付费工具。':'助手建议，尚未确认为用户事实。';};
 await assert.rejects(compressContextBatch('topic',{text:''},batch,generate,()=>{}),/服务中断/);assert.equal(getSetting('thread-context-parts:topic').parts.length,2);const result=await compressContextBatch('topic',{text:''},batch,generate,()=>{});assert.equal(result.pending,undefined);assert.match(result.text,/周五确认/);assert.equal(calls.filter(c=>c.role==='用户').length,1,'successful user chunk is not regenerated');const pieces=calls.filter(c=>c.role==='助手');assert.equal(pieces[0].part,1);assert.equal(pieces.at(-1).content,body.slice(16000));assert.deepEqual(pieces.at(-1).references,[{id:'note',revision:1}]);
 let checks=0;await assert.rejects(compressContextBatch('stale',{text:''},batch,generate,()=>{if(++checks>1)throw new Error('来源已变化');}),/来源已变化/);assert.equal(getSetting('thread-context-parts:stale',null),null);
 const partial=await compressContextBatch('budget',{text:''},batch,generate,()=>{},{maxCalls:1});assert.equal(partial.pending,true);assert.equal(partial.completed,1);assert.equal(partial.total,4);
 }finally{db.close();await rm(dir,{recursive:true,force:true});}
});
