import {test} from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,rm} from 'node:fs/promises';import path from 'node:path';import os from 'node:os';
test('concurrent sends share generation and atomically retain a replayable conversation',async()=>{
 const dir=await mkdtemp(path.join(os.tmpdir(),'shiguang-send-'));process.env.DATA_DIR=dir;process.env.SEED_DEMO='false';process.env.WORKER_MODE='true';const {save,all,remove,db}=await import('../server/store.mjs');const {conversationRequest}=await import('../server/conversation-requests.mjs');
 try{const body={opId:'send-operation-1',query:'原始问题',threadId:'same-thread',references:[{kind:'note',id:'source',revision:1}]};let calls=0,release;const gate=new Promise(r=>release=r);const work=async commit=>{calls++;await gate;return commit(()=>save('conversation',{threadId:'same-thread',query:body.query,body:'一次回答'}));};const first=conversationRequest(body,work),second=conversationRequest({...body},work);await Promise.resolve();assert.equal(calls,1);await assert.rejects(conversationRequest({...body,query:'另一个问题'},work),/不同/);release();const [a,b]=await Promise.all([first,second]);assert.equal(a.id,b.id);assert.equal(all('conversation').length,1);
 const reloaded=await import('../server/conversation-requests.mjs?restart=1');const retry=await reloaded.conversationRequest(body,()=>{throw new Error('cannot generate again');});assert.equal(retry.id,a.id);
 await assert.rejects(conversationRequest({...body,references:[{kind:'note',id:'source',revision:2}]},work),/不同/);
 remove(a.id,'conversation',a.revision);await assert.rejects(conversationRequest(body,work),/已删除/);assert.equal(all('conversation').length,0);
 const failed={opId:'failed-operation-1',query:'失败重试'};await assert.rejects(conversationRequest(failed,async commit=>commit(()=>{save('conversation',{query:'不应保存'});throw new Error('commit failed');})),/commit failed/);assert.equal(all('conversation').length,0);const ok=await conversationRequest(failed,async commit=>commit(()=>save('conversation',{query:'成功重试'})));assert.equal(ok.query,'成功重试');
 }finally{db.close();await rm(dir,{recursive:true,force:true});}
});
