import {test,after} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
const root=await mkdtemp(join(tmpdir(),'business-export-'));
Object.assign(process.env,{DATA_DIR:root,SEED_DEMO:'false',WORKER_MODE:'true'});
const {save,setSetting,db}=await import('../server/store.mjs');
const {businessDataExport}=await import('../server/core/backups/data-export.mjs');
after(async()=>{db.close();await rm(root,{recursive:true,force:true});});
test('readable export preserves cross-module relationships and excludes private runtime data',()=>{
 setSetting('provider',{apiKey:'test-credential-not-exported'});
 const project=save('project',{title:'PersonalAgent'});
 const category=save('noteCategory',{title:'开发',projectId:project.id});
 const note=save('note',{content:'原文\n1. 段落',categoryId:category.id,projectId:project.id,attachments:[{key:'private-upload-key',name:'图片.png',mime:'image/png'}]});
 const thread=save('thread',{title:'原话题'});
 save('sourceThread',{sourceKind:'note',sourceId:note.id,threadId:thread.id});
 save('classificationCorrection',{noteId:note.id,toCategoryId:category.id});
 const task=save('workTask',{title:'每日学习',projectId:project.id});
 const run=save('workRun',{taskId:task.id,status:'review'});
 save('supervisionEvidenceCheck',{runId:run.id,taskId:task.id,state:'accepted'});
 save('supervisionRecap',{taskId:task.id,text:'复盘正文'});
 save('researchInput',{taskId:task.id,text:'补充问题'});
 save('researchExternal',{taskId:task.id,text:'网页回填'});
 save('libraryFile',{title:'资料',content:'完整解析正文'});
 save('accountingImport',{original:{key:'private-bill-key',sha256:'abc',name:'账单.xlsx'}});
 const output=businessDataExport(),json=JSON.stringify(output);
 assert.equal(output.version,2);assert.match(output.exportNotice,/不包含原文件/);
 assert.equal(output.notes[0].content,note.content);assert.equal(output.notes[0].projectId,output.projects[0].id);
 assert.equal(output.sourceThreads[0].threadId,output.threads[0].id);
 assert.equal(output.supervisionEvidenceChecks[0].runId,output.workRuns[0].id);
 assert.equal(output.classificationCorrections[0].noteId,note.id);
 assert.equal(output.library[0].content,'完整解析正文');
 for(const name of ['supervisionRecaps','researchInputs','researchExternal','noteCategories'])assert.equal(output.coverage[name],1);
 assert.equal(output.accountingImports[0].original.sha256,'abc');
 assert.doesNotMatch(json,/test-credential-not-exported|private-upload-key|private-bill-key/);
});
