import {test,after} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import os from 'node:os';
import path from 'node:path';
const directory=mkdtempSync(path.join(os.tmpdir(),'library-pages-'));
Object.assign(process.env,{DATA_DIR:directory,SEED_DEMO:'false',WORKER_MODE:'true'});
const {db,save,get}=await import('../server/store.mjs');
const {libraryPage,libraryStatus,libraryKeywordSearch}=await import('../server/library.mjs');
const {parseLibraryQuery,libraryCandidateIds}=await import('../server/library-filters.mjs');
test('library pages include sources older than 500, filter before pagination and reject stale or cross-filter cursors',()=>{
 for(let i=0;i<537;i++)save('libraryFile',{title:'资料'+i,content:'不应泄漏整段正文'.repeat(300),sourcePath:'项目/'+i+'.txt',status:i<7?'failed':'ready'});
 const visited=[];let cursor;
 do{const page=libraryPage({limit:30,...(cursor?{cursor}:{})});assert.equal(page.total,537);assert.ok(page.items.every(x=>!('content' in x)));visited.push(...page.items.map(x=>x.id));cursor=page.nextCursor;}while(cursor);
 assert.equal(visited.length,537);assert.equal(new Set(visited).size,537);
 const failed=libraryPage({status:'failed',limit:3});assert.equal(failed.total,7);assert.ok(failed.items.every(x=>x.status==='failed'));
 assert.throws(()=>libraryPage({status:'ready',cursor:failed.nextCursor}),e=>e.status===400);
 const first=libraryPage({limit:30});const changed=get(first.items[0].id,'libraryFile');save('libraryFile',{...changed,title:'修订'},changed.revision);
 assert.throws(()=>libraryPage({cursor:first.nextCursor}),e=>e.status===409);
 assert.throws(()=>libraryPage({limit:0}),e=>e.status===400);
 assert.throws(()=>libraryPage({status:'unknown'}),e=>e.status===400);
 assert.equal(libraryStatus({includeFiles:false}).files.length,0);
 assert.equal(libraryStatus({includeFiles:false}).counts.discovered,537);
});
test('combined filters agree for full list, keyword and vector candidates, including timezone and directory boundaries',()=>{
 const project=save('project',{name:'同名项目'}),other=save('project',{name:'同名项目'});
 const base={title:'筛选资料',content:'稀有筛选关键词',sourcePath:'文档/方案/a.PDF',status:'ready',projectId:project.id,createdAt:'2026-09-28T16:00:00.000Z'};
 const valid=save('libraryFile',base),nested=save('libraryFile',{...base,sourcePath:'文档/方案/子目录/b.pdf',createdAt:'2026-09-29T15:59:59.999Z'});
 for(const patch of [{sourcePath:'文档/方案外/a.pdf'},{sourcePath:'文档/方案/a.md'},{projectId:other.id},{createdAt:'2026-09-28T15:59:59.999Z'},{createdAt:'2026-09-29T16:00:00.000Z'},{status:'failed'}])save('libraryFile',{...base,...patch});
 const filters=parseLibraryQuery({status:'ready',projectId:project.id,directory:'文档\\方案/',extension:'.PDF',dateFrom:'2026-09-29',dateTo:'2026-09-29'});
 const expected=[valid.id,nested.id].sort();
 assert.deepEqual(libraryPage(filters).items.map(f=>f.id).sort(),expected);
 assert.deepEqual(libraryKeywordSearch('稀有筛选关键词',filters).map(f=>f.id).sort(),expected);
 assert.deepEqual(libraryCandidateIds(filters).sort(),expected);
 const first=libraryPage({...filters,limit:1});
 assert.throws(()=>libraryPage({...filters,directory:'文档',cursor:first.nextCursor}),e=>e.status===400);
 for(const patch of [{dateFrom:'2026-02-30'},{dateFrom:'2026-09-30'},{directory:'../文档'},{projectId:'missing'},{extension:['.pdf']},{unexpected:true}])assert.throws(()=>libraryPage({...filters,...patch}),e=>e.status===400);
 assert.equal(libraryKeywordSearch('稀有筛选关键词',{...filters,status:'failed'}).length,0);
});
after(()=>{db.close();rmSync(directory,{recursive:true,force:true});});
