import {test,after} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import path from 'node:path';
import os from 'node:os';
const directory=mkdtempSync(path.join(os.tmpdir(),'library-index-status-'));
Object.assign(process.env,{DATA_DIR:directory,SEED_DEMO:'false',WORKER_MODE:'true'});
const {db,save,get,setSetting}=await import('../server/store.mjs');
await import('../server/index-migration.mjs');
const {indexCollection}=await import('../server/embedding-contract.mjs');
const {libraryIndexState,retryLibraryIndex}=await import('../server/library-index-state.mjs');
const config={model:'test-embedding',qdrant:'http://qdrant.test',embedding:'http://embedding.test'};
const collection=indexCollection(config);
test('parsing ready is not indexing ready; configuration, receipts, errors and source revisions remain distinct',()=>{
 const file=save('libraryFile',{title:'资料',content:'正文',status:'ready'});
 assert.equal(libraryIndexState(file).state,'unconfigured');setSetting('retrieval',config);
 assert.equal(libraryIndexState(file).state,'queued');
 db.prepare('DELETE FROM search_outbox WHERE entity_id=?').run(file.id);
 setSetting('indexed:'+collection+':'+file.id,['some-point']);assert.equal(libraryIndexState(file).state,'unknown');
 setSetting('index-receipt:'+collection+':'+file.id,{revision:file.revision,chunks:1});assert.equal(libraryIndexState(file).state,'indexed');
 const changed=save('libraryFile',{...file,title:'改名'},file.revision);assert.equal(libraryIndexState(changed).state,'queued');
 assert.throws(()=>retryLibraryIndex(file.id,{revision:file.revision}),e=>e.status===409);
 setSetting('index-error:'+collection+':'+file.id,{revision:changed.revision,error:'Embedding不可用'});assert.equal(libraryIndexState(changed).state,'failed');
 assert.equal(retryLibraryIndex(file.id,{revision:changed.revision}).state,'queued');
 const archived=save('libraryFile',{...changed,status:'archived'},changed.revision);assert.equal(libraryIndexState(archived).state,'excluded');assert.throws(()=>retryLibraryIndex(file.id,{revision:archived.revision}),e=>e.status===409);
 assert.equal(libraryIndexState({...archived,status:'ready',content:''}).state,'waiting_parse');
});
test('managed failed job retries only its current source; rebuild and protocol invalidation defeat old completion',()=>{
 const file=save('libraryFile',{title:'队列资料',status:'ready',content:'正文'});
 db.prepare("INSERT INTO index_migrations(id,target,collection_name,state,cursor,created_at) VALUES('active',?,?,'building',0,'now')").run(JSON.stringify(config),collection);setSetting('activeIndexMigration','active');
 db.prepare("INSERT INTO index_migration_items VALUES('active',?,'libraryFile',?,'pending','job-one')").run(file.id,file.revision);
 db.prepare("INSERT INTO background_jobs(id,operation_key,kind,entity_id,revision,payload,state,error,updated_at,due_at) VALUES('job-one','one','index-migration-source',?,?,'{}','failed','网络失败',0,0)").run(file.id,file.revision);
 assert.equal(libraryIndexState(file).state,'failed');assert.equal(retryLibraryIndex(file.id,{revision:file.revision}).state,'queued');
 assert.equal(get(file.id,'libraryFile').revision,file.revision);
 db.prepare("UPDATE background_jobs SET state='running' WHERE id='job-one'").run();setSetting('index-progress:'+collection+':'+file.id,{revision:file.revision,next:2});assert.equal(libraryIndexState(file).completedChunks,2);assert.equal(libraryIndexState(file).state,'indexing');
 db.prepare("UPDATE index_migration_items SET state='indexed' WHERE entity_id=?").run(file.id);setSetting('indexed:'+collection+':'+file.id,['one','two']);assert.equal(libraryIndexState(file).state,'indexed');
 setSetting('index-rebuild-required:'+collection,true);assert.equal(libraryIndexState(file).state,'queued');setSetting('index-rebuild-required:'+collection,false);
 db.prepare("UPDATE index_migrations SET state='invalidated' WHERE id='active'").run();assert.equal(libraryIndexState(file).state,'invalidated');assert.throws(()=>retryLibraryIndex(file.id,{revision:file.revision}),e=>e.status===409);
});
after(()=>{db.close();rmSync(directory,{recursive:true,force:true});});
