import {test,after,before} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,writeFile,readFile,rm} from 'node:fs/promises';
import {spawn} from 'node:child_process';
import {createServer} from 'node:http';
import path from 'node:path';
import os from 'node:os';
const root=await mkdtemp(path.join(os.tmpdir(),'shiguang-phase2-'));const source=path.join(root,'source');await mkdir(source);const text='章节正文\n'.repeat(3000)+'尾部独特证据';await writeFile(path.join(source,'学习.md'),text);await writeFile(path.join(source,'重复.md'),text);await writeFile(path.join(source,'unknown.zip'),'unknown');await mkdir(path.join(source,'node_modules'));await writeFile(path.join(source,'node_modules','junk.js'),'junk');
let child,cookie,model;const base='http://127.0.0.1:4448/api';
async function req(url,body){const r=await fetch(base+url,{method:body?'POST':'GET',headers:{cookie:cookie||'','Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});return {status:r.status,data:await r.json()};}
async function until(fn,timeout=5000){const deadline=Date.now()+timeout;while(Date.now()<deadline){if(await fn())return;await new Promise(r=>setTimeout(r,50));}throw new Error('等待超时');}
before(async()=>{model=createServer(async(req,res)=>{let body='';for await(const part of req)body+=part;const p=JSON.parse(body),system=p.messages[0].content;let content;if(system.includes('规划助手'))content=JSON.stringify({goal:'学习',conditions:'现有资料',steps:['检索','生成报告'],deliverable:'学习总结'});else if(system.includes('验收任务')){const input=JSON.parse(p.messages[1].content);content=JSON.stringify({results:input.conditions.map(c=>({conditionId:c.id,status:'satisfied',reason:'证据覆盖三个要点',evidence:[{sourceId:'text',quote:input.sources.find(s=>s.id==='text').content}]}))});}else{const t=JSON.parse(p.messages[1].content);content=JSON.stringify(t.goal.includes('外部')&&!t.logs.some(l=>l.type==='external')?{tool:'search_web',query:'最新部署文档'}:t.logs.length===0?{tool:'search_local',query:'尾部独特证据'}:t.outputs.length?{tool:'finish'}:{tool:'write_report',body:'# 学习总结\n\n学习.md 中的尾部独特证据，已整理为三个要点。\n\n仍需用户亲自学习并提交总结，不能仅凭生成报告认定完成。'});}res.setHeader('Content-Type','application/json');res.end(JSON.stringify({choices:[{message:{content},finish_reason:'stop'}]}));});await new Promise(r=>model.listen(4449,'127.0.0.1',r));child=spawn(process.execPath,['server/index.mjs'],{env:{...process.env,PORT:'4448',DATA_DIR:path.join(root,'.data'),COMPUTER_FILES_ROOT:source,SEED_DEMO:'false',LLM_BASE_URL:'http://127.0.0.1:4449/v1',LLM_MODEL:'test',QDRANT_URL:'',EMBEDDING_BASE_URL:''},stdio:['ignore','ignore','pipe']});let startupError='';child.stderr.on('data',chunk=>{startupError+=chunk.toString();});await until(async()=>{if(child.exitCode!==null)throw new Error('测试服务启动失败：'+startupError);try{return (await fetch(base+'/health')).ok;}catch{return false;}},20000);const r=await fetch(base+'/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code:'shiguang-demo'})});cookie=r.headers.get('set-cookie').split(';')[0];});
after(async()=>{if(child&&child.exitCode===null){child.kill();await new Promise(r=>child.once('exit',r));}await new Promise(r=>model.close(r));await rm(root,{recursive:true,force:true});});
test('copies deduplicated documents, preserves originals, searches the tail and tracks unknown files',async()=>{assert.equal((await req('/library/scan',{path:''})).status,200);await until(async()=>(await req('/library')).data.job.status==='done');let s=(await req('/library')).data;assert.equal(s.counts.ready,2);const file=s.files.find(f=>f.copyName);assert.equal((await fetch(base+'/library/'+file.id+'/file',{headers:{cookie}})).status,200);assert.equal(s.counts.duplicate,0);assert.equal(new Set(s.files.filter(f=>f.copyName).map(f=>f.copyName)).size,1);assert.equal(s.counts.pending,1);assert.equal(s.counts.discovered,3);assert.equal(await readFile(path.join(source,'学习.md'),'utf8'),text);const hits=(await req('/library/search?q='+encodeURIComponent('尾部独特证据'))).data.results;assert.ok(hits.some(h=>h.start>8000&&h.text.includes('尾部独特证据')));assert.equal((await req('/library/scan',{path:'../'})).status,400);await req('/library/scan',{path:''});await until(async()=>(await req('/library')).data.job.status==='done');s=(await req('/library')).data;assert.equal(s.counts.discovered,3);});
test('plan requires confirmation, execution creates an artifact, duration and evidence both gate completion',async()=>{const created=await req('/work-tasks',{goal:'学习尾部内容',minutes:45,repeat:'daily'});assert.equal(created.status,200);const task=created.data;assert.equal(task.status,'draft');assert.equal((await req('/work-tasks')).data.runs.length,0);assert.equal((await req('/work-tasks/'+task.id+'/action',{action:'start'})).status,200);await until(async()=>(await req('/work-tasks')).data.tasks[0].status==='review');const d=(await req('/work-tasks')).data;assert.equal(d.tasks[0].outputs.length,1);assert.equal((await fetch(base+'/work-tasks/'+task.id+'/artifacts/'+d.tasks[0].outputs[0],{headers:{cookie}})).status,200);const run=d.runs[0];const early={action:'confirm',opId:'confirm-before-evidence',evidenceRevision:1,assessmentId:'missing'};assert.equal((await req('/work-runs/'+run.id+'/action',early)).status,409);const review=await req('/work-runs/'+run.id+'/action',{action:'evidence',opId:'evidence-task-once',evidenceRevision:1,evidence:'三个要点与实践案例'});assert.equal(review.status,200);const confirm={action:'confirm',opId:'confirm-after-evidence',evidenceRevision:2,assessmentId:review.data.assessment.id};assert.equal((await req('/work-runs/'+run.id+'/action',confirm)).status,409);assert.equal((await req('/work-runs/'+run.id+'/action',{action:'adjust',opId:'adjust-task-45',minutes:45,reason:'已在纸上学习'})).status,200);assert.equal((await req('/work-runs/'+run.id+'/action',confirm)).data.status,'completed');assert.equal((await req('/work-runs/'+run.id+'/action',{action:'start'})).status,409);});

test('missing web search enters explicit handoff and resumes after external evidence',async()=>{const task=(await req('/work-tasks',{goal:'外部调研验收',web:true})).data;await req('/work-tasks/'+task.id+'/action',{action:'start'});await until(async()=>(await req('/work-tasks')).data.tasks.find(t=>t.id===task.id).status==='waiting');assert.equal((await req('/work-tasks/'+task.id+'/action',{action:'external',text:'用户带回的搜索资料，来源 https://example.com，仍待核实。'})).data.status,'paused');await req('/work-tasks/'+task.id+'/action',{action:'start'});await until(async()=>(await req('/work-tasks')).data.tasks.find(t=>t.id===task.id).status==='review');});
