import {test,after} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {randomUUID} from 'node:crypto';
const dir=await mkdtemp(join(tmpdir(),'research-thread-'));
process.env.DATA_DIR=dir;process.env.SEED_DEMO='false';process.env.WORKER_MODE='true';
const {db,save,get,setSetting,all}=await import('../server/store.mjs');
const {turnSignature}=await import('../server/agent/thread-context.mjs');
const {createResearchTask,validateResearchInput,researchHandoffBrief}=await import('../server/agent/research/research-tasks.mjs');
const {createResearchHandlers}=await import('../server/agent/research/research-jobs.mjs');
const {fileJobs}=await import('../server/jobs/file-jobs.mjs');
after(async()=>{db.close();await rm(dir,{recursive:true,force:true});});
const create=(threadId,references=[])=>createResearchTask({references,executionMode:'research',opId:randomUUID(),threadId,researchBrief:{topic:'学习数据库',questions:['如何实践？'],type:'learning',expectedOutput:'学习路径',web:false}});
test('research retains older constraints and summary provenance through planning and handoff',async()=>{
 const threadId=randomUUID();
 const turns=Array.from({length:8},(_,i)=>save('conversation',{threadId,createdAt:`2026-10-01T00:00:0${i}.000Z`,query:i?'继续讨论'+i:'必须本地运行，不上传原始资料',body:'建议仅供讨论 '+i,references:[],sources:[]}));
 const full=create(threadId);assert.equal(validateResearchInput(full).context.length,8);
 const summary={text:'用户要求本地运行；助手建议使用 SQLite，尚未确认。',covered:turns.slice(0,2).map(t=>t.id),signatures:Object.fromEntries(turns.slice(0,2).map(t=>[t.id,turnSignature(t)])),version:1};
 setSetting('thread-context:'+threadId,summary);
 const long=save('note',{title:'数据库实践笔记',content:'无关前言。\n'.repeat(2000)+'\n如何实践？先创建隔离测试库，再模拟事务回滚。'});
 const task=create(threadId,[{kind:'note',id:long.id,revision:long.revision}]),input=validateResearchInput(task);
 assert.equal(input.context.length,6);assert.equal(input.contextSummary.text,summary.text);assert.equal(input.contextSummary.sources.length,2);
 assert.match(researchHandoffBrief(task),/用户要求本地运行/);
 let planInput;const handlers=createResearchHandlers({generate:async args=>{planInput=JSON.parse(args.user);throw new Error('stop-after-capturing-plan');}});
 const job=fileJobs.claim(task.researchJobId,randomUUID(),60000);assert.ok(job);
 await assert.rejects(()=>handlers.research.run(job),/stop-after-capturing-plan/);
 const preview=planInput.sourcePreviews[0];assert.equal(preview.revision,long.revision);assert.equal(preview.truncated,true);assert.equal(preview.totalCharacters,long.content.length);assert.ok(preview.passages.length<=3);assert.ok(preview.passages.some(p=>p.quote.includes('先创建隔离测试库')));for(const p of preview.passages)assert.equal(p.quote,long.content.slice(p.start,p.end));
 assert.equal(planInput.topicSummary.text,summary.text);assert.equal(planInput.topicContext.length,6);assert.match(planInput.topicSummary.notice,/不等于已确认/);
 setSetting('thread-context:'+threadId,{...summary,text:'后续重建摘要',version:2});
 assert.equal(validateResearchInput(task).contextSummary.text,summary.text);
 save('conversation',{...get(turns[0].id,'conversation'),query:'已改变原始约束'},turns[0].revision);
 assert.throws(()=>validateResearchInput(task),/摘要依据已修改/);
 const largeThread=randomUUID();save('conversation',{threadId:largeThread,query:'长文',body:'长'.repeat(19000)});
 const before=all('workTask').length;assert.throws(()=>create(largeThread),/更新话题摘要/);assert.equal(all('workTask').length,before);
});
