import {test,after} from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,rm} from 'node:fs/promises';import os from 'node:os';import path from 'node:path';
const root=await mkdtemp(path.join(os.tmpdir(),'todo-supervision-'));Object.assign(process.env,{DATA_DIR:root,SEED_DEMO:'false',WORKER_MODE:'true'});
const {db,save,get,all,setSetting}=await import('../server/store.mjs');const {upgradeTodo:upgrade,assertTodoChange,assertTodoRemoval}=await import('../server/domain/notes/todo-supervision.mjs');const {carryTodo}=await import('../server/domain/notes/todo-days.mjs');const {assessRunEvidence:assess,confirmRunEvidence:confirm}=await import('../server/pet/supervision/supervision-evidence.mjs');const {petReminders}=await import('../server/pet/pet-reminders.mjs');
const body=(todo,opId)=>({opId,revision:todo.revision,minutes:0,repeat:'once',startTime:'09:00',time:'20:00',conditions:[{id:'result',kind:'evidence',required:true,description:'写阅读心得'}]});
test('upgrade creates one linked supervision-only task; guards prevent checkbox, deletion and carry bypass; confirmation alone completes original',async()=>{
 const todo=save('todo',{title:'读书',day:'2026-09-28',done:false}),input=body(todo,'todo-upgrade-once'),result=upgrade(todo.id,input);assert.deepEqual(upgrade(todo.id,input),result);assert.equal(all('workTask').length,1);assert.equal(all('workRun').length,1);
 const task=get(result.taskId,'workTask'),run=get(result.runId,'workRun'),linked=get(todo.id,'todo');assert.equal(task.executionMode,'supervision');assert.equal(task.status,'supervising');assert.equal(task.calls,0);assert.equal(linked.day,todo.day);assert.equal(linked.done,false);assert.equal(linked.supervisionRunId,run.id);
 assert.throws(()=>upgrade(todo.id,{...input,opId:'todo-upgrade-other'}),/已经升级/);assert.throws(()=>assertTodoChange(linked,{done:true}),/核对证据/);assert.throws(()=>assertTodoChange(linked,{day:'2099-01-01'}),/核对证据/);assert.throws(()=>assertTodoRemoval(linked),/来源/);assert.throws(()=>carryTodo(todo.id,{revision:linked.revision,targetDay:'2026-09-29'},new Date('2026-09-29T04:00:00Z')),/已升级/);
 setSetting('taskReminders',{quietStart:0,quietEnd:0});assert.equal(petReminders().items.some(item=>item.sourceKind==='todo'&&item.sourceId===todo.id),false);
 const checked=await assess(run.id,{action:'evidence',opId:'upgrade-evidence',evidenceRevision:1,evidence:'我的心得：先理解再实践。'},{generate:async()=>JSON.stringify({results:[{conditionId:'result',status:'satisfied',reason:'有心得',evidence:[{sourceId:'text',quote:'先理解再实践'}]}]})});assert.equal(get(todo.id,'todo').done,false);
 const confirmation={action:'confirm',opId:'upgrade-confirm',evidenceRevision:2,assessmentId:checked.assessment.id};const done=confirm(run.id,confirmation);assert.equal(done.status,'completed');const completed=get(todo.id,'todo');assert.equal(completed.done,true);assert.equal(completed.completedAt,done.confirmedAt);confirm(run.id,confirmation);assert.equal(get(todo.id,'todo').revision,completed.revision);
});
test('invalid, completed or stale todos produce no extra tasks',()=>{
 const todo=save('todo',{title:'已完成',day:'2026-09-29',done:true}),count=all('workTask').length;assert.throws(()=>upgrade(todo.id,body(todo,'completed-upgrade')),/已完成/);
 const open=save('todo',{title:'新待办',day:'2026-09-29',done:false});assert.throws(()=>upgrade(open.id,{...body(open,'invalid-upgrade'),conditions:[]}),error=>error.status===400);assert.throws(()=>upgrade(open.id,{...body(open,'stale-upgrade'),revision:open.revision+1}),/已更新/);assert.equal(all('workTask').length,count);
});
after(async()=>{db.close();await rm(root,{recursive:true,force:true});});
