import {lookup} from 'node:dns/promises';
import http from 'node:http';
import https from 'node:https';
import {isIP} from 'node:net';
import {mkdir,writeFile} from 'node:fs/promises';
import path from 'node:path';
import {DATA_DIR,get} from './store.mjs';
export function readLibrary(id,start=0,revision){const f=get(id,'libraryFile');if(!f?.copyName)throw new Error('资料尚无本地副本');if(revision!==undefined&&f.revision!==revision)throw new Error('关联资料已更新，请暂停任务并重新关联当前版本');if(f.status!=='ready')throw new Error('资料当前不是可读取的有效正文');const offset=Number(start);if(!Number.isInteger(offset)||offset<0||offset>(f.content?.length||0))throw new Error('正文读取位置无效');return {id,kind:'libraryFile',revision:f.revision,title:f.title,sourcePath:f.sourcePath,start:offset,end:Math.min(offset+12000,f.content?.length||0),total:f.content?.length||0,text:(f.content||'').slice(offset,offset+12000),notice:f.content?'':'尚未解析'};}
function publicAddress(address){if(isIP(address)===6)return !/^(::|fc|fd|fe[89ab]|ff)/i.test(address);const [a,b]=address.split('.').map(Number);return a>0&&a!==10&&a!==127&&a!==169&&a<224&&!(a===172&&b>=16&&b<=31)&&!(a===192&&b===168)&&!(a===100&&b>=64&&b<=127);}
export async function readPublicPage(input){let url=new URL(input);for(let redirect=0;redirect<4;redirect++){if(!['https:','http:'].includes(url.protocol)||url.username||url.password||url.port&&!['80','443'].includes(url.port))throw new Error('仅支持公开 HTTP(S) 网页');const hosts=await lookup(url.hostname.replace(/^\[|\]$/g,''),{all:true});if(!hosts.length||hosts.some(h=>!publicAddress(h.address)))throw new Error('不能读取本机或内网地址');const response=await new Promise((resolve,reject)=>{const request=(url.protocol==='https:'?https:http).get(url,{lookup:(_host,options,callback)=>{const found=hosts[0];if(options.all)callback(null,[found]);else callback(null,found.address,found.family);},signal:AbortSignal.timeout(15000)},response=>{resolve({status:response.statusCode,ok:response.statusCode>=200&&response.statusCode<300,headers:{get:key=>response.headers[key]},body:{getReader:()=>{const iterator=response[Symbol.asyncIterator]();return {read:()=>iterator.next(),cancel:async()=>response.destroy()};}}});});request.on('error',reject);});if(response.status>=300&&response.status<400){url=new URL(response.headers.get('location'),url);continue;}if(!response.ok)throw new Error('网页读取失败：'+response.status);if(!/text\/|application\/json/.test(response.headers.get('content-type')||''))throw new Error('当前只支持文本网页');const reader=response.body.getReader();const chunks=[];let length=0;while(true){const {done,value}=await reader.read();if(done)break;length+=value.length;if(length>2*1024*1024){await reader.cancel();throw new Error('网页超过 2 MB，请换一个具体页面');}chunks.push(value);}const raw=Buffer.concat(chunks).toString('utf8');const text=raw.replace(/<(script|style)\b[^>]*>[\s\S]*?<\/\1>/gi,'').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim();return {url:url.href,text:text.slice(0,24000),truncated:text.length>24000,readAt:new Date().toISOString()};}throw new Error('网页重定向过多');}
export async function persistArtifact(artifact){const dir=path.join(DATA_DIR,'task-artifacts');await mkdir(dir,{recursive:true});await writeFile(path.join(dir,artifact.id+'.r'+artifact.revision+'.md'),artifact.body,'utf8');}
