import {useEffect,useRef,useState} from 'react';
import {api,ApiError,post} from './api';
import {Modal,Spinner} from './components';
const expenses=['美食','日用','花呗','交通','房租/还款','其他支出','医疗','演出/漫展','旅游','衣物/化妆品','护肤品'],incomes=['工资','奖金','兼职','投资','其他'];
type Draft={type:string;amount:string;category:string;date:string;note:string;channel:string;merchant:string;sourceRef:string};
type Row={rowId:string;rowNumber:number;sheetName?:string;decision:string;decisionReason?:string;status:string;reason:string;issues:string[];rawCells:(string|null)[];values:{merchant?:string};draft:{type:string;amountCents:number|null;category:string;date:string;note:string;source:string;sourceRef:string};transactionId?:string};
type Batch={id:string;revision:number;status:string;notice:string;error:string;original:{name:string;url:string;mime:string};rows:Row[];offset:number;totalRows:number;notices?:string[];parsingStartedAt?:number;summary?:{dataRows:number;needsReview:number;excluded:number;duplicateRows:number}};
type Edit={rowId:string;rowNumber:number;sheetName?:string;decision:string;draft:Draft;reason:string;acceptWarnings:boolean;exclusionOverride:string;issues:string[];excluded:boolean};
type Review={reviewId:string;revision:number;reviewToken:string;choices:{rowId:string;decision:string;reason?:string;draft?:{date:string;category:string;amountCents:number;note:string}}[];duplicates:{rowId:string;matches:{kind:string;id:string;rowNumber?:number;sheetName?:string;date?:string;amountCents?:number;note?:string;basis:string[]}[]}[]};
type Classification={id:string;batchId:string;batchRevision:number;status:string;notice:string;inputs:{rowId:string;type:string;note:string}[];suggestions:{rowId:string;type:string;note:string;category:string}[]};
type Pending={path:string;body:Record<string,unknown>};
const storage='shiguang-accounting-import',pendingKey=storage+'-pending',uploadKey=storage+'-upload';
const id=()=>Array.from(crypto.getRandomValues(new Uint8Array(16)),n=>n.toString(16).padStart(2,'0')).join('');
function read<T>(key:string,fallback:T):T{try{return JSON.parse(sessionStorage.getItem(key)||'null')||fallback;}catch{return fallback;}}
const money=(n:number|null|undefined)=>n==null?'待核对':(n/100).toFixed(2);
const labels:Record<string,string>={review:'待核对',completed:'已核对',parse_failed:'解析失败',parsing:'解析中'};
export default function AccountingImports({onClose,onRefresh,onToast}:{onClose:()=>void;onRefresh:()=>Promise<void>;onToast:(s:string)=>void}){
 const saved=useRef(read<{batchId?:string;edits?:Record<string,Edit>;review?:Review}>(storage,{}));
 const [batches,setBatches]=useState<Batch[]>([]),[next,setNext]=useState<number|null>(null),[batch,setBatch]=useState<Batch|null>(null),[edits,setEdits]=useState<Record<string,Edit>>(saved.current.edits||{}),[review,setReview]=useState<Review|null>(saved.current.review||null),[ack,setAck]=useState<string[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[fieldErrors,setFieldErrors]=useState<Record<string,string>>({}),[pending,setPending]=useState<Pending|null>(()=>read(pendingKey,null));
 const [classifications,setClassifications]=useState<Classification[]>([]);
 const [uploadPending,setUploadPending]=useState<{opId:string;name:string;size:number}|null>(()=>read(uploadKey,null));
 const input=useRef<HTMLInputElement>(null),errorBox=useRef<HTMLDivElement>(null),batchRef=useRef<Batch|null>(null),running=useRef(false);
 useEffect(()=>{if(error)errorBox.current?.focus();},[error]);
 function persist(nextEdits=edits,nextReview=review,batchId=batchRef.current?.id){try{sessionStorage.setItem(storage,JSON.stringify({batchId,edits:nextEdits,review:nextReview}));}catch{setError('浏览器无法保存草稿，请保持此页面打开。');}}
 async function list(offset=0){const result=await api<{imports:Batch[];nextOffset:number|null}>('/accounting/imports?offset='+offset+'&limit=20');setBatches(old=>offset?[...old,...result.imports]:result.imports);setNext(result.nextOffset);}
 async function load(batchId:string,offset=0){const result=await api<Batch>(`/accounting/imports/${batchId}?offset=${offset}&limit=10`);batchRef.current=result;setBatch(result);await loadClassifications(batchId);return result;}
 async function loadClassifications(batchId:string){const result=await api<{classifications:Classification[]}>(`/accounting/imports/${batchId}/classifications`);setClassifications(result.classifications);}
 async function classify(){if(!batch)return;const rows=batch.rows.filter(r=>r.decision==='pending'&&edits[r.rowId]?.decision!=='skip').map(r=>({rowId:r.rowId,type:edits[r.rowId]?.draft.type||r.draft.type,note:edits[r.rowId]?.draft.note??r.draft.note}));if(!rows.length)throw new Error('当前页没有待核对账单。');if(rows.some(r=>!['income','expense'].includes(r.type)||r.note.length>1000))throw new Error('请先修正本页账单的收支方向和超长备注，再请求分类。');await send<Classification>(`/accounting/imports/${batch.id}/classify`,{revision:batch.revision,rows});await loadClassifications(batch.id);}
 async function run(action:()=>Promise<void>){if(running.current)return;running.current=true;setBusy(true);setError('');try{await action();}catch(e){setError((e as Error).message);}finally{running.current=false;setBusy(false);}}
 useEffect(()=>{void run(async()=>{await list();if(saved.current.batchId)await load(saved.current.batchId);});},[]);
 async function select(b:Batch){if(batch?.id===b.id){await load(b.id,batch.offset);return;}if(pending)throw new Error('请先恢复未收到确认的操作。');if(batch?.id!==b.id&&Object.keys(edits).length&&!window.confirm('切换批次会放下当前未提交的编辑，是否继续？'))return;await load(b.id);setEdits({});setReview(null);setAck([]);persist({},null,b.id);}
 function edit(row:Row,patch:Partial<Edit>){const current=edits[row.rowId]||{rowId:row.rowId,rowNumber:row.rowNumber,sheetName:row.sheetName,decision:'pending',draft:{...row.draft,amount:row.draft.amountCents==null?'':money(row.draft.amountCents),channel:row.draft.source,merchant:row.values.merchant||''},reason:'',acceptWarnings:false,exclusionOverride:'',issues:row.issues,excluded:row.status==='excluded'};const updated={...edits,[row.rowId]:{...current,...patch}};setEdits(updated);setReview(null);setAck([]);persist(updated,null);}
 async function send<T>(path:string,body:Record<string,unknown>):Promise<T>{if(pending)throw new Error('上一项操作还未收到确认，请先恢复。');const operation={path,body:{...body,opId:id()}};sessionStorage.setItem(pendingKey,JSON.stringify(operation));setPending(operation);return execute<T>(operation);}
 async function execute<T>(operation:Pending):Promise<T>{try{const result=await post<T>(operation.path,operation.body);if(!result||typeof result!=='object'||!('reviewId' in result||'batchId' in result||'id' in result))throw new ApiError('服务器确认内容不完整，请恢复同一操作。',502);sessionStorage.removeItem(pendingKey);setPending(null);return result;}catch(e){if(e instanceof ApiError&&e.status>=400&&e.status<500){sessionStorage.removeItem(pendingKey);setPending(null);}throw e;}}
 async function afterCommit(result:{batchId:string;imported:number;skipped:number}){setEdits({});setReview(null);setAck([]);persist({},null,result.batchId);onToast(`已入账 ${result.imported} 笔，明确跳过 ${result.skipped} 行`);await load(result.batchId,batch?.offset||0);await list();await onRefresh();}
 async function recover(){if(!pending)return;const result=await execute<Review&Batch&{batchId:string;imported:number;skipped:number}>(pending);if(pending.path.endsWith('/commit'))await afterCommit(result);else if(pending.path.endsWith('/classify')){if(batch)await loadClassifications(batch.id);}else if(pending.path.endsWith('/review')){setReview(result);persist(edits,result);}else{await load(result.id);await list();}}
 async function upload(file:File){if(Object.keys(edits).length&&!window.confirm('上传新文件会放下当前未提交的编辑，是否继续？'))return;const operation=uploadPending||{opId:id(),name:file.name,size:file.size};if(operation.name!==file.name||operation.size!==file.size)throw new Error('请重新选择上次上传的同一文件，或先明确结束上次上传。');sessionStorage.setItem(uploadKey,JSON.stringify(operation));setUploadPending(operation);const form=new FormData();form.append('opId',operation.opId);form.append('file',file);const result=await api<Batch>('/accounting/imports',{method:'POST',body:form});if(!result.id)throw new Error('上传未收到有效确认，请用同一文件重试。');sessionStorage.removeItem(uploadKey);setUploadPending(null);setEdits({});setReview(null);persist({},null,result.id);await load(result.id);await list();}
 async function prepare(){if(!batch)return;const selected=Object.values(edits).filter(e=>e.decision!=='pending'),errors:Record<string,string>={};if(!selected.length)throw new Error('先选择至少一行的入账或跳过决定。');for(const e of selected){const add=(field:string,message:string)=>{errors[e.rowId+'.'+field]=message;};if(e.decision==='skip'){if(!e.reason.trim())add('reason','请说明跳过原因。');continue;}const d=e.draft;if(!['income','expense'].includes(d.type))add('type','请选择收支方向。');if(!/^(0|[1-9]\d*)(\.\d{1,2})?$/.test(d.amount)||Number(d.amount)<=0||Number(d.amount)>1e9)add('amount','金额应大于0、最多两位小数且不超过10亿元。');if(!(d.type==='income'?incomes:expenses).includes(d.category))add('category','请选择分类，未知分类不自动兜底。');if(!/^\d{4}-\d{2}-\d{2}$/.test(d.date)||!Number.isFinite(Date.parse(d.date+'T00:00:00Z'))||new Date(d.date+'T00:00:00Z').toISOString().slice(0,10)!==d.date)add('date','请填写真实日期。');if(d.note.length>1000)add('note','备注超过1000字，请编辑；原文仍保留。');if(!['wechat','alipay','manual','ocr'].includes(d.channel))add('channel','请选择渠道。');if((e.issues.length||e.excluded)&&!e.acceptWarnings)add('warnings','请确认已经核对本行提示。');if(e.excluded&&!e.exclusionOverride.trim())add('exclusionOverride','仅在识别有误时说明更正原因。');}setFieldErrors(errors);if(Object.keys(errors).length)throw new Error('部分行需要修改，请查看字段下方提示；其他页面的编辑也保留着。');const choices=selected.map(e=>e.decision==='skip'?{rowId:e.rowId,decision:'skip',reason:e.reason}:{rowId:e.rowId,decision:'include',draft:{type:e.draft.type,amount:e.draft.amount,category:e.draft.category,date:e.draft.date,note:e.draft.note,channel:e.draft.channel,merchant:e.draft.merchant,sourceRef:e.draft.sourceRef},acceptWarnings:e.acceptWarnings,...(e.exclusionOverride.trim()?{exclusionOverride:e.exclusionOverride}:{})});const result=await send<Review>(`/accounting/imports/${batch.id}/review`,{revision:batch.revision,choices});setReview(result);setAck([]);persist(edits,result);}
 function field(row:Row,e:Edit,name:keyof Draft,title:string,options?:string[]){const key=row.rowId+'.'+name,problem=fieldErrors[key],props={id:key,value:e.draft[name],disabled:busy||!!pending,'aria-invalid':!!problem,'aria-describedby':problem?key+'-error':undefined,onChange:(event:React.ChangeEvent<HTMLInputElement|HTMLSelectElement|HTMLTextAreaElement>)=>edit(row,{draft:{...e.draft,[name]:event.target.value,...(name==='type'?{category:''}:{})}})};return <label key={name} htmlFor={key}>{title}{options?<select {...props}><option value="">请选择</option>{options.map(o=><option key={o} value={o}>{({expense:'支出',income:'收入',wechat:'微信',alipay:'支付宝',manual:'手工/渠道不明',ocr:'历史截图/渠道不明'} as Record<string,string>)[o]||o}</option>)}</select>:name==='note'?<textarea {...props} rows={3}/>:<input {...props} type={name==='date'?'date':'text'} inputMode={name==='amount'?'decimal':undefined}/>} {problem&&<small id={key+'-error'} className="import-error">{problem}</small>}</label>;}
 return <Modal title="账单导入与核对" wide onClose={()=>{if(!busy){persist();onClose();}}}><section className="account-import-panel phase-panel">
 <div className="phase-actions"><button className="btn primary" disabled={busy||!!pending} onClick={()=>input.current?.click()}>上传账单 / 截图</button><button className="btn secondary" disabled={busy} onClick={()=>void run(async()=>{await list();if(batch)await load(batch.id,batch.offset);})}>刷新批次</button>{busy&&<Spinner label="处理中"/>}</div><input hidden ref={input} type="file" accept=".xlsx,image/png,image/jpeg,image/webp" onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(file)void run(()=>upload(file));}}/>
 {error&&<div role="alert" ref={errorBox} tabIndex={-1} className="accounting-import-notice import-error">{error}</div>}
 {pending&&<div className="accounting-import-notice">上次操作尚未收到确认。请恢复同一操作，避免重复入账。<button className="btn secondary" disabled={busy} onClick={()=>void run(recover)}>恢复上次操作</button></div>}
 {uploadPending&&<div className="accounting-import-notice">上次上传尚未确认：{uploadPending.name}。重新选择同一文件可继续；也可先查看下面是否已有批次。<button className="btn secondary" disabled={busy} onClick={()=>{if(window.confirm('先检查批次列表，确认不需要恢复这次上传后再结束。结束后再次上传会创建独立批次。')){sessionStorage.removeItem(uploadKey);setUploadPending(null);}}}>结束上次上传</button></div>}
 <details open={!batch}><summary>已保存的导入批次（可继续核对）</summary>{!batches.length&&!busy&&<p>还没有导入批次。上传后原文件会保留在拾光中。</p>}<div className="account-import-batches">{batches.map(b=><button className="btn secondary" key={b.id} disabled={busy||!!pending} onClick={()=>void run(()=>select(b))}>{b.original.name} · {labels[b.status]||b.status}</button>)}</div>{next!==null&&<button className="btn secondary" disabled={busy} onClick={()=>void run(()=>list(next))}>更多批次</button>}</details>
 {batch&&<><header><h2>{batch.original.name}</h2><a href={batch.original.url}>下载原账单</a>{batch.original.mime.startsWith('image/')&&<a href={batch.original.url}><img src={batch.original.url} alt="已保存的账单原图，点击下载" style={{display:'block',maxWidth:'100%',maxHeight:400,objectFit:'contain',marginTop:16}}/></a>}<p>{labels[batch.status]||batch.status} · 共 {batch.totalRows} 行。{batch.notice}</p>{batch.summary&&<p>待核对异常 {batch.summary.needsReview} 行 · 建议排除 {batch.summary.excluded} 行 · 疑似重复 {batch.summary.duplicateRows} 行（可能重叠）</p>}{batch.error&&<p role="alert">{batch.error}</p>}{batch.notices?.map(n=><p key={n}>{n}</p>)}</header>
 {['parse_failed','parsing'].includes(batch.status)&&<button className="btn secondary" disabled={busy||!!pending} onClick={()=>void run(async()=>{const result=await send<Batch>(`/accounting/imports/${batch.id}/reparse`,{revision:batch.revision});await load(result.id);await list();})}>重试解析原件</button>}
 {batch.status==='review'&&<div><button className="btn secondary" disabled={busy||!!pending} onClick={()=>void run(classify)}>AI 建议本页分类</button><p>仅向 AI 发送本页的收支方向和备注。建议不自动入账，也不覆盖人工编辑。</p>{classifications[0]&&<p role="status">{classifications[0].notice}{classifications[0].status==='running'&&' 若等待较久，可刷新查看结果；服务中断后可重新请求分类。'}</p>}</div>}
 <div className="account-import-rows">{batch.rows.map(row=>{const e=edits[row.rowId],latest=classifications.find(c=>c.inputs.some(i=>i.rowId===row.rowId)),suggestion=latest?.suggestions.find(c=>c.rowId===row.rowId),suggestionMatches=suggestion&&suggestion.type===(e?.draft.type||row.draft.type)&&suggestion.note===(e?.draft.note??row.draft.note);return <article key={row.rowId} id={row.rowId}><h3>{row.sheetName?row.sheetName+' · ':''}第 {row.rowNumber} 行 · {row.draft.date||'日期待核对'} · ¥{money(row.draft.amountCents)}</h3><p>{row.draft.note||'无说明'}</p>{row.reason&&<p>解析建议：{row.reason}</p>}{row.issues.map(issue=><p className="import-error" key={issue}>{issue}</p>)}<details><summary>查看提取内容 / 原始单元格</summary><pre>{row.rawCells.map((v,i)=>`${i+1}: ${v??''}`).join('\n')}</pre></details>{row.decision!=='pending'?<p>已{row.decision==='include'?'入账':'跳过'} · {row.decisionReason||'已确认'}{row.transactionId&&'（可在账单明细中查看和修改）'}</p>:<><label>本行决定<select disabled={busy||!!pending} value={e?.decision||'pending'} onChange={event=>edit(row,{decision:event.target.value})}><option value="pending">暂不处理</option><option value="include">核对后入账</option><option value="skip">明确跳过</option></select></label>{e?.decision==='skip'&&<label>跳过原因<textarea value={e.reason} disabled={busy||!!pending} onChange={event=>edit(row,{reason:event.target.value})}/><small className="import-error">{fieldErrors[row.rowId+'.reason']}</small></label>}{suggestion&&<p>AI 建议：{suggestion.category} {suggestionMatches?<button className="btn secondary" disabled={busy||!!pending} onClick={()=>{const draft=e?.draft||{...row.draft,amount:money(row.draft.amountCents),channel:row.draft.source,merchant:row.values.merchant||''};edit(row,{decision:'include',draft:{...draft,category:suggestion.category}});}}>应用此分类</button>:<span>（描述或收支方向已修改，请重新生成建议）</span>}</p>}{e?.decision==='include'&&<><div className="account-import-fields">{field(row,e,'type','收支方向',['expense','income'])}{field(row,e,'amount','金额（元）')}{field(row,e,'category','分类',e.draft.type==='income'?incomes:expenses)}{field(row,e,'date','发生日期')}{field(row,e,'channel','支付渠道',['wechat','alipay','manual','ocr'])}{field(row,e,'merchant','交易对方')}{field(row,e,'sourceRef','原交易标识')}{field(row,e,'note','备注')}</div>{(row.issues.length>0||row.status==='excluded')&&<label><input type="checkbox" disabled={busy||!!pending} checked={e.acceptWarnings} onChange={event=>edit(row,{acceptWarnings:event.target.checked})}/>我已核对本行提示及原件<small className="import-error">{fieldErrors[row.rowId+'.warnings']}</small></label>}{row.status==='excluded'&&<label>若排除建议有误，请说明更正原因<textarea disabled={busy||!!pending} value={e.exclusionOverride} onChange={event=>edit(row,{exclusionOverride:event.target.value})}/><small className="import-error">{fieldErrors[row.rowId+'.exclusionOverride']}</small></label>}</>}</>}</article>;})}</div>
 <div className="phase-actions"><button className="btn secondary" disabled={busy||batch.offset===0} onClick={()=>void run(()=>load(batch.id,Math.max(0,batch.offset-10)).then(()=>{}))}>上一页</button><span>{batch.totalRows?batch.offset+1:0}–{Math.min(batch.offset+10,batch.totalRows)} / {batch.totalRows} 行</span><button className="btn secondary" disabled={busy||batch.offset+10>=batch.totalRows} onClick={()=>void run(()=>load(batch.id,batch.offset+10).then(()=>{}))}>下一页</button></div>
 {batch.status==='review'&&<button className="btn primary" disabled={busy||!!pending} onClick={()=>void run(prepare)}>核对本次决定（{Object.values(edits).filter(e=>e.decision!=='pending').length} 行）</button>}
 {review&&<section className="account-import-confirm"><h2>最后核对</h2>{review.choices.map(c=><p key={c.rowId}>{edits[c.rowId]?.sheetName?edits[c.rowId].sheetName+' · ':''}第 {edits[c.rowId]?.rowNumber??c.rowId} 行：{c.decision==='include'?`入账 ¥${money(c.draft?.amountCents)} · ${c.draft?.category} · ${c.draft?.date}`:`跳过 · ${c.reason}`}</p>)}{review.duplicates.filter(d=>d.matches.length).map(d=><div key={d.rowId}><h3>{edits[d.rowId]?.sheetName?edits[d.rowId].sheetName+' · ':''}第 {edits[d.rowId]?.rowNumber??d.rowId} 行有疑似重复</h3><ul>{d.matches.map(m=><li key={m.kind+m.id}>{m.kind==='importRow'?`本批次${m.sheetName?'「'+m.sheetName+'」':''}第${m.rowNumber}行`:`已入账：${m.date} · ¥${money(m.amountCents)} · ${m.note||m.id}`} · {m.basis.some(b=>b.includes('trade_id'))?'交易标识相同':'日期、金额和对方相似'}{m.basis.some(b=>b.startsWith('unverified'))?'（渠道未核实）':''}</li>)}</ul><label><input type="checkbox" checked={ack.includes(d.rowId)} disabled={busy||!!pending} onChange={e=>setAck(old=>e.target.checked?[...old,d.rowId]:old.filter(v=>v!==d.rowId))}/>核对后仍保留{edits[d.rowId]?.sheetName?edits[d.rowId].sheetName+' · ':''}第 {edits[d.rowId]?.rowNumber??d.rowId} 行，不自动跳过</label></div>)}<button className="btn primary" disabled={busy||!!pending||review.duplicates.some(d=>d.matches.length&&!ack.includes(d.rowId))} onClick={()=>void run(async()=>{const result=await send<{batchId:string;imported:number;skipped:number}>(`/accounting/imports/${batch.id}/commit`,{revision:review.revision,reviewId:review.reviewId,reviewToken:review.reviewToken,approved:true,duplicateAcknowledgements:ack});await afterCommit(result);})}>确认保存本次决定</button></section>}</>}
 </section></Modal>;
}
