import {contractPost} from './api';
import {contractGet} from './api';
import {PetReminderProvider,HomeEventPrompts} from './PetReminderContext';
import ImportFile from './ImportFile';
import ProjectsPanel from './ProjectsPanel';
import CategoryTools from './CategoryTools';
import TodayTasks from './TodayTasks';
import WorkTasks from './WorkTasks';
import LibraryFiles from './LibraryFiles';
import {useState,useEffect,useRef,useCallback} from 'react';
import {Search,Plus,Inbox,Sparkles,FilePenLine,Wallet,Settings as SettingsIcon,ChevronDown,ArrowUpRight,Upload,Mic,Pin,Menu,X,LayoutGrid,List,ChevronRight,ArrowRight,Cloud,WifiOff,FolderOpen,Command,RefreshCw,CalendarClock} from 'lucide-react';
import {api,readableDate,fileUrl} from './api';
import {Logo,Toast,Empty,Spinner,ErrorBanner,TypeIcon,typeName} from './components';
import type {Bootstrap,Note,Page} from './types';
import NoteEditor from './NoteEditor';
import Assistant from './Assistant';
import Artifacts from './Artifacts';
import Memories from './Memories';
import Events from './Events';
import Settings from './Settings';
import Recorder from './Recorder';
import {applyTheme,readTheme,type ThemeId} from './theme';
import PetBuddy from './PetBuddy';
import {desktop} from './desktop';
import {DesktopNavigation} from './DesktopSurface';
import TodoPanel from './TodoPanel';
import ComputerFiles from './ComputerFiles';
import Accounting from './Accounting';

const nav=[{id:'library',label:'记录',Icon:Inbox},{id:'assistant',label:'搭子',Icon:Sparkles},{id:'workTasks',label:'任务',Icon:CalendarClock},{id:'events',label:'要事',Icon:CalendarClock},{id:'artifacts',label:'成果',Icon:FilePenLine}] as const;
function Login({demo,onLogin}:{demo:boolean;onLogin:()=>void}){const [code,setCode]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');async function enter(value=code){setBusy(true);setError('');try{await contractPost('postLogin','/login',{code:value});onLogin();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}return <main className="login-page"><div className="login-story"><div className="brand"><Logo/><span>拾光<small>SHIGUANG</small></span></div><div><span className="eyebrow">YOUR NOTES. YOUR MEMORY. YOUR WAY.</span><h1>让一闪而过的想法，<br/>有一个慢慢生长的地方。</h1><p>记下生活与工作的碎片。<br/>在需要的时候，找回属于自己的答案。</p></div><div className="login-cards"><div className="login-note"><span>今天的一点想法</span><p>好的工具，应该让我们<br/>更专注于自己的生活。</p><i># 灵感</i></div><div className="login-note back"><span>连接那些零散的时刻</span><p>记录 → 记忆 → 新的作品</p></div></div><small className="login-foot">从记录开始，与你一起思考。</small></div><div className="login-form-wrap"><form className="login-form" onSubmit={e=>{e.preventDefault();enter();}}><span className="eyebrow">WELCOME TO YOUR SPACE</span><h2>回到你的记忆空间</h2><p>手机与电脑，同一个拾光。</p><ErrorBanner message={error}/><label>访问口令<input type="password" autoComplete="current-password" autoFocus placeholder="输入你的空间口令" value={code} onChange={e=>setCode(e.target.value)}/></label><button className="btn primary full" disabled={busy||!code}>{busy?<Spinner label="正在进入…"/>:<>进入空间<ArrowRight size={17}/></>}</button>{demo&&<div className="demo-entry"><span>第一次来？先用示例资料体验</span><button type="button" className="btn secondary full" disabled={busy} onClick={()=>enter('shiguang-demo')}>进入演示空间<ArrowUpRight size={16}/></button><small>演示口令：shiguang-demo<br/>导入个人资料前，可在设置中更换口令。</small></div>}</form></div></main>;}
export default function App(){
 const [projectsOpen,setProjectsOpen]=useState(false);
 const [libraryFilesOpen,setLibraryFilesOpen]=useState(false);
 const [theme,setTheme]=useState<ThemeId>(readTheme);
 const [session,setSession]=useState<{authenticated:boolean;demoAccess:boolean}|null>(null),[data,setData]=useState<Bootstrap|null>(null),[page,setPage]=useState<Page>(()=>{const p=location.hash.slice(1);return ['workTasks','library','assistant','events','artifacts','memories','settings','accounting'].includes(p)?p as Page:'library';});
 const [error,setError]=useState(''),[online,setOnline]=useState(navigator.onLine),[toast,setToast]=useState(''),[menu,setMenu]=useState(false),[query,setQuery]=useState(''),[searchResults,setSearchResults]=useState<Note[]|null>(null),[searchBusy,setSearchBusy]=useState(false),[category,setCategory]=useState(''),[type,setType]=useState(''),[project,setProject]=useState(''),[tag,setTag]=useState(''),[layout,setLayout]=useState('grid'),[limit,setLimit]=useState(12),[editor,setEditor]=useState<Note|'new'|null>(null),[recording,setRecording]=useState(false),[computerFilesOpen,setComputerFilesOpen]=useState(false),[importingFile,setImportingFile]=useState<File|null>(null),[sort,setSort]=useState('newest');
 useEffect(()=>{applyTheme(theme);},[theme]);
 const input=useRef<HTMLInputElement>(null),searchInput=useRef<HTMLInputElement>(null),cursor=useRef(0),refreshPending=useRef<Promise<void>|null>(null),toastTimer=useRef<ReturnType<typeof setTimeout>|null>(null);
 const notify=useCallback((s:string)=>{setToast(s);if(toastTimer.current)clearTimeout(toastTimer.current);toastTimer.current=setTimeout(()=>setToast(''),4200);},[]);
 const refresh=useCallback(async()=>{if(refreshPending.current)return refreshPending.current;const promise=contractGet('getBootstrap','/bootstrap').then(s=>{setData(s);cursor.current=s.cursor;setError('');setOnline(true);}).catch(e=>{setError(e.message);throw e;}).finally(()=>{refreshPending.current=null;});refreshPending.current=promise;return promise;},[]);
 useEffect(()=>{contractGet('getSession','/session').then(setSession).catch(e=>setError(e.message));},[]);
 useEffect(()=>{if(session?.authenticated)void refresh().catch(()=>{});},[session?.authenticated,refresh]);
 useEffect(()=>{const expired=()=>{setSession(s=>s?{...s,authenticated:false}:s);setData(null);};const offline=()=>setOnline(false);const online=()=>{setOnline(true);if(session?.authenticated)void refresh().catch(()=>{});};const focus=()=>{if(session?.authenticated)void refresh().catch(()=>{});};window.addEventListener('session-expired',expired);window.addEventListener('offline',offline);window.addEventListener('online',online);window.addEventListener('focus',focus);return()=>{window.removeEventListener('session-expired',expired);window.removeEventListener('offline',offline);window.removeEventListener('online',online);window.removeEventListener('focus',focus);};},[session?.authenticated,refresh]);
 useEffect(()=>{if(!session?.authenticated)return;const timer=setInterval(()=>{if(document.visibilityState==='visible')void contractGet('getChanges','/changes?since='+cursor.current).then(s=>{setOnline(true);if(s.changed)return refresh();}).catch(()=>setOnline(false));},4000);return()=>clearInterval(timer);},[session?.authenticated,refresh]);
 useEffect(()=>{const change=()=>{const p=location.hash.slice(1);if(['workTasks','library','assistant','events','artifacts','memories','settings','accounting'].includes(p))setPage(p as Page);};window.addEventListener('hashchange',change);return()=>window.removeEventListener('hashchange',change);},[]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(document.querySelector('[role=dialog]'))return;if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setPage('library');location.hash='library';setTimeout(()=>searchInput.current?.focus(),50);}const target=e.target as HTMLElement;if(e.key.toLowerCase()==='n'&&!e.ctrlKey&&!e.metaKey&&!e.altKey&&!['INPUT','TEXTAREA','SELECT'].includes(target.tagName)&&!target.isContentEditable){e.preventDefault();setEditor('new');}if(e.key==='Escape')setMenu(false);};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[]);
 useEffect(()=>{if(!query.trim()){setSearchResults(null);setSearchBusy(false);return;}let alive=true;setSearchBusy(true);const timer=setTimeout(()=>{void contractGet('getSearch','/search?q='+encodeURIComponent(query)).then(r=>{if(alive)setSearchResults(r.notes);}).catch(e=>{if(alive)setError(e.message);}).finally(()=>{if(alive)setSearchBusy(false);});},200);return()=>{alive=false;clearTimeout(timer);};},[query,data?.cursor]);
 const navigate=(p:Page)=>{setPage(p);location.hash=p;setMenu(false);window.scrollTo({top:0});};
 const openNote=(n:Note)=>setEditor(n);
 async function finishImportedNote(imported:Note){let n=imported;await refresh().catch(()=>setError('原件已保存，但列表暂时未刷新；请稍后刷新页面。'));if(data?.settings.modelEnabled&&n.type!=='audio'&&(n.content.trim()||n.type==='image')){try{n=await api<Note>('/notes/'+n.id+'/summarize',{method:'POST'});notify('原件已保存，AI 归纳完成');await refresh().catch(()=>setError('AI 归纳已保存，但列表暂时未刷新；请稍后刷新页面。'));}catch(e){setError('原件已保存，但归纳失败：'+(e as Error).message);}}else notify(n.type==='audio'?'录音已保存；转写后才能归纳内容':'文件已保存');setEditor(n);}
 function importFile(file:File){setError('');if(file.size>25*1024*1024){setError('文件超过 25 MB，请压缩或拆分后导入。');return;}if(!/\.(txt|md|markdown|csv|json|pdf|docx|png|jpg|jpeg|webp|gif|mp3|wav|m4a|webm|ogg)$/i.test(file.name)){setError('暂不支持这个格式。可导入文字、文档、图片或音频。');return;}setImportingFile(file);if(input.current)input.current.value='';}
 if(!session)return <div className="app-loading"><Logo/><h2>拾光</h2>{error?<><ErrorBanner message={error}/><button className="btn secondary" onClick={()=>location.reload()}>重新连接</button></>:<Spinner label="打开你的记忆空间…"/>}</div>;
 if(!session.authenticated)return <Login demo={session.demoAccess} onLogin={()=>setSession({...session,authenticated:true})}/>;
 if(!data)return <div className="app-loading"><Logo/>{error?<><ErrorBanner message={error}/><button className="btn secondary" onClick={()=>void refresh().catch(()=>{})}>重新加载</button></>:<Spinner label="正在找回你的记录…"/>}</div>;
 const projects=[...new Set(data.notes.map(n=>n.project).filter(Boolean))];const tags=[...new Set(data.notes.flatMap(n=>n.tags))];let notes=(searchResults??data.notes).filter(n=>(!type||n.type===type)&&(!project||n.project===project)&&(!tag||n.tags.includes(tag))&&(!category||(category==='unclassified'?!n.categoryId:n.categoryId===category)));
 if(!query.trim())notes=[...notes].sort((a,b)=>Number(!!b.pinned)-Number(!!a.pinned)||(sort==='oldest'?a.createdAt.localeCompare(b.createdAt):b.createdAt.localeCompare(a.createdAt)));
 return <PetReminderProvider cursor={data.cursor}><div className="app-shell"><DesktopNavigation/><a className="skip-link" href="#main-content">跳转到主要内容</a>{menu&&<div className="sidebar-scrim" onClick={()=>setMenu(false)}/>}<aside className={'sidebar '+(menu?'open':'')}><button className="brand brand-button" onClick={()=>{navigate('library');setProject('');setTag('');}}><Logo/><span>拾光<small>SHIGUANG</small></span></button><button className="workspace-switch" onClick={()=>navigate('settings')}><span className="workspace-avatar">我</span><span>{data.settings.name}<small>个人记忆空间</small></span><ChevronDown size={15}/></button><button className="btn primary new-note" onClick={()=>{setEditor('new');setMenu(false);}}><Plus size={18}/>记一条<span>N</span></button><div className="nav-caption">我的空间</div><nav aria-label="主导航">{nav.map(({id,label,Icon})=><button key={id} className={'nav-item '+(page===id?'active':'')} onClick={()=>navigate(id)} aria-current={page===id?'page':undefined}><Icon size={19} strokeWidth={1.7}/><span>{label}</span>{id==='library'?<small>{data.notes.length}</small>:null}</button>)}</nav><button className="nav-item" onClick={()=>{setProjectsOpen(true);setMenu(false);}}><FolderOpen size={19}/><span>项目资料</span></button><div className="nav-caption project-caption">旧项目标签<span>{projects.length}</span></div><div className="project-nav">{projects.map((p,i)=><button key={p} className={project===p&&page==='library'?'selected':''} onClick={()=>{navigate('library');setProject(project===p?'':p);setTag('');}}><i style={{background:['#c18763','#79957b','#9990ae','#698e9f'][i%4]}}/><span>{p}</span><small>{data.notes.filter(n=>n.project===p).length}</small></button>)}</div><div className="sidebar-bottom"><div className="growth-note"><span className="tiny-flower">✳</span><p>每一次记录，<br/>都是对自己的积累。</p><small>{data.notes.length} 条记录，慢慢生长中</small></div><button className={'nav-item '+(page==='accounting'?'active':'')} onClick={()=>navigate('accounting')}><Wallet size={18}/><span>记账</span></button><button className={'nav-item '+(page==='settings'?'active':'')} onClick={()=>navigate('settings')}><SettingsIcon size={18}/><span>设置与数据</span></button><div className="sidebar-user"><span className="user-avatar">我</span><span>拾光同行者<small>把日子，过成自己的样子</small></span></div></div></aside>
 <div className="workspace"><header className="topbar"><div className="breadcrumb"><button className="icon-btn mobile-menu" aria-label="打开导航" onClick={()=>setMenu(true)}><Menu size={21}/></button><span>我的空间</span><ChevronRight size={13}/><strong>{page==='accounting'?'记账':page==='memories'?'记忆与偏好':nav.find(n=>n.id===page)?.label||'设置与数据'}</strong></div><div className="topbar-right"><span className={'sync-status '+(!online?'offline':'')}>{online?<Cloud size={15}/>:<WifiOff size={15}/>}<span>{online?'已连接空间':'等待重新连接'}</span></span><span className="topbar-divider"/><button className="icon-btn" onClick={()=>navigate('settings')} aria-label="空间设置"><span className="user-avatar small">我</span></button></div></header>
 <main id="main-content" className={'main-content '+(page==='library'?'library-page':'')}><ErrorBanner message={error}/>{page==='library'?<><section className="library-heading"><div><span className="eyebrow">A PLACE FOR EVERY LITTLE THOUGHT</span><h1>把此刻，留给未来的自己<span className="heading-dot">。</span></h1><p>收集零散的想法，让每一次记录都有回响。</p></div><div className="date-stamp"><span>{new Date().toLocaleDateString('en-US',{month:'short'}).toUpperCase()}</span><strong>{String(new Date().getDate()).padStart(2,'0')}</strong><small>{new Date().toLocaleDateString('zh-CN',{weekday:'long'})}</small></div></section>
 <div className="library-capture-grid"><section className="capture-box"><button className="capture-prompt" onClick={()=>setEditor('new')}><span className="capture-avatar"><Plus size={21}/></span><span>此刻，有什么想记下来？<small>一个想法、一段见闻，或今天的小小进展</small></span><span className="capture-hint">开始记录<ArrowUpRight size={16}/></span></button><div className="capture-bottom"><div><button onClick={()=>setRecording(true)}><Mic size={16}/>语音记录</button><button onClick={()=>input.current?.click()} disabled={!!importingFile}><Upload size={16}/>导入文件</button><button onClick={()=>setLibraryFilesOpen(true)}>资料库</button><button onClick={()=>setComputerFilesOpen(true)}><FolderOpen size={16}/>电脑文件</button></div><span>先记下来，慢慢整理</span></div></section><TodoPanel todos={data.todos} onRefresh={refresh} onToast={notify}/></div>
 <TodayTasks/><HomeEventPrompts/>
 <CategoryTools notes={data.notes} filter={category} onFilter={id=>{setCategory(id);setLimit(12);}} onRefresh={refresh}/><section className="library-toolbar"><div className="search-field"><Search size={17}/><input ref={searchInput} aria-label="搜索记录" placeholder="搜索你的记录、标签或想法…" value={query} onChange={e=>{setQuery(e.target.value);setLimit(12);}}/>{query?<button className="icon-btn" aria-label="清空搜索" onClick={()=>setQuery('')}><X size={15}/></button>:<kbd><Command size={11}/> K</kbd>}</div><div className="library-controls"><div className="filter-tabs" role="group" aria-label="记录类型">{[['','全部记录'],['text','文字'],['document','文档'],['image','图片'],['audio','音频']].map(([v,l])=><button key={v} className={type===v?'selected':''} onClick={()=>{setType(v);setLimit(12);}}>{l}{!v&&<span>{data.notes.length}</span>}</button>)}</div><div className="view-controls"><label className="sort-control"><select aria-label="记录排序" value={sort} onChange={e=>setSort(e.target.value)}><option value="newest">最新记录</option><option value="oldest">最早记录</option></select></label><div className="layout-toggle"><button aria-label="卡片视图" className={layout==='grid'?'selected':''} onClick={()=>setLayout('grid')}><LayoutGrid size={16}/></button><button aria-label="列表视图" className={layout==='list'?'selected':''} onClick={()=>setLayout('list')}><List size={17}/></button></div></div></div><select className="tag-filter" aria-label="筛选标签" value={tag} onChange={e=>setTag(e.target.value)}><option value="">所有标签</option>{tags.map(t=><option key={t}>{t}</option>)}</select></section>
 {(project||tag||query||category)&&<div className="active-filters"><span>找到 {notes.length} 条记录</span>{project&&<button onClick={()=>setProject('')}><FolderOpen size={12}/>{project}<X size={12}/></button>}{tag&&<button onClick={()=>setTag('')}>#{tag}<X size={12}/></button>}<button className="clear-filters" onClick={()=>{setProject('');setTag('');setQuery('');setType('');setCategory('');}}>清除筛选</button></div>}
 {searchBusy?<div className="search-loading"><Spinner label="正在寻找相关记录…"/></div>:!notes.length?<Empty title={query||type||tag||project||category?'这里暂时没有匹配的记录':'从第一条记录开始'} description={query?'换个关键词试试，也可以清除筛选查看全部资料。':'写一点想法，或导入一份资料，让这个空间慢慢丰富起来。'} action={<button className="btn secondary" onClick={()=>setEditor('new')}><Plus size={16}/>写一条记录</button>}/>:<div className={'notes-grid '+(layout==='list'?'list-view':'')}>{notes.slice(0,limit).map((n,i)=><article className={'note-card '+(n.pinned?'pinned ':'')+n.type} key={n.id} style={{animationDelay:`${Math.min(i,8)*35}ms`}}><button className="note-card-body" onClick={()=>openNote(n)}><div className="note-card-meta"><span><TypeIcon type={n.type}/>{typeName(n.type)}</span><div>{n.sample&&<span className="sample-badge">示例</span>}{n.pinned&&<Pin size={13}/>}</div></div>{n.attachments.find(a=>a.mime.startsWith('image/'))&&<img className="card-image" src={fileUrl(n.id,n.attachments.find(a=>a.mime.startsWith('image/'))!.id)} alt="" loading="lazy"/>}<h2>{n.title}</h2><p>{n.content||n.notice||n.summary}</p></button><div className="note-card-tags">{n.tags.slice(0,3).map(t=><button key={t} onClick={()=>setTag(t)}>#{t}</button>)}</div><footer><span>{readableDate(n.createdAt)}</span>{n.project&&<button onClick={()=>setProject(n.project)}><i/>{n.project}</button>}<button className="note-open" aria-label={'打开记录：'+n.title} onClick={()=>openNote(n)}><ArrowUpRight size={15}/></button></footer></article>)}</div>}
 {notes.length>limit&&<div className="load-more"><button className="btn secondary" onClick={()=>setLimit(l=>l+12)}>再看看更多记录<ChevronDown size={16}/></button></div>}<div className="library-footer"><span/><p>每一份微小的记录，都在成为你的一部分。</p><span/></div></>:page==='assistant'?<Assistant onOpenLibrary={()=>setLibraryFilesOpen(true)} data={data} onRefresh={refresh} onOpen={openNote} onOpenEvent={event=>{navigate('events');setTimeout(()=>document.getElementById('event-'+event.id)?.scrollIntoView({behavior:'smooth',block:'center'}),50);}} onToast={notify}/>:page==='workTasks'?<WorkTasks/>:page==='events'?<Events data={data} onRefresh={refresh} onOpenNote={openNote} onToast={notify}/>:page==='artifacts'?<Artifacts data={data} onRefresh={refresh} onOpen={openNote} onToast={notify}/>:page==='memories'?<Memories data={data} onRefresh={refresh} onOpen={openNote} onToast={notify}/>:page==='accounting'?<Accounting transactions={data.transactions} budget={data.accountingBudget} modelEnabled={data.settings.modelEnabled} onRefresh={refresh} onToast={notify}/>:<Settings onRefresh={refresh} onToast={notify} onLogout={()=>setSession({...session,authenticated:false})} theme={theme} onThemeChange={setTheme}/>}</main></div>
 <input ref={input} type="file" className="hidden" accept=".txt,.md,.markdown,.csv,.json,.pdf,.docx,.png,.jpg,.jpeg,.webp,.gif,.mp3,.wav,.m4a,.webm,.ogg" onChange={e=>{const file=e.target.files?.[0];if(file)void importFile(file);}} aria-label="选择导入文件"/>
 <nav className="mobile-bottom-nav" aria-label="手机导航">{nav.map(({id,label,Icon})=><button key={id} className={page===id?'active':''} onClick={()=>navigate(id)}><Icon size={20}/><span>{label}</span></button>)}</nav>
 {editor!==null&&<NoteEditor key={editor==='new'?'new':editor.id} note={editor==='new'?null:editor} projects={projects} onClose={()=>setEditor(null)} onSaved={()=>void refresh().catch(()=>{})} onDeleted={()=>{setEditor(null);void refresh().catch(()=>{});}} onToast={notify}/>}{recording&&<Recorder onClose={()=>setRecording(false)} onSaved={n=>{setRecording(false);setEditor(n);void refresh().catch(()=>{});notify('录音已保存');}}/>}{importingFile&&<ImportFile file={importingFile} onClose={()=>setImportingFile(null)} onImported={finishImportedNote}/>} {projectsOpen&&<ProjectsPanel onClose={()=>setProjectsOpen(false)} onNote={note=>{setProjectsOpen(false);setEditor(note);}}/>} {libraryFilesOpen&&<LibraryFiles onClose={()=>setLibraryFilesOpen(false)}/>} {computerFilesOpen&&<ComputerFiles onClose={()=>setComputerFilesOpen(false)} onImported={finishImportedNote}/>}{!desktop&&<PetBuddy/>}<Toast message={toast}/>{!online&&<button className="reconnect-button" onClick={()=>void refresh().catch(()=>{})}><RefreshCw size={15}/>重试连接</button>}</div></PetReminderProvider>;
}
