import {useState} from 'react';
import {FilePenLine,ArrowUpRight,Plus,Download,Pencil,Save,Trash2,BookOpen,CalendarDays,Sparkles} from 'lucide-react';
import {api,post,patch,del,readableDate,downloadText,ApiError} from './api';
import {Modal,Markdown,Sources,Spinner,ErrorBanner,Empty} from './components';
import type {Bootstrap,Artifact,Note} from './types';

const modeLabel=(a:Artifact)=>a.mode==='human'?'人工编辑':a.mode==='model'?'AI 草稿':'本地原文整理';
export default function Artifacts({data,onRefresh,onOpen,onToast}:{data:Bootstrap;onRefresh:()=>Promise<void>;onOpen:(n:Note)=>void;onToast:(s:string)=>void}){
 const [create,setCreate]=useState(false),[template,setTemplate]=useState('weekly'),[project,setProject]=useState(''),[days,setDays]=useState(7),[instructions,setInstructions]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');const [active,setActive]=useState<Artifact|null>(null),[editing,setEditing]=useState(false),[body,setBody]=useState(''),[title,setTitle]=useState('');const [conflict,setConflict]=useState<Artifact|null>(null);
 const projects=[...new Set(data.notes.map(n=>n.project).filter(Boolean))];
 async function generate(){setBusy(true);setError('');try{const result=await post<Artifact>('/tasks',{template,project,days,instructions});setCreate(false);setActive(result);setEditing(false);await onRefresh();onToast('草稿已生成，可以继续修改和导出');}catch(e){setError((e as Error).message);await onRefresh();}finally{setBusy(false);}}
 async function save(){if(!active)return;setBusy(true);setError('');try{const result=await patch<Artifact>('/artifacts/'+active.id,{revision:active.revision,title,body});setActive(result);setEditing(false);await onRefresh();onToast('已保存成果');}catch(e){setError((e as Error).message);if(e instanceof ApiError&&e.status===409)setConflict(e.current as Artifact);}finally{setBusy(false);}}
 async function exportSaved(){if(!active||busy)return;setBusy(true);setError('');try{const saved=await api<Artifact>('/artifacts/'+active.id+'?revision='+active.revision);downloadText(saved.body,saved.title+'.md');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function remove(){if(!active||!window.confirm('确定删除这份成果吗？原始记录不会被删除。'))return;try{await del('/artifacts/'+active.id,active.revision);setActive(null);await onRefresh();onToast('已删除成果');}catch(e){setError((e as Error).message);}}
 const open=(a:Artifact)=>{setActive(a);setEditing(false);setError('');setConflict(null);};
 return <><div className="page-heading"><div><span className="eyebrow">FROM NOTES TO SOMETHING NEW</span><h1>让记录，成为作品</h1><p>从自己的积累出发，完成下一份周报、文章或总结。</p></div><button className="btn primary" onClick={()=>{setCreate(true);setError('');}}><Plus size={17}/>新建成果</button></div>
 <div className="template-grid"><button className="template-card weekly" onClick={()=>{setTemplate('weekly');setCreate(true);setError('');}}><span className="template-icon"><CalendarDays size={25}/></span><div><h3>一周工作回顾</h3><p>串起进展、收获与下一步</p></div><ArrowUpRight size={20}/></button><button className="template-card article" onClick={()=>{setTemplate('article');setCreate(true);setError('');}}><span className="template-icon"><FilePenLine size={25}/></span><div><h3>把想法写成文章</h3><p>让零散记录围绕一个主题生长</p></div><ArrowUpRight size={20}/></button></div>
 <div className="section-heading spacious"><h2>我的成果</h2><span>{data.artifacts.length} 份</span></div>{!data.artifacts.length?<Empty title="你的第一份作品，从这里开始" description="选择上方的模板，把已有记录整理成一份有出处的草稿。" icon={<FilePenLine size={32} strokeWidth={1.3}/>}/>:<div className="artifact-grid">{data.artifacts.map(a=><button className="artifact-card" key={a.id} onClick={()=>open(a)}><div className="artifact-preview"><div className="paper"><span/><b>{a.title}</b><i/><i/><i/><i/><i/><i/></div><span className="artifact-label">{a.template==='weekly'?'工作周报':'主题整理'}</span></div><div className="artifact-info"><h3>{a.title}</h3><p>{readableDate(a.createdAt)}<span>·</span>{a.sources.length} 条来源<span>·</span>{modeLabel(a)}</p></div></button>)}</div>}
 {data.tasks.filter(t=>t.status==='running').map(t=><div className="subtle-notice" key={t.id}><Spinner label={t.title+'，正在后台处理…'}/></div>)}
 {data.tasks.some(t=>t.status==='failed')&&<details className="task-history"><summary>查看未完成的任务</summary>{data.tasks.filter(t=>t.status==='failed').slice(0,5).map(t=><p key={t.id}>{t.title}：{t.error}</p>)}</details>}
 {create&&<Modal closeDisabled={busy} title="让记录变成一份新成果" onClose={()=>{if(!busy)setCreate(false);}}><form className="form-body" onSubmit={e=>{e.preventDefault();generate();}}><ErrorBanner message={error}/><div className="segmented"><button type="button" className={template==='weekly'?'selected':''} onClick={()=>setTemplate('weekly')}><CalendarDays size={17}/>工作周报</button><button type="button" className={template==='article'?'selected':''} onClick={()=>setTemplate('article')}><FilePenLine size={17}/>主题整理</button></div><div className="form-row"><label>资料范围<select value={project} onChange={e=>setProject(e.target.value)}><option value="">全部项目</option>{projects.map(p=><option key={p}>{p}</option>)}</select></label><label>记录时间<select value={days} onChange={e=>setDays(Number(e.target.value))}><option value={7}>最近 7 天</option><option value={30}>最近 30 天</option><option value={3650}>全部时间</option></select></label></div><label>有什么特别的要求？<textarea placeholder="比如：突出本周进展，保留风险和待办，语气简洁一些。" value={instructions} onChange={e=>setInstructions(e.target.value)} maxLength={1000} rows={4}/></label><div className="subtle-notice"><BookOpen size={17}/>{data.settings.modelEnabled?'将读取所选范围内的资料和已确认偏好，由 AI 生成带引用的草稿。':'当前使用本地整理模式：汇集原文与来源，不会虚构生成内容。连接模型后可进行 AI 写作。'}</div><button className="btn primary full" disabled={busy}>{busy?<Spinner label="正在整理资料，请稍候…"/>:<><Sparkles size={17}/>开始整理</>}</button></form></Modal>}
 {active&&<Modal closeDisabled={busy} title="成果工作台" wide onClose={()=>{if(busy)return;if(editing&&(body!==active.body||title!==active.title)&&!window.confirm('修改尚未保存，确定离开吗？'))return;setActive(null);}}><div className="artifact-detail"><ErrorBanner message={error}/><div className="artifact-toolbar"><span className="type-label"><FilePenLine size={15}/>{modeLabel(active)}</span><div><button className="btn text" disabled={busy||editing} onClick={()=>void exportSaved()}><Download size={15}/>导出</button>{editing?<button className="btn primary" disabled={busy} onClick={save}><Save size={15}/>保存</button>:<button className="btn secondary" onClick={()=>{setEditing(true);setTitle(active.title);setBody(active.body);}}><Pencil size={15}/>编辑</button>}<button className="icon-btn danger" aria-label="删除成果" onClick={remove}><Trash2 size={17}/></button></div></div>
 {editing&&<p className="field-help">请先保存修改，再导出保存版本。</p>}{active.mode==='human'&&<p className="field-help">当前为人工编辑版本，最初来源：{active.originMode==='model'?'AI 草稿':'本地原文整理'}。</p>}{active.qualityNotice&&<div className="subtle-notice">{active.qualityNotice}</div>}{editing?<><input className="editor-title" aria-label="成果标题" value={title} onChange={e=>setTitle(e.target.value)}/><textarea className="artifact-editor" aria-label="成果正文" value={body} onChange={e=>setBody(e.target.value)}/>{conflict&&<div className="conflict-box"><p>另一设备保存了新版本。请先复制保留你的内容，再合并。</p><button className="btn secondary" onClick={()=>{setActive(conflict);setConflict(null);setError('已更新版本基线，请核对你的内容后再次保存。');}}>基于最新版本继续保存</button></div>}</>:<Markdown>{active.body}</Markdown>}{active.memories&&active.memories.length>0&&<details className="phase-card"><summary>生成时采用的记忆（{active.memories.length} 条）</summary><p className="field-help">以下保留生成时的内容；之后修改记忆不会改写这份成果。</p>{active.memories.map(memory=><article key={memory.id}><p className="preserve-text">{memory.content}</p><small>{memory.scope||'通用'}{memory.revision!==undefined?' · 版本 '+memory.revision:''}</small></article>)}</details>}<div className="answer-sources"><h3>这份成果的来源</h3><Sources sources={active.sources} notes={data.notes} onOpen={onOpen}/></div></div></Modal>}
 </>;
}
