import {randomId} from './randomId';
import {useEffect,useRef,useState} from 'react';
import {api,post,patch} from './api';
import {Modal,ErrorBanner} from './components';
import type {Note} from './types';
export type NoteCategory={id:string;revision:number;name:string;kind:string;projectId?:string};
type Project={id:string;name:string};
export default function CategoryTools({notes,filter,onFilter,onRefresh}:{notes:Note[];filter:string;onFilter:(id:string)=>void;onRefresh:()=>Promise<void>}){
 const [items,setItems]=useState<NoteCategory[]>([]),[error,setError]=useState(''),[open,setOpen]=useState(false),[projects,setProjects]=useState<Project[]>([]),[categoryId,setCategoryId]=useState(''),[selected,setSelected]=useState<{id:string;revision:number;title:string}[]>([]),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[name,setName]=useState(''),[projectId,setProjectId]=useState(''),[projectName,setProjectName]=useState(''),[rename,setRename]=useState(''),[message,setMessage]=useState('');
 const operation=useRef(randomId()),projectOperation=useRef(randomId());
 async function load(){try{const [categories,projects]=await Promise.all([api<{items:NoteCategory[]}>('/categories'),api<{items:Project[]}>('/projects')]);setItems(categories.items);setProjects(projects.items);setError('');}catch(e){setError((e as Error).message);}}
 useEffect(()=>{void load();},[]);
 function change(){operation.current=randomId();setMessage('');}
 async function assign(){setBusy(true);setError('');try{await post('/notes/categories',{opId:operation.current,categoryId,notes:selected.map(({id,revision})=>({id,revision})),reason});setSelected([]);change();setMessage('分类已保存，纠错记录已登记。');await onRefresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function create(){setBusy(true);setError('');try{let parent=projectId;if(parent==='new'){const created=await post<Project>('/projects',{name:projectName,opId:projectOperation.current});parent=created.id;setProjectId(parent);setProjects(old=>[...old.filter(p=>p.id!==parent),created]);}const category=await post<NoteCategory>('/categories',{name,projectId:parent});setCategoryId(category.id);change();setName('');await load();setMessage('项目类别已创建。记录与项目的关联仍需明确选择。');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function renameCategory(){const category=items.find(c=>c.id===categoryId);if(!category)return;setBusy(true);setError('');try{await patch('/categories/'+category.id,{name:rename,revision:category.revision});setRename('');await load();setMessage('类别已改名，记录关联保持不变。');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const choices=<><option value="">请选择类别</option>{categoryId&&!items.some(c=>c.id===categoryId)&&<option value={categoryId}>所选类别暂不可用，请重新选择</option>}{items.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</>;
 return <section className="category-tools" aria-label="记录分类"><label>记录类别<select aria-label="筛选记录类别" value={filter} onChange={e=>onFilter(e.target.value)}><option value="">全部类别</option><option value="unclassified">待分类</option>{items.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><button className="btn secondary" onClick={()=>{setOpen(true);void load();}}>整理记录分类</button>{!open&&error&&<><ErrorBanner message={error}/><button className="btn secondary" onClick={()=>void load()}>重试加载类别</button></>}
 {open&&<Modal title="整理记录分类" wide closeDisabled={busy} onClose={()=>{if(!busy)setOpen(false);}}><ErrorBanner message={error}/>{message&&<p role="status">{message}</p>}<p>每条记录归入一个类别。人工调整会登记纠错反馈，不会改变正文、附件或聊天。</p><fieldset className="category-edit-fields" disabled={busy}>
 <label>目标类别<select aria-label="目标类别" value={categoryId} onChange={e=>{setCategoryId(e.target.value);change();}}>{choices}</select></label>
 <fieldset className="category-note-list"><legend>选择记录（最多100条）</legend>{notes.map(note=><label key={note.id}><input type="checkbox" checked={selected.some(s=>s.id===note.id)} disabled={busy||(!selected.some(s=>s.id===note.id)&&selected.length>=100)} onChange={e=>{setSelected(old=>e.target.checked?[...old,{id:note.id,revision:note.revision,title:note.title}]:old.filter(s=>s.id!==note.id));change();}}/><span>{note.title}<small> · {items.find(c=>c.id===note.categoryId)?.name||(note.categoryId?'原类别已失效':'待分类')}</small></span></label>)}</fieldset>
 {selected.some(s=>!notes.some(n=>n.id===s.id))&&<div>{selected.filter(s=>!notes.some(n=>n.id===s.id)).map(s=><p key={s.id}>{s.title}（已不在当前列表）<button className="btn text" onClick={()=>{setSelected(old=>old.filter(n=>n.id!==s.id));change();}}>移除</button></p>)}</div>}
 <label>调整原因（可选）<input value={reason} maxLength={500} onChange={e=>{setReason(e.target.value);change();}}/></label><button className="btn primary" disabled={busy||!selected.length||!categoryId} onClick={()=>void assign()}>保存所选记录分类（{selected.length}）</button>
 <details><summary>新建开发项目类别</summary><label>类别名称<input value={name} maxLength={80} onChange={e=>setName(e.target.value)}/></label><label>关联项目<select aria-label="关联项目" value={projectId} onChange={e=>setProjectId(e.target.value)}><option value="">请选择项目</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name} · {p.id.slice(0,8)}</option>)}<option value="new">新建独立项目</option></select></label>{projectId==='new'&&<label>新项目名称<input value={projectName} maxLength={80} onChange={e=>{setProjectName(e.target.value);projectOperation.current=randomId();}}/></label>}<button className="btn secondary" disabled={busy||!name.trim()||!projectId||(projectId==='new'&&!projectName.trim())} onClick={()=>void create()}>创建项目类别</button></details>
 {items.find(c=>c.id===categoryId)?.kind==='development_project'&&<details><summary>修改所选类别名称</summary><label>新类别名称<input value={rename} maxLength={80} onChange={e=>setRename(e.target.value)}/></label><button className="btn secondary" disabled={busy||!rename.trim()} onClick={()=>void renameCategory()}>保存类别名称</button></details>}
 </fieldset></Modal>}
 </section>;
}
