import {contractPatch} from './api';
import {contractGet} from './api';
import type {components} from '../contracts/generated/types';
import {useEffect,useState} from 'react';

import {ErrorBanner,Spinner} from './components';
type Correction = components['schemas']['ClassificationCorrection'];
function CorrectionItem({item,onSaved}:{item:Correction;onSaved:()=>void}){
 const [resolution,setResolution]=useState(item.resolution||''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function save(){setBusy(true);setError('');try{await contractPatch('patchClassificationCorrectionsById','/classification-corrections/'+item.id,{revision:item.revision,status:item.status==='open'?'resolved':'open',resolution});onSaved();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <article className="correction-item" aria-label={'分类纠错：'+item.sourceTitle}><h3>{item.sourceTitle}</h3><p>{item.oldCategoryName||'待分类'} → {item.newCategoryName} · {item.status==='open'?'待处理':'已处理'}</p>{item.reason&&<p>调整原因：{item.reason}</p>}<p className="field-help">来源版本 {item.sourceRevision} · 分类器版本 {item.classifierRevision} · {item.model||'未经过模型分类'}{item.promptVersion&&` · ${item.promptVersion}`}</p><ErrorBanner message={error}/><label>处理说明<textarea value={resolution} maxLength={1000} disabled={busy} onChange={e=>setResolution(e.target.value)}/></label><button className="btn secondary" disabled={busy} onClick={()=>void save()}>{busy?'保存中…':item.status==='open'?'标为已处理':'重新打开问题'}</button>{!!item.history?.length&&<details><summary>处理历史（{item.history.length}）</summary><ol>{item.history.map((entry,index)=><li key={index}>{new Date(entry.at).toLocaleString()} · {entry.status==='resolved'?'已处理':'重新打开'}<p>{entry.resolution||'未填写说明'}</p></li>)}</ol></details>}</article>;
}
export default function ClassificationCorrections(){
 const [status,setStatus]=useState('open'),[offset,setOffset]=useState(0),[version,setVersion]=useState(0),[data,setData]=useState<{items:Correction[];total:number}|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState('');
 useEffect(()=>{let active=true;setLoading(true);setError('');void contractGet('getClassificationCorrections',`/classification-corrections?offset=${offset}&limit=20${status?'&status='+status:''}`).then(result=>{if(active){if(offset>0&&!result.items.length){setOffset(Math.max(0,offset-20));return;}setData(result);}}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[status,offset,version]);
 return <section className="settings-panel" aria-label="分类纠错问题表"><h2>分类纠错问题表</h2><p>人工调整分类时会自动登记。处理状态用于记录排查进度，不会自动训练模型或修改程序。</p><label>问题状态<select aria-label="问题状态" value={status} onChange={e=>{setStatus(e.target.value);setOffset(0);setMessage('');}}><option value="open">待处理</option><option value="resolved">已处理</option><option value="">全部</option></select></label>{message&&<p role="status">{message}</p>}<ErrorBanner message={error}/>{error&&<button className="btn secondary" onClick={()=>setVersion(v=>v+1)}>重试加载问题表</button>}{loading?<Spinner label="读取分类纠错记录…"/>:!error&&data&&<>{!data.items.length?<p>当前没有此状态的分类纠错记录。</p>:data.items.map(item=><CorrectionItem key={item.id} item={item} onSaved={()=>{setVersion(v=>v+1);setMessage('处理状态已保存，历史记录仍保留。');}}/>)}<div className="transcript-controls"><span>共 {data.total} 条</span><button className="btn secondary" disabled={offset===0} onClick={()=>setOffset(v=>Math.max(0,v-20))}>上一页</button><button className="btn secondary" disabled={offset+20>=data.total} onClick={()=>setOffset(v=>v+20)}>下一页</button></div></>}</section>;
}
