import {API_BASE} from './api';
import {openPetSource} from './PetReminderTable';
import {useEffect,useRef} from 'react';
import type {ReactNode} from 'react';
import {X,ArrowUpRight,FileText,Mic,Image as ImageIcon,StickyNote,LoaderCircle,Check,AlertCircle,Sun} from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import type {EventRecord,Note,Source} from './types';

export const Logo=({small=false}:{small?:boolean})=><span className={`brand-mark ${small?'small':''}`}><Sun size={small?20:27} strokeWidth={1.6}/></span>;
export function Spinner({label='处理中…'}:{label?:string}){return <span className="spinner" role="status"><LoaderCircle className="spin" size={17}/>{label}</span>;}
export function TypeIcon({type,size=16}:{type:string;size?:number}){const Icon=type==='audio'?Mic:type==='image'?ImageIcon:type==='document'?FileText:StickyNote;return <Icon size={size} strokeWidth={1.6}/>;}
export const typeName=(type:string)=>({text:'文字记录',document:'文档资料',image:'图片',audio:'音频'}[type]||'记录');
export function Modal({title,children,onClose,wide=false,closeDisabled=false}:{title:string;children:ReactNode;onClose:()=>void;wide?:boolean;closeDisabled?:boolean}){
 const ref=useRef<HTMLDivElement>(null);const close=useRef(onClose);close.current=onClose;
 useEffect(()=>{const previous=document.activeElement as HTMLElement;const old=document.body.style.overflow;document.body.style.overflow='hidden';const timer=setTimeout(()=>{
  const dialog=ref.current,dialogs=document.querySelectorAll('[role=dialog]');
  // Do not steal an input focus already chosen by the user or a newer dialog.
  if(!dialog||dialog!==dialogs[dialogs.length-1]||dialog.contains(document.activeElement))return;
  (dialog.querySelector<HTMLElement>('[autofocus], textarea:not(:disabled), input:not(:disabled)')||dialog.querySelector<HTMLElement>('button:not(:disabled)'))?.focus();
 },30);
 const key=(e:KeyboardEvent)=>{const dialogs=document.querySelectorAll('[role=dialog]');if(ref.current!==dialogs[dialogs.length-1])return;if(e.key==='Escape'){e.preventDefault();close.current();}if(e.key==='Tab'){const els=Array.from(ref.current?.querySelectorAll<HTMLElement>('button:not(:disabled), input:not(:disabled), textarea:not(:disabled), select:not(:disabled), a[href], [tabindex="0"]')||[]).filter(el=>el.offsetParent!==null);const first=els[0],last=els[els.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}};document.addEventListener('keydown',key);return()=>{clearTimeout(timer);document.body.style.overflow=old;document.removeEventListener('keydown',key);previous?.focus();};},[]);
 return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose();}}><div ref={ref} className={`modal ${wide?'wide':''}`} role="dialog" aria-modal="true" aria-label={title}><header className="modal-header"><h2>{title}</h2><button className="icon-btn" onClick={onClose} disabled={closeDisabled} aria-label="关闭窗口"><X size={20}/></button></header>{children}</div></div>;
}
export function Empty({title,description,action,icon}:{title:string;description:string;action?:ReactNode;icon?:ReactNode}){return <div className="empty"><div className="empty-icon">{icon||<Sun size={30} strokeWidth={1.3}/>}</div><h3>{title}</h3><p>{description}</p>{action}</div>;}
export function ErrorBanner({message}:{message:string}){return message?<div className="error-banner" role="alert"><AlertCircle size={17}/><span>{message}</span></div>:null;}
export function Markdown({children,showImages=false}:{children:string;showImages?:boolean}){return <div className="markdown"><ReactMarkdown remarkPlugins={[remarkGfm]} components={{a:({href,children})=><a href={href} target="_blank" rel="noopener noreferrer">{children}</a>,img:({src,alt})=>showImages?<img src={src} alt={alt||''} loading="lazy"/>:<a href={typeof src==='string'?src:undefined} target="_blank" rel="noopener noreferrer">查看图片：{alt||'外部图片'}</a>}}>{children}</ReactMarkdown></div>;}
export function Sources({sources,notes,events=[],onOpen,onOpenEvent}:{sources:Source[];notes:Note[];events?:EventRecord[];onOpen:(n:Note)=>void;onOpenEvent?:(event:EventRecord)=>void}){return <div className="source-list">{sources.map((s,i)=>{if(s.kind==='researchExternal')return <button key={`${s.id}-${i}`} className="source-item" disabled={!s.taskId} onClick={()=>s.taskId&&openPetSource({sourceKind:'workTask',sourceId:s.taskId,actionTarget:{page:'workTasks',id:s.taskId}})}><span className="source-number">{i+1}</span><span><strong>{s.title}</strong><small>用户回填 · 未独立核验 · {s.quote.slice(0,72)}</small></span></button>;if(s.kind==='libraryFile')return <a key={`${s.id}-${i}`} className="source-item" href={(API_BASE + "/library/")+s.id+'/file'}><span className="source-number">{i+1}</span><span><strong>{s.title}</strong><small>资料副本 · {s.quote.slice(0,72)}</small></span></a>;if(s.kind==='web')return <a key={`${s.id}-${i}`} className="source-item" href={s.url} target="_blank" rel="noopener noreferrer"><span className="source-number">{i+1}</span><span><strong>{s.title}</strong><small>网页摘要 · {s.quote.slice(0,72)}</small></span><ArrowUpRight size={16}/></a>;const event=s.kind==='event'?events.find(item=>item.id===s.id):undefined;const note=s.kind!=='event'&&s.kind!=='memory'?notes.find(item=>item.id===s.id):undefined;const memory=s.kind==='memory';const available=!!note||!!event||memory;return <button key={`${s.id}-${i}`} className={`source-item ${!available?'unavailable':''}`} disabled={!note&&!event} onClick={()=>{if(note)onOpen(note);else if(event)onOpenEvent?.(event);}}><span className="source-number">{i+1}</span><span><strong>{s.title}</strong><small>{memory?'已确认长期记忆 · '+(s.scopeKind==='project'?'项目 '+(s.scopeId||'').slice(0,8):s.scopeKind==='thread'?'当前话题':'全局')+' · '+(s.purpose||'通用')+' · '+s.quote.slice(0,72):!available?'来源已删除':event?'要事 · '+(event.revision!==s.revision?'内容已更新，请核对当前版本':s.quote.slice(0,72)):note?.revision!==s.revision?'来源已更新，请核对当前版本':s.quote.slice(0,72)}</small></span>{(note||event)&&<ArrowUpRight size={16}/>}</button>;})}{sources.filter(s=>s.excerpts?.length).map((s,i)=><details className="phase-card" key={'excerpt-'+s.id+'-'+i}><summary>{s.title} · 当时引用片段 · 版本 {s.revision}</summary><p>{s.truncated?'只读取以下片段，未阅读全文。':'本次读取完整文字。'}原文共 {s.totalCharacters} 字符。{s.sourceField==='transcriptContent'?'位置对应正文与带时间戳的录音转写。':''}</p>{s.excerpts?.map(e=><div key={e.start}><small>位置 {e.start}–{e.end}{e.selectionMethod==='distributed_preview'?' · 分布式预览':''}</small><p className="preserve-text">{e.quote}</p></div>)}</details>)}</div>;}
export function Toast({message}:{message:string}){return message?<div className="toast" role="status"><Check size={17}/>{message}</div>:null;}
