import {useEffect,useState} from 'react';
import {api,post} from './api';
import {ErrorBanner,Spinner} from './components';
type Item={id:string;title:string;invalid?:string};
export default function EventRelations({kind,eventId,ids,onChange,suggested=[]}:{kind:'event'|'workTask';eventId?:string;ids:string[];onChange:(ids:string[])=>void;suggested?:string[]}){
 const label=kind==='event'?'关联要事':'关联任务';
 const [q,setQ]=useState(''),[offset,setOffset]=useState(0),[page,setPage]=useState<{items:Item[];total:number}>({items:[],total:0}),[selected,setSelected]=useState<Item[]>([]),[error,setError]=useState(''),[selectedError,setSelectedError]=useState(''),[loading,setLoading]=useState(false),[attempt,setAttempt]=useState(0);
 const signature=JSON.stringify(ids);
 useEffect(()=>{let current=true;setLoading(true);setError('');void api<{items:Item[];total:number}>(`/event-references?kind=${kind}&q=${encodeURIComponent(q)}&offset=${offset}&limit=20${eventId?'&excludeId='+encodeURIComponent(eventId):''}`).then(value=>{if(current)setPage(value);}).catch(e=>{if(current)setError(e.message);}).finally(()=>{if(current)setLoading(false);});return()=>{current=false;};},[kind,eventId,q,offset,attempt]);
 useEffect(()=>{let current=true;setSelectedError('');void post<{items:Item[]}>('/event-references/resolve',{kind,ids:JSON.parse(signature),...(eventId?{excludeId:eventId}:{})}).then(value=>{if(current)setSelected(value.items);}).catch(e=>{if(current)setSelectedError(e.message);});return()=>{current=false;};},[kind,eventId,signature,attempt]);
 return <fieldset className="event-related"><legend>{kind==='event'?'相关要事建议 / 关联':'关联任务与证据'}</legend><p>最多选择10项。翻页或搜索不会清除已选内容。{kind==='workTask'?'复核会读取关联任务的计划、执行证据和成果；不会修改或启动任务。':''}</p><label>搜索{label}<input value={q} onChange={e=>{setQ(e.target.value);setOffset(0);}}/></label><ErrorBanner message={error||selectedError}/>{(error||selectedError)&&<button type="button" className="btn secondary" onClick={()=>setAttempt(v=>v+1)}>重试加载{label}</button>}
 {ids.length>0&&<div aria-label={'已选'+label}>{ids.map((id,index)=>{const item=selected.find(x=>x.id===id)||page.items.find(x=>x.id===id);return <p key={id+index}>{item?.title||id}{item?.invalid?' · '+item.invalid:''}<button type="button" className="btn text" onClick={()=>onChange(ids.filter(x=>x!==id))}>移除{item?.title||id}</button></p>;})}</div>}
 {loading?<Spinner label={'加载'+label}/>:!error&&<><div className="event-related-list">{page.items.map(item=>{const checked=ids.includes(item.id);return <label className={'event-related-option'+(checked?' selected':'')} key={item.id}><input type="checkbox" checked={checked} disabled={!checked&&ids.length>=10} onChange={e=>onChange(e.target.checked?[...ids,item.id]:ids.filter(id=>id!==item.id))}/><span className="event-related-title">{item.title}</span>{suggested.includes(item.id)&&<span className="event-related-suggestion">AI 建议</span>}</label>;})}</div>{!page.items.length&&<p>没有匹配的{label}。</p>}<div className="phase-actions"><button type="button" className="btn secondary" disabled={!offset} onClick={()=>setOffset(v=>Math.max(0,v-20))}>上一页{label}</button><span>共 {page.total} 项</span><button type="button" className="btn secondary" disabled={offset+20>=page.total} onClick={()=>setOffset(v=>v+20)}>下一页{label}</button></div></>}</fieldset>;
}
