import {contractPost} from './api';
import {API_BASE} from './api';
import {PetSourcePrompt} from './PetReminderContext';
import {usePetTarget,focusPetSource} from './usePetTarget';
import {eventRequest} from './eventRequest';
import EventActionRecovery from './EventActionRecovery';
import EventRelations from './EventRelations';
import EventChecks from './EventChecks';
import DiscussSource from './DiscussSource';
import {useEffect,useState} from 'react';
import {CalendarClock,Plus,Sparkles,Check,Trash2,Pencil,Link2} from 'lucide-react';
import {del,fileUrl} from './api';
import {Modal,ErrorBanner,Spinner,Empty} from './components';
import type {Attachment,Bootstrap,EventRecord,Note} from './types';

const localDate=(value:string)=>value?new Date(new Date(value).getTime()-new Date(value).getTimezoneOffset()*60000).toISOString().slice(0,16):'';
function EventImages({images,url}:{images:Attachment[];url:(image:Attachment)=>string}){return images.length?<div className="event-images">{images.map(image=><a key={image.id} href={url(image)} target="_blank" rel="noopener noreferrer" aria-label={'查看图片：'+image.name}><img src={url(image)} alt={image.name} loading="lazy"/><span>{image.name}</span></a>)}</div>:null;}
export default function Events({data,onRefresh,onOpenNote,onToast}:{data:Bootstrap;onRefresh:()=>Promise<void>;onOpenNote:(note:Note)=>void;onToast:(text:string)=>void}){
 const [editor,setEditor]=useState<EventRecord|'new'|null>(null),[title,setTitle]=useState(''),[summary,setSummary]=useState(''),[tags,setTags]=useState(''),[project,setProject]=useState(''),[priority,setPriority]=useState<'normal'|'high'>('normal'),[dueAt,setDueAt]=useState(''),[occurredAt,setOccurredAt]=useState(''),[sourceNoteId,setSourceNoteId]=useState(''),[relatedEventIds,setRelatedEventIds]=useState<string[]>([]),[suggestedRelatedEventIds,setSuggestedRelatedEventIds]=useState<string[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [draftNotice,setDraftNotice]=useState('');
 const [eventType,setEventType]=useState<'long_term'|'one_off'|''>('one_off');
 const [search,setSearch]=useState(''),[statusFilter,setStatusFilter]=useState('all'),[typeFilter,setTypeFilter]=useState('all'),[priorityFilter,setPriorityFilter]=useState('all');
 function clearFilters(){setSearch('');setStatusFilter('all');setTypeFilter('all');setPriorityFilter('all');}
 const events=[...(data.events||[])].filter(event=>(statusFilter==='all'||(event.lifecycleStatus==='ended'||event.status==='ended'?'ended':'ongoing')===statusFilter)&&(typeFilter==='all'||(event.eventType||'unknown')===typeFilter)&&(priorityFilter==='all'||event.priority===priorityFilter)&&(!search.trim()||[event.title,event.summary,event.project,event.occurredAt,...event.tags].filter(Boolean).join(' ').toLocaleLowerCase().includes(search.trim().toLocaleLowerCase()))).sort((a,b)=>(a.status==='open'?0:1)-(b.status==='open'?0:1)||(a.dueAt||'9999').localeCompare(b.dueAt||'9999'));
 const waitingForReview=data.events.some(event=>event.status==='open'&&event.priority==='high'&&event.dueAt&&Date.parse(event.dueAt)<=Date.now()&&(event.reviewedDueAt!==event.dueAt||event.reviewStale)&&event.reviewJob?.state!=='failed');
 useEffect(()=>{if(!waitingForReview)return;const timer=setInterval(()=>void onRefresh().catch(()=>{}),4000);return()=>clearInterval(timer);},[waitingForReview,onRefresh]);
 const [relatedTaskIds,setRelatedTaskIds]=useState<string[]>([]);
 const sourceNote=data.notes.find(note=>note.id===sourceNoteId);
 const savedImages=editor&&editor!=='new'&&editor.sourceNoteId===sourceNoteId&&editor.images?.length?editor.images:null;
 const previewImages=savedImages||sourceNote?.attachments.filter(image=>image.mime.startsWith('image/'))||[];
 function open(value:EventRecord|'new',source?:Note){setEditor(value);setEventType(value==='new'?'one_off':value.eventType||'');setTitle(value==='new'?source?.title||'':value.title);setSummary(value==='new'?source?.summary||source?.content.slice(0,300)||'':value.summary);setTags(value==='new'?source?.tags.join('，')||'':value.tags.join('，'));setProject(value==='new'?source?.project||'':value.project);setPriority(value==='new'?'normal':value.priority);setDueAt(value==='new'?'':localDate(value.dueAt));setOccurredAt(value==='new'?'':value.occurredAt||'');setSourceNoteId(value==='new'?source?.id||'':value.sourceNoteId||'');setRelatedEventIds(value==='new'?[]:value.relatedEventIds||[]);setRelatedTaskIds(value==='new'?[]:value.relatedTaskIds||[]);setSuggestedRelatedEventIds([]);setDraftNotice('');setError('');}
 async function save(){if(!eventType){setError('请选择长期或一次性要事。');return;}setBusy(true);setError('');try{const body={eventType,title,summary,occurredAt:occurredAt||null,tags:tags.split(/[,，#]/).map(x=>x.trim()).filter(Boolean),project,priority,dueAt:dueAt?new Date(dueAt).toISOString():'',sourceNoteId:sourceNoteId||null,relatedEventIds,relatedTaskIds};if(editor==='new')await eventRequest('/events',body);else if(editor)await eventRequest('/events/'+editor.id,{...body,revision:editor.revision},'PATCH');setEditor(null);await onRefresh();onToast('要事已保存');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function suggest(){if(!sourceNoteId&&(!editor||editor==='new')&&!title.trim()&&!summary.trim()){setError('请先写下标题或摘要，或选择一条来源记录。');return;}setBusy(true);setError('');try{const reference=editor&&editor!=='new'?{eventId:editor.id,eventRevision:editor.revision,...(sourceNoteId&&editor.sourceNoteId!==sourceNoteId?{noteId:sourceNoteId}:{})}:{...(sourceNoteId?{noteId:sourceNoteId,noteRevision:sourceNote?.revision}:{})};const result=await contractPost('postEventsSuggest','/events/suggest',{...reference,draft:{title,summary,tags:tags.split(/[,，#]/).map(x=>x.trim()).filter(Boolean),project}});setDraftNotice([result.inputNotice,...(result.removedSuggestions||[]).map(item=>`已移除关联建议${item.id?' '+item.id:''}：${item.reason}`)].filter(Boolean).join('；'));setTitle(result.title);setSummary(result.summary);setTags(result.tags.join('，'));setProject(result.project);const validRelatedIds=result.relatedEventIds;setRelatedEventIds(validRelatedIds);setSuggestedRelatedEventIds(validRelatedIds);onToast(result.analyzedImages?`已结合 ${result.analyzedImages} 张图片填写 AI 草稿，请核对后保存`:'AI 草稿已填入，请核对后保存');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function confirm(event:EventRecord){try{await eventRequest('/events/'+event.id+'/confirm',{revision:event.revision,occurrenceId:event.currentOccurrenceId});await onRefresh();onToast('已确认本次检查，要事仍在进行');}catch(e){setError((e as Error).message);}}
 async function check(event:EventRecord){setBusy(true);setError('');try{await eventRequest('/events/'+event.id+'/check',{revision:event.revision,occurrenceId:event.currentOccurrenceId});await onRefresh();onToast('已提交后台复核，结果会自动更新');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function remove(event:EventRecord){if(!window.confirm('删除这条要事？来源记录会保留。'))return;try{await del('/events/'+event.id,event.revision);await onRefresh();onToast('要事已删除');}catch(e){setError((e as Error).message);}}
 usePetTarget('events',item=>{if(!data.events.some(event=>event.id===item.sourceId)){setError('这条要事已不存在，请刷新提示。');return true;}clearFilters();focusPetSource('event-'+item.sourceId);return true;});
 return <><EventActionRecovery onRefresh={async()=>{await onRefresh();setError('');}}/><div className="page-heading"><div><span className="eyebrow">MOMENTS THAT MATTER</span><h1>要事</h1><p>把重要的事留在这里，到了约定时间再一起检查。</p></div><button className="btn primary" onClick={()=>open('new')}><Plus size={17}/>新建要事</button></div><ErrorBanner message={error}/>
 <div className="phase-card" aria-label="查找要事"><label>搜索要事<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="标题、摘要、标签、项目或发生日期"/></label><div className="phase-actions"><label>状态<select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="all">全部状态</option><option value="ongoing">进行中（含已确认检查）</option><option value="ended">已结束</option></select></label><label>类型<select value={typeFilter} onChange={e=>setTypeFilter(e.target.value)}><option value="all">全部类型</option><option value="long_term">长期</option><option value="one_off">一次性</option><option value="unknown">类型待选择</option></select></label><label>等级<select value={priorityFilter} onChange={e=>setPriorityFilter(e.target.value)}><option value="all">全部等级</option><option value="normal">普通</option><option value="high">高等级</option></select></label><button type="button" className="btn secondary" onClick={clearFilters}>清除筛选</button></div><p role="status">显示 {events.length} / {data.events.length} 条要事</p></div>
 {!events.length?<Empty title={data.events.length?'没有匹配的要事':'还没有要事'} description={data.events.length?'请修改关键词或清除筛选，已有要事仍保留。':'可以从已有记录整理一条要事，也可以直接新建。'} icon={<CalendarClock size={30}/>}/>:<div className="event-list">{events.map(event=>{const due=event.status==='open'&&!!event.dueAt&&Date.parse(event.dueAt)<=Date.now();const source=data.notes.find(n=>n.id===event.sourceNoteId);return <article id={'event-'+event.id} tabIndex={-1} className={'event-card '+(due?'due':'')} key={event.id}><header><span className={'event-priority '+event.priority}>{event.priority==='high'?'高等级':'普通要事'}</span><span>{event.eventType==='long_term'?'长期':event.eventType==='one_off'?'一次性':'类型待选择'} · {event.lifecycleStatus==='ended'?'已结束':event.status==='confirmed'?'本次检查已确认，事情进行中':due?'待你确认':event.dueAt?'等待约定时间':'未设提醒'}</span></header><h2>{event.title}</h2><PetSourcePrompt kind="event" id={event.id}/><p>{event.summary}</p><EventImages images={event.images||[]} url={image=>`${API_BASE}/events/${event.id}/image/${image.id}`}/><div className="event-meta">{event.occurredAt&&<span>发生日期：{event.occurredAt}</span>}{event.dueAt&&<span><CalendarClock size={15}/>检查时间：{new Date(event.dueAt).toLocaleString('zh-CN')}</span>}{event.project&&<span>{event.project}</span>}{event.tags.map(tag=><span key={tag}>#{tag}</span>)}</div>{source&&<button className="btn text" onClick={()=>onOpenNote(source)}><Link2 size={14}/>来源：{source.title}</button>}{event.relatedEventIds?.length?<small>相关要事：{event.relatedEventIds.map(id=>data.events.find(e=>e.id===id)?.title).filter(Boolean).join('、')}</small>:null}
 {due&&event.priority==='high'&&<div className="event-review"><strong>{event.reviewStale?'旧建议依据已变化，需重新复核':'到点复核建议 · 由你决定'}</strong><p>{event.reviewText||event.reviewNotice||event.reviewJob?.error||(event.reviewJob?.state==='running'?'正在复核，结果会自动更新。':'正在等待后台复核；约定和输入已保存，完成后可确认提醒。')}</p>{event.reviewSnapshot&&<details><summary>本次复核依据</summary><p>生成于 {new Date(event.reviewSnapshot.createdAt).toLocaleString('zh-CN')}</p>{event.reviewSnapshot.sources.map((source,i)=><p key={source.kind+source.id+i}>{source.title} · {source.issue|| (source.missing?'来源缺失':'版本 '+source.revision)}</p>)}<p>图片仅采用已有文字解释，本次未直接识图。</p></details>}</div>}
 <footer><EventChecks event={event} onRefresh={onRefresh}/><DiscussSource id={event.id} kind="event"/>{due?<button className="btn primary small" disabled={event.priority==='high'&&(event.reviewedDueAt!==event.dueAt||event.reviewStale)} onClick={()=>void confirm(event)}><Check size={15}/>确认提醒</button>:null}{due&&event.priority==='high'?<button className="btn secondary small" disabled={busy} onClick={()=>void check(event)}><Sparkles size={15}/>{event.reviewedDueAt===event.dueAt?'重新复核':'立即复核'}</button>:null}<button className="btn secondary small" onClick={()=>open(event)}><Pencil size={15}/>{due?'稍后确认 / 编辑':'编辑'}</button><button className="icon-btn danger" aria-label={'删除要事：'+event.title} onClick={()=>void remove(event)}><Trash2 size={16}/></button></footer></article>;})}</div>}
 {editor&&<Modal title={editor==='new'?'新建要事':'编辑要事'} wide closeDisabled={busy} onClose={()=>{if(!busy)setEditor(null);}}><form className="form-body event-form" onSubmit={e=>{e.preventDefault();void save();}}><EventActionRecovery onRefresh={async request=>{if(request?.path===(editor==='new'?'/events':editor?'/events/'+editor.id:''))setEditor(null);await onRefresh();setError('');}}/><ErrorBanner message={error}/>{draftNotice&&<p role="status" className="preserve-text">{draftNotice}</p>}<fieldset disabled={busy} style={{display:'contents'}} aria-label="要事编辑字段"><label>从记录转为要事（可选）<select value={sourceNoteId} onChange={e=>{const id=e.target.value;setSourceNoteId(id);const n=data.notes.find(note=>note.id===id);if(n&&editor==='new')open('new',n);}}><option value="">不关联记录</option>{sourceNoteId&&!sourceNote&&<option value={sourceNoteId}>来源记录已删除（要事图片仍保留）</option>}{data.notes.map(n=><option key={n.id} value={n.id}>{n.title}</option>)}</select></label><EventImages images={previewImages} url={image=>savedImages&&editor&&editor!=="new"?`${API_BASE}/events/${editor.id}/image/${image.id}`:fileUrl(sourceNoteId,image.id)}/>{previewImages.length>0&&<p className="muted small-copy">保存要事时会保留 {previewImages.length} 张图片的独立副本；AI 辅助编辑会读取这些图片。</p>}<button type="button" className="btn secondary" disabled={busy||(!sourceNoteId&&!title.trim()&&!summary.trim()&&!savedImages?.length)} onClick={()=>void suggest()}><Sparkles size={16}/>交由 AI 辅助编辑</button><p className="muted small-copy">AI 只填写草稿，核对后由你保存。</p><label>标题<input value={title} onChange={e=>setTitle(e.target.value)} maxLength={200} required/></label><label>摘要<textarea value={summary} onChange={e=>setSummary(e.target.value)} maxLength={3000} rows={5}/></label><div className="form-row"><label>要事类型<select value={eventType} onChange={e=>setEventType(e.target.value as typeof eventType)} required><option value="" disabled>请选择类型</option><option value="one_off">一次性</option><option value="long_term">长期</option></select></label><label>等级<select value={priority} onChange={e=>setPriority(e.target.value as 'normal'|'high')}><option value="normal">普通要事</option><option value="high">高等级 · 到点检查并提建议</option></select></label><label>事情发生日期（可不填写）<input type="date" value={occurredAt} onChange={e=>setOccurredAt(e.target.value)}/></label><label>约定检查时间（可不设置）<input disabled={editor!=='new'&&editor.lifecycleStatus==='ended'} type="datetime-local" value={dueAt} onChange={e=>setDueAt(e.target.value)}/></label></div><div className="form-row"><label>标签<input value={tags} onChange={e=>setTags(e.target.value)} placeholder="用逗号分隔"/></label><label>项目<input value={project} onChange={e=>setProject(e.target.value)}/></label></div>
 <EventRelations kind="event" eventId={editor==='new'?undefined:editor.id} ids={relatedEventIds} onChange={setRelatedEventIds} suggested={suggestedRelatedEventIds}/><EventRelations kind="workTask" eventId={editor==='new'?undefined:editor.id} ids={relatedTaskIds} onChange={setRelatedTaskIds}/>

 <button className="btn primary full" disabled={busy||!title.trim()}>{busy?<Spinner label="处理中"/>:'确认并保存要事'}</button></fieldset></form></Modal>}
 </>;
}
