import {usePetTarget,focusPetSource} from './usePetTarget';
import MemoryOrigin from './MemoryOrigin';
import {memoryRequest,pendingMemoryRequest,retryMemoryRequest} from './memoryRequest';
import MemoryScopeFields,{type MemoryScopeKind} from './MemoryScopeFields';
import {useRef,useState} from 'react';
import {Plus,Check,Pause,Play,Trash2,Brain,Pencil,ShieldCheck} from 'lucide-react';
import {api,del,ApiError} from './api';
import {Modal,ErrorBanner,Spinner,Empty} from './components';
import type {Bootstrap,Memory,Note} from './types';
export default function Memories({data,onRefresh,onOpen,onToast}:{data:Bootstrap;onRefresh:()=>Promise<void>;onOpen:(n:Note)=>void;onToast:(s:string)=>void}){
 const [filter,setFilter]=useState('all'),[editor,setEditor]=useState<Memory|'new'|null>(null),[content,setContent]=useState(''),[scope,setScope]=useState('通用'),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const [reviewedSource,setReviewedSource]=useState<{memoryId:string;memoryRevision:number;kind:string;id:string;revision:number;title:string;text:string;truncated:boolean;totalCharacters:number}|null>(null),[sourceConfirmed,setSourceConfirmed]=useState(false);
 const sourceEpoch=useRef(0);const [sourceLoading,setSourceLoading]=useState(false);
 async function loadSource(){if(!editor||editor==='new')return;const current=editor,epoch=++sourceEpoch.current;setSourceLoading(true);setSourceConfirmed(false);setError('');try{const source=await api<NonNullable<typeof reviewedSource>>(`/memories/${current.id}/source-review`);if(epoch!==sourceEpoch.current)return;if(source.memoryRevision!==current.revision)throw new Error('记忆已变化，请关闭编辑并刷新后再核对。');setReviewedSource(source);}catch(e){if(epoch===sourceEpoch.current)setError((e as Error).message);}finally{if(epoch===sourceEpoch.current)setSourceLoading(false);}}
 const [pending,setPending]=useState(pendingMemoryRequest);
 const [conflict,setConflict]=useState<{memory:Memory;conflicts:{id:string;revision:number;content:string;reason:string}[]}|null>(null);
 function failure(e:unknown){setError((e as Error).message);if(e instanceof ApiError&&e.current&&typeof e.current==='object'&&'conflicts' in e.current)setConflict(e.current as NonNullable<typeof conflict>);}
 const [scopeKind,setScopeKind]=useState<MemoryScopeKind>('global'),[scopeId,setScopeId]=useState('');
 usePetTarget('memories',item=>{if(!data.memories.some(m=>m.id===item.sourceId)){setError('这条记忆已不存在，请刷新提示。');return true;}setFilter('all');focusPetSource('memory-'+item.sourceId);return true;});
 const visible=data.memories.filter(m=>filter==='all'?m.status!=='rejected':m.status===filter);
 const edit=(m:Memory|'new')=>{sourceEpoch.current++;setSourceLoading(false);setSourceConfirmed(false);setReviewedSource(null);setEditor(m);setContent(m==='new'?'':m.content);setScope(m==='new'?'通用':m.scope);setScopeKind(m==='new'?'global':m.scopeKind||'global');setScopeId(m==='new'?'':m.scopeId||'');setError('');};
 async function submit(){setBusy(true);setError('');try{if(editor==='new')await memoryRequest('POST','/memories',{content,scope,scopeKind,scopeId});else if(editor)await memoryRequest('PATCH','/memories/'+editor.id,{content,scope,scopeKind,scopeId,revision:editor.revision,...(sourceConfirmed&&reviewedSource?{reviewedSource:{kind:reviewedSource.kind,id:reviewedSource.id,revision:reviewedSource.revision}}:{})});setEditor(null);await onRefresh();onToast(editor==='new'?'已添加候选记忆，确认后才会生效':'修改已保存；候选需确认后才生效');}catch(e){setError((e as Error).message);}finally{setBusy(false);setPending(pendingMemoryRequest());}}
 async function status(m:Memory,s:string){setBusy(true);setError('');try{await memoryRequest('PATCH','/memories/'+m.id,{revision:m.revision,status:s});await onRefresh();onToast(s==='active'?'这条记忆已生效':'已暂停使用这条记忆');}catch(e){failure(e);}finally{setBusy(false);setPending(pendingMemoryRequest());}}
 async function resolveConflict(keepNew:boolean){if(!conflict)return;setBusy(true);setError('');try{await memoryRequest('PATCH','/memories/'+conflict.memory.id,{revision:conflict.memory.revision,status:keepNew?'active':'rejected',...(keepNew?{replace:conflict.conflicts.map(({id,revision})=>({id,revision}))}:{})});setConflict(null);await onRefresh();onToast(keepNew?'已确认新记忆，旧记忆保留为暂停记录':'已保留原有记忆');}catch(e){failure(e);}finally{setBusy(false);setPending(pendingMemoryRequest());}}
 async function retry(){setBusy(true);setError('');try{await retryMemoryRequest();setEditor(null);setConflict(null);await onRefresh();onToast('已确认上一次操作结果');}catch(e){failure(e);}finally{setBusy(false);setPending(pendingMemoryRequest());}}
 async function remove(m:Memory){if(!window.confirm('确定删除这条记忆？原始记录会保留。'))return;try{await del('/memories/'+m.id,m.revision);await onRefresh();onToast('已删除记忆');}catch(e){setError((e as Error).message);}}
 return <>{pending&&<div className="phase-card" role="status"><p>上一项记忆操作尚未收到确认，输入已保留。重试不会重复创建记忆。</p><button className="btn secondary" disabled={busy} onClick={()=>void retry()}>重试未确认操作</button></div>}<div className="page-heading"><div><span className="eyebrow">A LITTLE MORE LIKE YOU</span><h1>慢慢了解你，也由你决定</h1><p>记住你的偏好与背景，让每一次协助更贴近你。</p></div><button className="btn primary" onClick={()=>edit('new')}><Plus size={17}/>添加记忆</button></div><div className="memory-promise"><ShieldCheck size={25} strokeWidth={1.5}/><div><h3>你确认的，才会成为记忆</h3><p>候选记忆不会自动生效。你随时可以修改、暂停或删除。</p></div><span>{data.memories.filter(m=>m.status==='active'&&!m.sourceIssue).length} 条生效中</span></div><div className="filter-tabs">{[['all','全部记忆'],['candidate','待确认'],['active','已生效'],['paused','已暂停']].map(([v,l])=><button key={v} className={filter===v?'selected':''} onClick={()=>setFilter(v)}>{l}{v==='candidate'&&data.memories.filter(m=>m.status===v).length>0&&<span>{data.memories.filter(m=>m.status===v).length}</span>}</button>)}</div><ErrorBanner message={error}/>
 {!visible.length?<Empty title={filter==='candidate'?'没有待确认的记忆':'还没有这类记忆'} description="可以添加一条偏好，比如「周报先写结论」，也可以从记录详情提取候选记忆。" icon={<Brain size={30} strokeWidth={1.3}/>}/>:<div className="memory-grid">{visible.map(m=>{return <article className={'memory-card '+m.status} key={m.id} id={'memory-'+m.id} tabIndex={-1}><div className="memory-card-top"><span className={'memory-status '+m.status}><i/>{m.sourceIssue?'来源失效，暂不采用':({candidate:'等待你确认',active:'已生效',paused:'已暂停',invalid:'来源已失效',rejected:'已忽略'})[m.status]}</span><span className="scope-tag">{m.scopeKind==='project'?'项目':m.scopeKind==='thread'?'话题':'全局'}{m.scopeId?' · '+m.scopeId.slice(0,8):''} · {m.scope}</span></div><p>{m.content}</p>{m.sourceIssue&&<p role="status">{m.sourceIssue}</p>}<MemoryOrigin memory={m} notes={data.notes} onOpen={onOpen} onError={setError}/><footer><div><button className="icon-btn" aria-label="编辑记忆" onClick={()=>edit(m)}><Pencil size={15}/></button><button className="icon-btn danger" aria-label="删除记忆" onClick={()=>remove(m)}><Trash2 size={15}/></button></div>{m.status==='candidate'?<button className="btn primary small" disabled={busy} onClick={()=>status(m,'active')}><Check size={15}/>确认记住</button>:m.status==='active'?<button className="btn secondary small" disabled={busy} onClick={()=>status(m,'paused')}><Pause size={14}/>暂停</button>:m.status==='paused'?<button className="btn secondary small" disabled={busy} onClick={()=>status(m,'active')}><Play size={14}/>恢复</button>:null}</footer></article>;})}</div>}
 {conflict&&<Modal closeDisabled={busy} title="核对记忆冲突" onClose={()=>{if(!busy){setConflict(null);void onRefresh();}}}><div className="form-body"><ErrorBanner message={error}/><h3>待确认的新记忆</h3><p className="preserve-text">{conflict.memory.content}</p><h3>已有记忆</h3>{conflict.conflicts.map(item=><article className="phase-card" key={item.id}><p className="preserve-text">{item.content}</p><p>{item.reason}</p></article>)}<p>使用新记忆会将上面的旧记忆暂停并保留历史。提交时会再次检查其他冲突。</p><button className="btn primary" disabled={busy} onClick={()=>void resolveConflict(true)}>{busy?'正在核对…':'确认使用新记忆，替代上述旧记忆'}</button><button className="btn secondary" disabled={busy} onClick={()=>void resolveConflict(false)}>保留旧记忆，放弃这条候选</button></div></Modal>}
 {editor&&<Modal closeDisabled={busy} title={editor==='new'?'让拾光记住一点关于你的事':'编辑这条记忆'} onClose={()=>{if(!busy)setEditor(null);}}><form className="form-body" onSubmit={e=>{e.preventDefault();submit();}}><ErrorBanner message={error}/><label>记忆内容<textarea autoFocus placeholder="例如：我的工作周报先写结论，再列进展和风险。" value={content} onChange={e=>setContent(e.target.value)} rows={5} maxLength={2000}/></label>{editor!=='new'&&(editor.sourceId||editor.sourceRef||editor.sourceConversationId)&&<section className="phase-panel"><button type="button" className="btn secondary" disabled={busy||sourceLoading} onClick={()=>void loadSource()}>{sourceLoading?'读取来源…':'读取最新来源并核对'}</button>{reviewedSource&&<><details open><summary>{reviewedSource.title} · 版本 {reviewedSource.revision}</summary><div style={{maxHeight:280,overflowY:'auto',whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{reviewedSource.text||'来源没有可用文字，请先补充内容或查看原件。'}</div>{reviewedSource.truncated&&<p>这里只展示前100,000字，来源共 {reviewedSource.totalCharacters} 字；需完整核对时请到原来源查看。</p>}</details><MemoryOrigin memory={editor} notes={data.notes} onOpen={onOpen} onError={setError}/><label><input type="checkbox" checked={sourceConfirmed} disabled={busy} onChange={e=>setSourceConfirmed(e.target.checked)}/>我已核对这个来源版本，当前记忆内容仍有依据</label><p>保存后仍为待确认候选，须检查冲突并确认启用。</p></>}</section>}<MemoryScopeFields kind={scopeKind} id={scopeId} disabled={busy} onChange={(kind,id)=>{setScopeKind(kind);setScopeId(id);}}/><label>用途限制<select value={scope} onChange={e=>setScope(e.target.value)}><option>通用</option><option>周报</option><option>文章</option></select></label><p className="muted small-copy">只记下真实、稳定的信息。一次性的任务要求不必长期保存。</p><button className="btn primary full" disabled={busy||!content.trim()||(scopeKind!=='global'&&!scopeId)}>{busy?<Spinner label="保存中"/>:'保存记忆'}</button></form></Modal>}
 </>;
}
