import type {ConversationReference} from './types';
export type PendingConversation={key:string;payload:{query:string;project:string;projectId?:string;webSearch:boolean;references:{id:string;kind:ConversationReference['kind'];revision:number}[];threadId?:string;continueRunId?:string;opId:string};references:ConversationReference[]};
const storageKey='shiguang-pending-conversations';
const validReference=(value:unknown,title=false)=>{const r=value as Partial<ConversationReference>|null;return !!r&&typeof r.id==='string'&&['note','event','libraryFile'].includes(r.kind||'')&&Number.isInteger(r.revision)&&(!title||typeof r.title==='string');};
function entries():PendingConversation[]{try{const value=JSON.parse(sessionStorage.getItem(storageKey)||'[]');return Array.isArray(value)?value.filter(item=>item&&typeof item.key==='string'&&typeof item.payload?.opId==='string'&&typeof item.payload?.query==='string'&&typeof item.payload.project==='string'&&(item.payload.projectId===undefined||typeof item.payload.projectId==='string')&&typeof item.payload.webSearch==='boolean'&&(item.payload.threadId===undefined||typeof item.payload.threadId==='string')&&Array.isArray(item.payload.references)&&item.payload.references.every((ref:unknown)=>validReference(ref))&&Array.isArray(item.references)&&item.references.every((ref:unknown)=>validReference(ref,true))):[];}catch{return [];}}
export function findPendingConversation(key:string){return entries().find(item=>item.key===key)||null;}
export function restorePendingConversation(){try{if(sessionStorage.getItem('sourceDiscussion')||sessionStorage.getItem('libraryDiscussion')||sessionStorage.getItem('memoryDiscussion'))return null;}catch{return null;}return entries().at(-1)||null;}
export function rememberPendingConversation(item:PendingConversation){try{sessionStorage.setItem(storageKey,JSON.stringify([...entries().filter(old=>old.key!==item.key),item]));return true;}catch{return false;}}
export function forgetPendingConversation(opId:string){try{sessionStorage.setItem(storageKey,JSON.stringify(entries().filter(item=>item.payload.opId!==opId)));}catch{/* In-memory state still works when browser storage is unavailable. */}}
