import {API_BASE} from './api';
import {randomId} from './randomId';
import DiscussSource from './DiscussSource';
import {useEffect,useState} from 'react';
import {api,post,patch} from './api';
import {Modal,ErrorBanner,Spinner,Markdown} from './components';
import type {Note,Attachment} from './types';
type Project={id:string;revision:number;name:string};
type LinkKind='note'|'event'|'libraryFile'|'artifact';
type Kind=LinkKind|'memory';
type Item={images?:Attachment[];id:string;revision:number;title:string;content?:string;summary?:string;body?:string;copyName?:string;projectName?:string|null;status?:string;sourceIssue?:string;scope?:string};
type Result={items:Item[];total:number};
const linkKinds:LinkKind[]=['note','event','libraryFile','artifact'];
const kinds:Kind[]=[...linkKinds,'memory'];
const memoryStatus:Record<string,string>={candidate:'待确认',active:'已生效',paused:'已暂停',rejected:'已忽略',invalid:'已失效'};
const itemTitle=(item:Item)=>item.title||item.content?.slice(0,60)||'未命名';
const labels:Record<Kind,string>={note:'记录',event:'要事',libraryFile:'文件',artifact:'成果',memory:'长期记忆'};
function Group({project,kind,version,onNote,onNavigate}:{project:Project;kind:Kind;version:number;onNavigate:()=>void;onNote:(note:Note)=>void}){
 const [offset,setOffset]=useState(0),[attempt,setAttempt]=useState(0),[data,setData]=useState<Result|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[detail,setDetail]=useState<Item|null>(null);
 useEffect(()=>{let active=true;setLoading(true);setError('');void api<Result>(`/projects/${project.id}/items?kind=${kind}&offset=${offset}&limit=10`).then(result=>{if(active){if(offset&&result.items.length===0){setOffset(0);return;}setData(result);}}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[project.id,kind,offset,version,attempt]);
 return <section className="phase-card" aria-label={'项目'+labels[kind]}><h3>{labels[kind]}</h3><ErrorBanner message={error}/>{error&&<button className="btn secondary" onClick={()=>setAttempt(v=>v+1)}>重试加载{labels[kind]}</button>}{loading?<Spinner label={'加载'+labels[kind]+'…'}/>:!error&&data&&<>{!data.items.length&&<p>还没有关联的{labels[kind]}。</p>}{data.items.map(item=><p key={item.id}><button className="btn text" onClick={()=>{if(kind==='note')onNote(item as Note);else setDetail(item);}}>{itemTitle(item)}</button>{kind==='memory'&&<span> · {item.sourceIssue?'暂不采用':memoryStatus[item.status||'']||'未知状态'} · {item.scope||'通用'}</span>}</p>)}<div className="phase-actions"><span>共 {data.total} 项</span><button className="btn secondary" disabled={!offset} onClick={()=>setOffset(v=>Math.max(0,v-10))}>上一页</button><button className="btn secondary" disabled={offset+10>=data.total} onClick={()=>setOffset(v=>v+10)}>下一页</button></div></>}{detail&&<Modal title={kind==='memory'?'项目记忆详情':detail.title||'资料详情'} onClose={()=>setDetail(null)} wide><div className="phase-panel">{kind==='memory'&&<><p>{memoryStatus[detail.status||'']||'未知状态'} · 项目：{project.name} · {detail.scope||'通用'}</p><ErrorBanner message={detail.sourceIssue||''}/><p>暂停、编辑或确认请到“我的记忆”。项目汇集不会自动启用记忆。</p></>}<Markdown>{detail.content||detail.summary||detail.body||'暂无可展示的正文。'}</Markdown>{kind==='event'&&<><div className="event-images">{(detail.images||[]).map(image=><a key={image.id} href={`${API_BASE}/events/${detail.id}/image/${image.id}`} target="_blank" rel="noopener noreferrer" aria-label={'查看图片：'+image.name}><img src={`${API_BASE}/events/${detail.id}/image/${image.id}`} alt={image.name} loading="lazy"/><span>{image.name}</span></a>)}</div><DiscussSource id={detail.id} kind="event" onOpened={onNavigate}/></>}{kind==='libraryFile'&&detail.copyName&&<a className="btn secondary" href={(API_BASE + "/library/")+detail.id+'/file'}>下载文件副本</a>}</div></Modal>}</section>;
}
function LinkSource({project,onSaved}:{project:Project;onSaved:()=>void}){
 const [kind,setKind]=useState<LinkKind>('note'),[q,setQ]=useState(''),[offset,setOffset]=useState(0),[version,setVersion]=useState(0),[data,setData]=useState<Result|null>(null),[selection,setSelection]=useState<Item|null>(null),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState('');
 useEffect(()=>{let active=true;setLoading(true);setError('');void api<Result>(`/projects/${project.id}/candidates?kind=${kind}&q=${encodeURIComponent(q)}&offset=${offset}&limit=10`).then(r=>{if(active)setData(r);}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[project.id,kind,q,offset,version]);
 async function link(){if(!selection)return;setBusy(true);setError('');setMessage('');try{await post(`/projects/${project.id}/links`,{kind,id:selection.id,revision:selection.revision});setMessage('已关联：'+selection.title);setSelection(null);setOffset(0);setVersion(v=>v+1);onSaved();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <details className="phase-card"><summary>关联已有资料</summary><p>选择资料后明确关联。若资料已属于其他项目，保存后会移到当前项目；聊天保持独立。</p><fieldset disabled={busy}><label>资料类型<select value={kind} onChange={e=>{setKind(e.target.value as LinkKind);setSelection(null);setOffset(0);setMessage('');}}>{linkKinds.map(k=><option key={k} value={k}>{labels[k]}</option>)}</select></label><label>按标题查找<input value={q} onChange={e=>{setQ(e.target.value);setOffset(0);}}/></label><ErrorBanner message={error}/>{error&&<button className="btn secondary" onClick={()=>setVersion(v=>v+1)}>重新加载候选资料</button>}{loading?<Spinner label="查找资料…"/>:!error&&data&&<>{data.items.map(item=><p key={item.id}><button className="btn secondary" aria-pressed={selection?.id===item.id} onClick={()=>setSelection(item)}>{item.title} · {item.id.slice(0,8)}{item.projectName?' · 当前项目：'+item.projectName:''}</button></p>)}{!data.items.length&&<p>没有可选资料。</p>}<div className="phase-actions"><button className="btn secondary" disabled={!offset} onClick={()=>setOffset(v=>Math.max(0,v-10))}>上一页候选</button><button className="btn secondary" disabled={offset+10>=data.total} onClick={()=>setOffset(v=>v+10)}>下一页候选</button></div></>}{selection&&<p>已选：{selection.title}（版本 {selection.revision}）<button className="btn text" onClick={()=>setSelection(null)}>清除选择</button></p>}<button className="btn primary" disabled={!selection||busy} onClick={()=>void link()}>{busy?'关联中…':'确认关联资料'}</button></fieldset>{message&&<p role="status">{message}</p>}</details>;
}
function ProjectDetail({project,onUpdated,onNote,onNavigate}:{project:Project;onUpdated:()=>void;onNavigate:()=>void;onNote:(note:Note)=>void}){
 const [name,setName]=useState(project.name),[busy,setBusy]=useState(false),[error,setError]=useState(''),[version,setVersion]=useState(0);
 return <><form className="phase-actions" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await patch('/projects/'+project.id,{name,revision:project.revision});onUpdated();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><label>项目名称<input value={name} maxLength={80} disabled={busy} onChange={e=>setName(e.target.value)}/></label><button className="btn secondary" disabled={busy||!name.trim()||name===project.name}>保存项目名称</button></form><ErrorBanner message={error}/><p>项目类别中的记录会在这里汇集；已单独关联其他项目的记录保留原关联。旧文字标签不会自动合并。</p><LinkSource project={project} onSaved={()=>setVersion(v=>v+1)}/>{kinds.map(kind=><Group key={kind} project={project} kind={kind} version={version} onNote={onNote} onNavigate={onNavigate}/>)}</>;
}
export default function ProjectsPanel({onClose,onNote}:{onClose:()=>void;onNote:(note:Note)=>void}){
 const [projects,setProjects]=useState<Project[]>([]),[id,setId]=useState(''),[name,setName]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[version,setVersion]=useState(0),[operation,setOperation]=useState(()=>randomId());
 useEffect(()=>{let active=true;setLoading(true);void api<{items:Project[]}>('/projects').then(r=>{if(active){setProjects(r.items);setId(old=>r.items.some(p=>p.id===old)?old:r.items[0]?.id||'');setError('');}}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[version]);
 const current=projects.find(p=>p.id===id);
 return <Modal title="项目资料" onClose={()=>{if(!busy)onClose();}} closeDisabled={busy} wide><div className="phase-panel"><p>按项目一起找记录、要事、文件、成果和项目记忆。每份资料的聊天仍各自保留。</p><ErrorBanner message={error}/>{error&&<button className="btn secondary" onClick={()=>setVersion(v=>v+1)}>重试加载项目</button>}<form className="phase-actions" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const created=await post<Project>('/projects',{name,opId:operation});setProjects(old=>old.some(p=>p.id===created.id)?old:[created,...old]);setId(created.id);setName('');setOperation(randomId());}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><label>新项目名称<input value={name} maxLength={80} disabled={busy} onChange={e=>{setName(e.target.value);setOperation(randomId());}}/></label><button className="btn secondary" disabled={busy||!name.trim()}>新建项目</button></form>{loading?<Spinner label="加载项目…"/>:<><label>选择项目<select value={id} onChange={e=>setId(e.target.value)}><option value="">请选择</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name} · {p.id.slice(0,8)}</option>)}</select></label>{current&&<ProjectDetail key={current.id+':'+current.revision} project={current} onUpdated={()=>setVersion(v=>v+1)} onNote={onNote} onNavigate={onClose}/>}</>}</div></Modal>;
}
