import {API_BASE} from './api';
import ResearchCandidates,{type CandidateDecision} from './ResearchCandidates';
import {useEffect,useRef,useState} from 'react';
import {api} from './api';
import {ErrorBanner,Markdown,Modal,Spinner} from './components';
import {PetSourcePrompt} from './PetReminderContext';
import {pendingResearch,researchRequest,retryResearch} from './researchRequest';
type Ref={id:string;kind:'note'|'event'|'libraryFile';revision:number;title:string};
type Brief={topic:string;background:string;questions:string[];constraints:string;type:'learning'|'comparison'|'feasibility'|'custom';asOf:string;expectedOutput:string;web:boolean};
type Plan={version:number;goal:string;conditions:string;steps:string[];known:string[];unknown:string[];deliverable:string};
type Evidence={id:string;kind?:string;url?:string;retrievedAt?:string;evidenceId:string;title:string;revision:number;quote:string;start:number;end:number;total:number;truncated:boolean;evidenceType?:string;providedAt?:string;urls?:string[]};
type Research={reportAcknowledgement?:{artifactId:string;artifactRevision:number;at:string};id:string;revision:number;candidateDecisions?:Record<string,CandidateDecision>;title:string;status:string;notice?:string;researchApproval?:{planVersion:number};handoff?:{id:string;text:string;state:string};externalMaterials?:{id:string;revision:number;title:string;providedAt:string|null;available:boolean}[];handoffBrief:string;researchBrief:Brief;plan:Plan|null;planHash:string|null;references:Ref[];job:{state:string;attempts:number;error:string|null};budget:{spentTimeMs:number;reservedTimeMs:number;chargedMicros:number;reservedMicros:number;uncertainMicros:number};artifacts:{id:string;revision:number;researchReportVersion?:number;body:string;mode:string;sources:Evidence[];actionCandidates:{title:string;description:string;kind:string}[]}[]};
function seed(){try{return JSON.parse(sessionStorage.getItem('taskDraft')||'{}');}catch{return {};}}
export function ResearchCreate({onCreated}:{onCreated:(id:string)=>void}){
 const [initial,setInitial]=useState(seed),[topic,setTopic]=useState<string>((initial.goal||'').length<=500?initial.goal||'':''),[background,setBackground]=useState<string>((initial.goal||'').length>500?initial.goal:''),[questions,setQuestions]=useState<string>((initial.goal||'').length<=500?initial.goal||'':''),[constraints,setConstraints]=useState(''),[type,setType]=useState<Brief['type']>('learning'),[output,setOutput]=useState('结论、概念、学习路径、小练习及待核实项'),[web,setWeb]=useState(true),[asOf,setAsOf]=useState(''),[refs,setRefs]=useState<Ref[]>(initial.references||[]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[pending,setPending]=useState(pendingResearch);
 useEffect(()=>{const update=()=>setPending(pendingResearch());window.addEventListener('research-request-change',update);return()=>window.removeEventListener('research-request-change',update);},[]);
 async function finish(request:()=>Promise<{id:string}>,clearDraft=true){setBusy(true);setError('');try{const task=await request();if(clearDraft){sessionStorage.removeItem('taskDraft');setInitial({});setTopic('');setBackground('');setQuestions('');setConstraints('');setType('learning');setOutput('结论、概念、学习路径、小练习及待核实项');setWeb(true);setAsOf('');setRefs([]);}onCreated(task.id);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <details className="phase-card"><summary>快速学习与调研</summary><p>先生成计划，由你确认后开始分析。计划、重试与降级共用 5 分钟 / 1 元预算；等待你确认不计时。</p><ErrorBanner message={error}/>{pending&&<div role="status"><p>上一项调研操作尚未收到确认，恢复不会重复创建或重复确认。</p><button className="btn secondary" disabled={busy} onClick={()=>void finish(retryResearch,pending?.path==='/research-tasks')}>恢复未确认的调研操作</button></div>}
 <form onSubmit={e=>{e.preventDefault();const questionList=questions.split('\n').map(x=>x.trim()).filter(Boolean);if(!questionList.length||questionList.length>8||questionList.some(q=>q.length>500)){setError('请填写1至8个关键问题，每行一个，每个最多500字；长段背景请保留在背景栏。');return;}void finish(()=>researchRequest('/research-tasks',{executionMode:'research',threadId:initial.threadId||'',references:refs.map(({id,kind,revision})=>({id,kind,revision})),researchBrief:{topic,background,questions:questionList,constraints,type,asOf,expectedOutput:output,web}}));}}>
 <fieldset disabled={busy||!!pending} style={{border:0,padding:0,minWidth:0}}><label>调研类型<select value={type} onChange={e=>setType(e.target.value as Brief['type'])}><option value="learning">快速学习</option><option value="comparison">方案比较</option><option value="feasibility">可行性分析</option><option value="custom">自定义</option></select></label>
 {(initial.goal||'').length>500&&<p role="status">原问题超过500字，已完整放入背景。请填写简短的调研主题，并将关键问题分行列出；原问题未被截断。</p>}<label>调研主题<input required maxLength={500} value={topic} onChange={e=>setTopic(e.target.value)}/></label><label>背景<textarea rows={3} maxLength={6000} value={background} onChange={e=>setBackground(e.target.value)}/></label>{initial.threadId&&<p>已关联来源话题，将保留有效摘要和未归纳的对话背景；助手建议不等于已确认事实，原会话保留。</p>}
 <label>关键问题（每行一个，最多 8 个，每个最多 500 字）<textarea required rows={4} maxLength={4008} value={questions} onChange={e=>setQuestions(e.target.value)}/></label><label>约束与已知条件<textarea rows={2} maxLength={4000} value={constraints} onChange={e=>setConstraints(e.target.value)}/></label><label>时效要求<input placeholder="例如：截至今天；不要求最新" maxLength={100} value={asOf} onChange={e=>setAsOf(e.target.value)}/></label><label>希望得到什么<input required maxLength={2000} value={output} onChange={e=>setOutput(e.target.value)}/></label>
 <label className="check-row"><input type="checkbox" checked={web} onChange={e=>setWeb(e.target.checked)}/><span>需要联网查证；不可用时保留已有材料并明确哪些内容未核验</span></label><ResearchSources refs={refs} setRefs={setRefs}/><button className="btn primary" disabled={busy||!!pending}>{busy?<Spinner label="正在保存调研…"/>:'生成调研计划'}</button></fieldset></form></details>;
}
export function ResearchSources({refs,setRefs,maxRefs=8}:{refs:Ref[];setRefs:(refs:Ref[])=>void;maxRefs?:number}){
 const [kind,setKind]=useState<Ref['kind']>('note'),[q,setQ]=useState(''),[items,setItems]=useState<Ref[]>([]),[cursor,setCursor]=useState<string|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false),[attempt,setAttempt]=useState(0);const epoch=useRef(0);
 async function load(next:string|null=null){const current=++epoch.current;setLoading(true);setError('');try{const data=await api<{items:Ref[];nextCursor:string|null}>('/research-sources?'+new URLSearchParams({kind,q,...(next?{cursor:next}:{})}));if(current===epoch.current){setItems(old=>next?[...old,...data.items]:data.items);setCursor(data.nextCursor);}}catch(e){if(current===epoch.current)setError((e as Error).message);}finally{if(current===epoch.current)setLoading(false);}}
 useEffect(()=>{setItems([]);setCursor(null);void load();return()=>{epoch.current++;};},[kind,q,attempt]);
 return <details><summary>引用记录、要事或已导入的文件（{refs.length}/{maxRefs}）</summary><p>当前读取文字正文。所选版本在生成、确认及发布前都会核对。</p><div aria-label="已选调研材料">{refs.map(ref=><p key={ref.kind+ref.id}>{ref.title} · 版本 {ref.revision}<button type="button" className="btn text" onClick={()=>setRefs(refs.filter(r=>r.id!==ref.id||r.kind!==ref.kind))}>移除 {ref.title}</button></p>)}</div><label>材料类型<select value={kind} onChange={e=>setKind(e.target.value as Ref['kind'])}><option value="note">记录</option><option value="event">要事</option><option value="libraryFile">文件副本</option></select></label><label>查找调研材料<input value={q} maxLength={200} onChange={e=>setQ(e.target.value)}/></label><ErrorBanner message={error}/><button type="button" className="btn text" onClick={()=>setAttempt(n=>n+1)}>刷新材料列表</button><div>{items.map(item=>{const selected=refs.find(r=>r.id===item.id&&r.kind===item.kind);return <label className="check-row" key={item.id}><input type="checkbox" checked={!!selected} disabled={!selected&&refs.length>=maxRefs} onChange={e=>setRefs(e.target.checked?[...refs,item]:refs.filter(r=>r.id!==item.id||r.kind!==item.kind))}/><span>{item.title} · 版本 {item.revision}{selected&&selected.revision!==item.revision?'（已选旧版本，请移除后重选）':''}</span></label>;})}</div>{loading&&<Spinner label="正在读取材料…"/>}{cursor&&<button type="button" className="btn secondary" disabled={loading} onClick={()=>void load(cursor)}>更多调研材料</button>}</details>;
}
export function ResearchDetail({id,onClose,onChanged}:{id:string;onClose:()=>void;onChanged:()=>void}){
 const [data,setData]=useState<Research|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[selectedReport,setSelectedReport]=useState('');const epoch=useRef(0);
 async function load(){const current=++epoch.current;try{const value=await api<Research>('/research-tasks/'+id);if(current===epoch.current)setData(value);}catch(e){if(current===epoch.current)setError((e as Error).message);}}
 useEffect(()=>{void load();const timer=setInterval(()=>void load(),2000);return()=>{epoch.current++;clearInterval(timer);};},[id]);
 async function action(action:'acknowledge_report'|'confirm'|'retry'|'retry_web'|'cancel'|'handoff'|'external'|'end_handoff',extra:Record<string,unknown>={}){if(!data)return;setBusy(true);setError('');try{await researchRequest('/research-tasks/'+id+'/action',{...extra,action,revision:data.revision,...(action==='confirm'?{approved:true,planVersion:data.plan!.version,planHash:data.planHash}:{})});await load();onChanged();return true;}catch(e){setError((e as Error).message);return false;}finally{setBusy(false);}}
 const labels:Record<string,string>={planning:'正在生成计划',draft:'计划待你确认',running:'正在调研',review:'成果待核对',failed:'执行失败',waiting:'等待网页回填（等待不计时）',cancelled:'已停止'};
 return <Modal title="调研计划与进度" onClose={onClose} wide><div className="phase-panel"><ErrorBanner message={error}/>{pendingResearch()&&<button className="btn secondary" disabled={busy} onClick={async()=>{setBusy(true);setError('');try{await retryResearch();await load();onChanged();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>恢复未确认的调研操作</button>}{!data?<Spinner label="正在读取调研…"/>:<><h2>{data.title}</h2><p role="status">{labels[data.status]||data.status}{data.job?.state==='pending'?' · 等待后台工作队列':''}</p><p>{data.notice}</p><PetSourcePrompt kind="workTask" id={id}/><p>已处理 {(data.budget.spentTimeMs/1000).toFixed(1)} / 300 秒；进行中预留 {(data.budget.reservedTimeMs/1000).toFixed(1)} 秒。保守费用核算 ¥{(data.budget.chargedMicros/1e6).toFixed(6)} / ¥1；进行中预留 ¥{(data.budget.reservedMicros/1e6).toFixed(6)}。</p>{data.budget.uncertainMicros>0&&<p>包含价格或用量的保守上界，并非供应商实际扣款账单。</p>}<h3>本次关键问题</h3><ol>{data.researchBrief.questions.map((q,i)=><li key={i}>{q}</li>)}</ol>
 {data.plan&&<><h3>计划</h3><p>{data.plan.goal}</p><p>{data.plan.conditions}</p><h4>已知条件</h4><ul>{data.plan.known.map((x,i)=><li key={i}>{x}</li>)}</ul><h4>缺少的信息</h4><ul>{data.plan.unknown.map((x,i)=><li key={i}>{x}</li>)}</ul><ol>{data.plan.steps.map((s,i)=><li key={i}>{s}</li>)}</ol><p>预期产物：{data.plan.deliverable}</p></>}
 <div className="phase-actions">{data.status==='draft'&&<button className="btn primary" disabled={busy} onClick={()=>void action('confirm')}>确认此计划并开始调研</button>}{data.status==='failed'&&<button className="btn secondary" disabled={busy} onClick={()=>void action('retry')}>重试调研（沿用剩余预算）</button>}{data.researchBrief.web&&data.researchApproval&&['review','failed'].includes(data.status)&&<button className="btn secondary" disabled={busy} onClick={()=>void action('retry_web')}>重新联网取材（沿用剩余预算）</button>}{data.status!=='cancelled'&&<button className="btn text" disabled={busy} onClick={()=>void action('cancel')}>取消调研</button>}</div>
 <ResearchHandoff data={data} busy={busy} act={action}/>{!!data.externalMaterials?.length&&<details><summary>已保存的网页回填记录</summary>{data.externalMaterials.map(source=><article className="phase-card" key={source.id}><strong>{source.title}</strong><p>{source.providedAt} · 用户提供，未独立核验{!source.available?'；资料已失效':''}</p><ResearchExternal taskId={id} sourceId={source.id}/></article>)}</details>}{data.artifacts.length>1&&<label>查看报告版本<select value={selectedReport||data.artifacts.at(-1)?.id} onChange={e=>setSelectedReport(e.target.value)}>{data.artifacts.map((a,i)=><option key={a.id} value={a.id}>第 {a.researchReportVersion||i+1} 版{i===data.artifacts.length-1?'（最新）':''}</option>)}</select></label>}
 {data.artifacts.filter(a=>a.id===(selectedReport||data.artifacts.at(-1)?.id)).map(artifact=><article aria-label={'报告版本 '+(artifact.researchReportVersion||1)} key={artifact.id}><h3>{artifact.mode==='model'?'调研报告':'阶段进度'}</h3><p>报告第 {artifact.researchReportVersion||1} 版；之前的版本保留。</p><Markdown>{artifact.body}</Markdown>{data.status==='review'&&artifact.id===data.artifacts.at(-1)?.id&&<div className="phase-card">{data.reportAcknowledgement?.artifactId===artifact.id&&data.reportAcknowledgement?.artifactRevision===artifact.revision?<p role="status">本版报告已查看；生成新版后，小九会再次提示。</p>:<><p>查看确认只收起本版报告的提示，不代表认可全部结论，也不会执行建议。</p><button className="btn secondary" disabled={busy} onClick={()=>void action('acknowledge_report',{artifactId:artifact.id,artifactRevision:artifact.revision,approved:true})}>我已查看本版报告</button></>}</div>}<a className="btn secondary" href={(API_BASE + "/work-tasks/")+id+'/artifacts/'+encodeURIComponent(artifact.id)}>下载 Markdown</a><details><summary>查看当时引用的原文</summary>{artifact.sources.map((s,sourceIndex)=><article className="phase-card" key={s.evidenceId}><strong>{s.evidenceId} · {s.title} · {s.kind==='web'?(s.evidenceType==='web_page'?'网页文字':'搜索摘要'):'版本 '+s.revision}</strong>{s.kind==='web'&&s.url&&<p><a href={s.url} target="_blank" rel="noreferrer noopener">打开网页来源</a> · 获取于 {s.retrievedAt}</p>}<p>{s.evidenceType==='search_snippet'?'以下为搜索服务摘要，网页全文长度未知':<>第 {s.start+1}–{s.end} 字，共 {s.total} 字{s.truncated?'；本次未读取全文':''}</>}</p><pre className="preserve-text">{s.quote}</pre>{s.evidenceType==='user_fill'&&<><p>用户回填于 {s.providedAt}，尚未独立核验。</p>{s.urls?.map(url=><p key={url}><a href={url} target="_blank" rel="noreferrer noopener">{url}</a></p>)}{artifact.sources.findIndex(item=>item.id===s.id)===sourceIndex&&<ResearchExternal taskId={id} sourceId={s.id}/>}</>}</article>)}</details>{artifact.actionCandidates?.length>0&&<ResearchCandidates taskId={id} revision={data.revision} artifact={artifact} decisions={data.candidateDecisions||{}} onSaved={async()=>{await load();onChanged();}}/>}</article>)}</>}</div></Modal>;
}

function ResearchHandoff({data,busy,act}:{data:Research;busy:boolean;act:(action:'handoff'|'external'|'end_handoff',extra:Record<string,unknown>)=>Promise<boolean|undefined>}){
 const [open,setOpen]=useState(false),[draft,setDraft]=useState(''),[text,setText]=useState(''),[urls,setUrls]=useState(''),[copyStatus,setCopyStatus]=useState('');const textarea=useRef<HTMLTextAreaElement>(null);
 useEffect(()=>{if(data.handoff?.state==='waiting'){setDraft(data.handoff.text);setOpen(true);setText('');setUrls('');setCopyStatus('');}},[data.handoff?.id]);
 const waiting=data.status==='waiting'&&data.handoff?.state==='waiting',allowed=!!data.researchApproval&&['review','failed'].includes(data.status);
 if(!waiting&&!allowed)return null;
 return <section className="phase-card" aria-label="网页接力"><h3>到 DeepSeek 网页端继续查证</h3><p>只有你保存简报并选择接力，任务才会等待回填；已确认的问题和剩余预算保持不变。</p>{!open&&!waiting&&<button className="btn secondary" disabled={busy} onClick={()=>{setDraft(data.handoffBrief);setOpen(true);setCopyStatus('');}}>整理并编辑网页简报</button>}
 {(open||waiting)&&<><p>先核对将分享的内容。修改这里的网页简报不会更改应用内已确认的问题。</p><label>网页接力简报<textarea ref={textarea} rows={14} maxLength={64000} readOnly={waiting} value={draft} onChange={e=>setDraft(e.target.value)}/></label>
 {!waiting?<button className="btn primary" disabled={busy||!draft.trim()} onClick={async()=>{if(await act('handoff',{brief:draft}))setOpen(false);}}>保存简报，开始网页接力</button>:<><div className="phase-actions"><button className="btn secondary" onClick={async()=>{try{await navigator.clipboard.writeText(draft);setCopyStatus('已复制，可在 DeepSeek 网页端粘贴并开启联网搜索。');}catch{textarea.current?.focus();textarea.current?.select();setCopyStatus('自动复制不可用，已选中简报，请手动复制。');}}}>复制网页简报</button><a className="btn secondary" href="https://chat.deepseek.com" target="_blank" rel="noreferrer noopener">打开 DeepSeek 网页端</a></div>{copyStatus&&<p role="status">{copyStatus}</p>}<form onSubmit={async e=>{e.preventDefault();if(await act('external',{handoffId:data.handoff!.id,text,urls:urls.split('\n').map(x=>x.trim()).filter(Boolean)})){setOpen(false);setText('');setUrls('');}}}><label>网页返回的内容<textarea required rows={10} maxLength={30000} value={text} onChange={e=>setText(e.target.value)}/></label><label>来源链接（可选，每行一个，最多 8 个）<textarea rows={3} maxLength={16008} value={urls} onChange={e=>setUrls(e.target.value)}/></label><p>回填内容会保留为用户提供的材料；附上链接不等于应用已经读取或核验。</p><button className="btn primary" disabled={busy||!text.trim()}>保存回填并继续调研</button></form><button className="btn text" disabled={busy} onClick={async()=>{if(await act('end_handoff',{handoffId:data.handoff!.id}))setOpen(false);}}>{data.artifacts.length?'结束接力，保留原成果':'结束接力，继续原调研'}</button></>}
 </>}</section>;
}
function ResearchExternal({taskId,sourceId}:{taskId:string;sourceId:string}){
 const [text,setText]=useState<string|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 return <div><button className="btn text" disabled={busy} onClick={async()=>{setBusy(true);setError('');try{const source=await api<{text:string}>('/research-tasks/'+taskId+'/external/'+sourceId);setText(source.text);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>读取完整回填内容</button><ErrorBanner message={error}/>{text!==null&&<pre className="preserve-text">{text}</pre>}</div>;
}
