import {useState} from 'react';
import {ErrorBanner,Spinner} from './components';
import {pendingResearch,researchRequest} from './researchRequest';
import {openPetSource} from './PetReminderTable';
export type CandidateDecision={targetId:string;targetKind:'event'|'workTask';title:string;available?:boolean};
type Candidate={title:string;description:string;kind:string};
export default function ResearchCandidates({taskId,revision,artifact,decisions,onSaved}:{taskId:string;revision:number;artifact:{id:string;revision:number;actionCandidates:Candidate[]};decisions:Record<string,CandidateDecision>;onSaved:()=>Promise<void>}){
 return <details><summary>后续建议（由你选择保存）</summary><p>建议不会自动执行。要事等级由你选择；行动任务保存为待确认草稿，由你执行，确认计划后才开始监督。</p>{artifact.actionCandidates.map((candidate,index)=><CandidateForm key={artifact.id+':'+index} {...{taskId,revision,artifact,index,candidate,onSaved}} decision={decisions[artifact.id+':'+index]}/>)}</details>;
}
function CandidateForm({taskId,revision,artifact,index,candidate,decision,onSaved}:{taskId:string;revision:number;artifact:{id:string;revision:number};index:number;candidate:Candidate;decision?:CandidateDecision;onSaved:()=>Promise<void>}){
 const [editing,setEditing]=useState(false),[title,setTitle]=useState(candidate.title),[description,setDescription]=useState(candidate.description),[kind,setKind]=useState(candidate.kind==='event'?'event':'action'),[priority,setPriority]=useState(''),[eventType,setEventType]=useState(''),[dueAt,setDueAt]=useState(''),[time,setTime]=useState('20:00'),[minutes,setMinutes]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState('');
 return <section className="phase-card" aria-label={'调研建议 '+(index+1)}><h4>{candidate.title}</h4><p>{candidate.description}</p><ErrorBanner message={error}/>{decision?<><p role="status">已保存为{decision.targetKind==='event'?'要事':'行动任务草稿'}：{decision.title}{decision.available===false?'（已删除，不会重复创建）':''}</p><button className="btn secondary" disabled={decision.available===false} onClick={()=>openPetSource({sourceKind:decision.targetKind,sourceId:decision.targetId,actionTarget:{page:decision.targetKind==='event'?'events':'workTasks',id:decision.targetId}})}>查看已保存的{decision.targetKind==='event'?'要事':'任务'}</button></>:!editing?<button className="btn secondary" onClick={()=>setEditing(true)}>选择这条建议</button>:<form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await researchRequest('/research-tasks/'+taskId+'/action',{action:'save_candidate',revision,artifactId:artifact.id,artifactRevision:artifact.revision,candidateIndex:index,title,description,target:kind==='event'?{kind,priority,eventType,dueAt:dueAt?new Date(dueAt).toISOString():''}:{kind,time,minutes}});await onSaved();}catch(cause){setError((cause as Error).message);}finally{setBusy(false);}}}>
 <fieldset disabled={busy||!!pendingResearch()} style={{border:0,padding:0,minWidth:0}}><label>保存为<select value={kind} onChange={e=>setKind(e.target.value)}><option value="action">行动任务草稿</option><option value="event">要事</option></select></label><label>建议标题<input required maxLength={160} value={title} onChange={e=>setTitle(e.target.value)}/></label><label>{kind==='event'?'要事摘要':'行动说明与完成条件'}<textarea required rows={4} maxLength={2000} value={description} onChange={e=>setDescription(e.target.value)}/></label>
 {kind==='event'?<><label>要事等级<select required value={priority} onChange={e=>setPriority(e.target.value)}><option value="">请自行选择</option><option value="normal">普通</option><option value="high">高等级</option></select></label><label>要事类型<select required value={eventType} onChange={e=>setEventType(e.target.value)}><option value="">请选择</option><option value="one_off">一次性要事</option><option value="long_term">长期要事</option></select></label><label>约定检查时间（可选）<input type="datetime-local" value={dueAt} onChange={e=>setDueAt(e.target.value)}/></label><p>不填时间则先保存要事，可稍后安排检查。</p></>:<><label>确认开始后的检查时刻<input required type="time" value={time} onChange={e=>setTime(e.target.value)}/></label><label>至少投入分钟数<input required type="number" min={0} max={1440} step={1} value={minutes} onChange={e=>setMinutes(Number(e.target.value))}/></label></>}
 <button className="btn primary" disabled={busy||kind==='event'&&(!priority||!eventType)}>{busy?<Spinner label="正在保存建议…"/>:kind==='event'?'确认保存为要事':'保存行动任务草稿'}</button><button type="button" className="btn text" onClick={()=>setEditing(false)}>暂不保存</button></fieldset></form>}</section>;
}
