import {contractGet} from './api';
import type {components} from '../contracts/generated/types';
import {useEffect,useState} from 'react';

import {ErrorBanner} from './components';
export type EvidenceRef = components['schemas']['EvidenceReference'];
type Item = components['schemas']['EvidenceSourceItem'];
const labels={note:'记录',libraryFile:'文件',artifact:'本任务成果'};
export default function RunEvidenceSources({runId,refs,onChange,disabled}:{runId:string;refs:EvidenceRef[];onChange:(refs:EvidenceRef[])=>void;disabled:boolean}){
 const [kind,setKind]=useState<EvidenceRef['kind']>('note'),[q,setQ]=useState(''),[offset,setOffset]=useState(0),[attempt,setAttempt]=useState(0),[page,setPage]=useState<{items:Item[];total:number}>({items:[],total:0}),[selected,setSelected]=useState<Item[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[selectedError,setSelectedError]=useState('');
 const signature=JSON.stringify(refs);
 useEffect(()=>{let current=true;setLoading(true);setPage({items:[],total:0});setError('');void contractGet('getWorkRunsByIdEvidenceOptions',`/work-runs/${runId}/evidence-options?kind=${kind}&q=${encodeURIComponent(q)}&offset=${offset}`).then(value=>{if(current)setPage(value);}).catch(e=>{if(current)setError(e.message);}).finally(()=>{if(current)setLoading(false);});return()=>{current=false;};},[runId,kind,q,offset,attempt]);
 useEffect(()=>{let current=true;setSelected([]);setSelectedError('');void contractGet('getWorkRunsByIdEvidenceSources',`/work-runs/${runId}/evidence-sources?refs=${encodeURIComponent(signature)}`).then(value=>{if(current)setSelected(value.items);}).catch(e=>{if(current)setSelectedError(e.message);});return()=>{current=false;};},[runId,signature,attempt]);
 return <fieldset className="event-related" disabled={disabled}><legend>引用证据（最多 10 项）</legend><p className="event-related-help">保留你选中时的版本。资料改版后，请移除旧项并重新选择；最终检查会再次核对。</p><ErrorBanner message={selectedError}/><div aria-label="已选证据">{refs.map(ref=>{const item=selected.find(item=>item.id===ref.id&&item.revision===ref.revision);return <article className="phase-card" key={ref.id}><strong>{item?.title||ref.id}</strong><p>{labels[ref.kind]} · 版本 {ref.revision}</p>{item?.invalid&&<p role="alert">{item.invalid}。请移除后重新选择。</p>}{item?.preview&&<details><summary>查看正文预览</summary><p style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{item.preview}{item.truncated?'…（仅预览截短，验收读取全文）':''}</p></details>}<button type="button" className="btn text" onClick={()=>onChange(refs.filter(value=>value.id!==ref.id))}>移除 {item?.title||ref.id}</button></article>;})}</div><div className="phase-actions"><label>证据类型<select value={kind} onChange={e=>{setKind(e.target.value as EvidenceRef['kind']);setOffset(0);}}>{Object.entries(labels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>搜索证据标题<input value={q} maxLength={200} onChange={e=>{setQ(e.target.value);setOffset(0);}}/></label><button type="button" className="btn text" onClick={()=>setAttempt(value=>value+1)}>刷新证据列表</button></div><ErrorBanner message={error}/>{loading?<p role="status">正在读取可用资料…</p>:<><div className="event-related-list">{page.items.map(item=>{const checked=refs.some(ref=>ref.id===item.id);return <label className="event-related-option" key={item.id}><input type="checkbox" checked={checked} disabled={!checked&&refs.length>=10} onChange={()=>onChange(checked?refs.filter(ref=>ref.id!==item.id):[...refs,{kind:item.kind,id:item.id,revision:item.revision}])}/><span className="event-related-title">{item.title} · 版本 {item.revision}</span></label>;})}</div>{!error&&!page.total&&<p>没有符合条件的资料。</p>}<div className="phase-actions"><button type="button" className="btn text" disabled={offset===0} onClick={()=>setOffset(Math.max(0,offset-20))}>上一页</button><span>共 {page.total} 项</span><button type="button" className="btn text" disabled={offset+20>=page.total} onClick={()=>setOffset(offset+20)}>下一页</button></div></>}</fieldset>;
}
