import {contractPatch} from './api';
import {contractGet} from './api';
import {DesktopSettingsPanel} from './DesktopSurface';
import ResearchSearchPricing from './ResearchSearchPricing';
import ClassificationCorrections from './ClassificationCorrections';
import {useEffect,useState} from 'react';
import {Save,LockKeyhole,Plug,CheckCircle2,ExternalLink,LogOut,MonitorSmartphone,Globe2} from 'lucide-react';
import {post} from './api';
import {ErrorBanner,Spinner} from './components';
import type {Settings as SettingsData} from './types';
import {themes,type ThemeId} from './theme';
import {Palette,Check} from 'lucide-react';
import AiLogs from './AiLogs';
import BackupPanel from './BackupPanel';
import CapabilitiesPanel from './CapabilitiesPanel';
export default function Settings({onRefresh,onToast,onLogout,theme,onThemeChange}:{onRefresh:()=>Promise<void>;onToast:(s:string)=>void;onLogout:()=>void;theme:ThemeId;onThemeChange:(theme:ThemeId)=>void}){
 const [data,setData]=useState<SettingsData|null>(null),[name,setName]=useState(''),[baseUrl,setBaseUrl]=useState(''),[model,setModel]=useState(''),[key,setKey]=useState(''),[searchKey,setSearchKey]=useState(''),[code,setCode]=useState(''),[busy,setBusy]=useState(''),[error,setError]=useState(''),[testResult,setTestResult]=useState('');
 const load=()=>contractGet('getSettings','/settings').then(s=>{setData(s);setName(s.name);setBaseUrl(s.provider.baseUrl);setModel(s.provider.model);}).catch(e=>setError(e.message));
 useEffect(()=>{void load();},[]);
 async function save(section:string){setBusy(section);setError('');setTestResult('');try{await contractPatch('patchSettings','/settings',section==='profile'?{name}:section==='access'?{accessCode:code}:section==='search'?{webSearch:{apiKey:searchKey}}:{provider:{baseUrl,model,apiKey:key}});setKey('');setSearchKey('');setCode('');await load();await onRefresh();onToast('设置已保存');}catch(e){setError((e as Error).message);}finally{setBusy('');}}
 async function test(){setBusy('test');setError('');setTestResult('');try{const result=await post<{response:string}>('/settings/test',{});setTestResult(result.response);}catch(e){setError((e as Error).message);}finally{setBusy('');}}
 async function disconnect(){setBusy('model');setError('');try{await contractPatch('patchSettings','/settings',{provider:{baseUrl:'',model:'',clearKey:true}});await load();await onRefresh();onToast('已切换到本地检索模式');}catch(e){setError((e as Error).message);}finally{setBusy('');}}
 return <><div className="page-heading"><div><span className="eyebrow">MAKE YOURSELF AT HOME</span><h1>一个属于你的空间</h1><p>管理模型、设备访问和你的数据。</p></div></div><ErrorBanner message={error}/>{!data?<Spinner label="正在读取设置…"/>:<div className="settings-layout"><div className="settings-panels"><section className="settings-panel theme-panel"><h2><Palette size={20}/>界面主题</h2><p className="panel-description">选择一套你喜欢的色彩与质感；更改只影响当前浏览器的显示。</p><div className="theme-options" role="radiogroup" aria-label="界面主题">{themes.map(option=><button key={option.id} type="button" role="radio" aria-checked={theme===option.id} className={"theme-option "+(theme===option.id?"selected":"")} onClick={()=>onThemeChange(option.id)}><span className="theme-swatch" aria-hidden="true">{option.colors.map(color=><i key={color} style={{background:color}}/>)}{theme===option.id&&<Check size={15}/>}</span><span className="theme-option-copy"><strong>{option.name}</strong><small>{option.description}</small></span></button>)}</div></section><section className="settings-panel"><h2><MonitorSmartphone size={20}/>空间设置</h2><form onSubmit={e=>{e.preventDefault();save('profile');}}><label>空间名称<input value={name} onChange={e=>setName(e.target.value)} maxLength={30}/></label><p className="field-help">在手机和电脑上使用相同地址与口令，即可访问同一空间。</p><button className="btn secondary" disabled={!!busy}><Save size={15}/>保存名称</button></form></section>
 <section className="settings-panel"><h2><Plug size={20}/>连接 AI 模型</h2><p className="panel-description">默认可以本地搜索、查看原文摘录和整理资料。连接兼容接口后，可启用 AI 问答与写作。</p><form onSubmit={e=>{e.preventDefault();save('model');}}><label>接口地址<input type="url" placeholder="http://localhost:11434/v1" value={baseUrl} onChange={e=>setBaseUrl(e.target.value)} disabled={data.provider.environmentManaged}/></label><label>模型名称<input placeholder="填写服务提供方的模型名称" value={model} onChange={e=>setModel(e.target.value)} disabled={data.provider.environmentManaged}/></label><label>API 密钥<input type="password" autoComplete="off" placeholder={data.provider.hasKey?'已保存密钥，留空保持不变':'本地模型通常不需要填写'} value={key} onChange={e=>setKey(e.target.value)} disabled={data.provider.environmentManaged}/></label><p className="field-help">接口应兼容 Chat Completions，地址通常以 /v1 结尾。连接云端服务后，相关资料将发送到该服务处理。</p>{data.provider.environmentManaged?<div className="subtle-notice">模型由服务端环境变量管理。</div>:<div className="button-row"><button className="btn primary" disabled={!!busy}>{busy==='model'?<Spinner label="保存中"/>:<><Save size={15}/>保存模型</>}</button>{data.provider.baseUrl&&<button type="button" className="btn text" onClick={disconnect} disabled={!!busy}>断开模型</button>}</div>}</form><button className="btn secondary test-model" onClick={test} disabled={!!busy||!data.provider.baseUrl}>{busy==='test'?<Spinner label="测试连接中…"/>:<><Plug size={15}/>测试已保存的连接</>}</button>{testResult&&<div className="success-banner"><CheckCircle2 size={16}/>{testResult}</div>}</section>
 <section className="settings-panel"><h2><Globe2 size={20}/>应用内联网分析</h2><p className="panel-description">DeepSeek API 目前没有内置网页搜索。这里使用 Brave Search 获取网页摘要，再由已连接的 AI 模型分析；DeepSeek 网页端搜索不需要此密钥。</p><form onSubmit={e=>{e.preventDefault();void save('search');}}><label>Brave Search API 密钥<input type="password" autoComplete="off" value={searchKey} onChange={e=>setSearchKey(e.target.value)} placeholder={data.webSearch.hasKey?'已保存密钥，留空保持不变':'填写 Brave Search API 密钥'} disabled={data.webSearch.environmentManaged}/></label><p className="field-help">搜索时只把问题发给 Brave；引用记录和要事不会发送给搜索服务。密钥仅保存在服务端。</p>{data.webSearch.environmentManaged?<div className="subtle-notice">搜索密钥由服务端环境变量管理。</div>:<div className="button-row"><button className="btn primary" disabled={!!busy||!searchKey.trim()}><Save size={15}/>保存搜索密钥</button>{data.webSearch.hasKey&&<button type="button" className="btn text" disabled={!!busy} onClick={async()=>{setBusy('search');setError('');try{await contractPatch('patchSettings','/settings',{webSearch:{clearKey:true}});await load();await onRefresh();onToast('搜索密钥已移除');}catch(e){setError((e as Error).message);}finally{setBusy('');}}}>移除搜索密钥</button>}</div>}</form><ResearchSearchPricing/></section>
 <DesktopSettingsPanel/><CapabilitiesPanel/>
 <AiLogs/>
 <section className="settings-panel"><h2><LockKeyhole size={20}/>访问口令</h2>{data.demoAccess&&<div className="subtle-notice">当前为演示口令。导入个人资料前，建议设置自己的口令。</div>}<form onSubmit={e=>{e.preventDefault();save('access');}}><label>新口令<input type="password" autoComplete="new-password" placeholder="至少 8 位" value={code} onChange={e=>setCode(e.target.value)} minLength={8} maxLength={100}/></label><p className="field-help">修改后，其他设备需要重新登录；当前设备保持登录。</p><button className="btn secondary" disabled={!!busy||code.length<8}>更新口令</button></form></section>
 <ClassificationCorrections/><BackupPanel/></div><aside className="settings-aside"><div className="about-card"><div className="eyebrow">拾光 · WEB DEMO</div><h3>记录的价值，<br/>在再次遇见时。</h3><p>这个版本专注于记录、找回、整理与记忆确认。使用示例资料即可体验完整流程。</p><ul><li>真实保存到服务器</li><li>手机与电脑共享空间</li><li>原文可回看，记忆可修改</li></ul><a href="https://github.com/usememos/memos" target="_blank" rel="noreferrer">开源参考：Memos<ExternalLink size={13}/></a><a href="https://github.com/khoj-ai/khoj" target="_blank" rel="noreferrer">开源参考：Khoj<ExternalLink size={13}/></a></div><button className="btn secondary full" onClick={async()=>{try{await post('/logout',{});onLogout();}catch(e){setError((e as Error).message);}}}><LogOut size={16}/>退出当前空间</button></aside></div>}</>;
}
