import {useEffect,useState} from 'react';
import {api,ApiError,post} from './api';
import {ErrorBanner} from './components';
type Entry={id:string;title:string;status:string;seconds:number;timing:boolean;minimumSeconds:number|null;conditions:{id:string;description:string}[];evidence:string;skipReason:string;scheduledDueAt:string|null;snoozedUntil:string|null;references:{id:string;title:string;revision:number;invalid:boolean;content:string}[]};
type Snapshot={day:string;signature:string;items:Entry[];totals:{planned:number;completed:number;skipped:number;pending:number;seconds:number;minimumSeconds:number;unknownRequirements:number};recap:null|{signature:string;createdAt:string;items:{runId:string;advice:string}[]}};
type Pending={day:string;signature:string;opId:string};
const key='shiguang-pending-supervision-recap';
const status:Record<string,string>={open:'待完成',review:'待用户确认',completed:'已确认完成',skipped:'已跳过'};
export default function SupervisionRecap({onOpen}:{onOpen:(id:string)=>void}){
 const [pending,setPending]=useState<Pending|null>(()=>{try{return JSON.parse(sessionStorage.getItem(key)||'null');}catch{return null;}});
 const [day,setDay]=useState(pending?.day||new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())),[open,setOpen]=useState(!!pending),[snapshot,setSnapshot]=useState<Snapshot|null>(null),[attempt,setAttempt]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState(''),[loading,setLoading]=useState(false);
 useEffect(()=>{const refresh=()=>setAttempt(value=>value+1);window.addEventListener('business-changed',refresh);return()=>window.removeEventListener('business-changed',refresh);},[]);
 useEffect(()=>{if(!open||!day){setSnapshot(null);return;}let current=true;setLoading(true);setSnapshot(null);setError('');void api<Snapshot>('/supervision/recap?day='+encodeURIComponent(day)).then(value=>{if(current)setSnapshot(value);}).catch(e=>{if(current)setError(e.message);}).finally(()=>{if(current)setLoading(false);});return()=>{current=false;};},[day,open,attempt]);
 async function generate(){if(!snapshot&&!pending)return;setBusy(true);setError('');try{const body=pending||{day,signature:snapshot!.signature,opId:crypto.randomUUID()};sessionStorage.setItem(key,JSON.stringify(body));setPending(body);await post('/supervision/recap',body);sessionStorage.removeItem(key);setPending(null);setAttempt(value=>value+1);}catch(e){if(e instanceof ApiError&&((e.status>=400&&e.status<500)||e.status===502)){sessionStorage.removeItem(key);setPending(null);}setError((e as Error).message);}finally{setBusy(false);}}
 return <details open={open} onToggle={e=>setOpen(e.currentTarget.open)}><summary>每日复盘</summary><div className="phase-panel"><p>仅回顾监督任务，普通待办与要事不混入统计。计时采用已保存的投入，不把页面停留算作学习。</p><div className="phase-actions"><label>复盘日期<input type="date" value={day} disabled={busy||!!pending} onChange={e=>setDay(e.target.value)}/></label><button className="btn secondary" disabled={busy||!day} onClick={()=>setAttempt(value=>value+1)}>刷新复盘事实</button><button className="btn primary" disabled={busy||(!pending&&(loading||!snapshot?.items.length))} onClick={()=>void generate()}>{busy?'正在生成复盘建议…':pending?'重试生成复盘建议':'生成 AI 复盘建议'}</button></div><ErrorBanner message={error}/>{pending&&<p>生成请求尚待确认，重试沿用原操作编号。</p>}{loading&&<p role="status">正在读取当日记录…</p>}{snapshot&&<><p>计划 {snapshot.totals.planned} 项 · 已确认完成 {snapshot.totals.completed} 项 · 待处理 {snapshot.totals.pending} 项 · 跳过 {snapshot.totals.skipped} 项</p><p>已保存投入 {(snapshot.totals.seconds/60).toFixed(1)} 分钟 / 已知最低要求 {(snapshot.totals.minimumSeconds/60).toFixed(1)} 分钟{snapshot.totals.unknownRequirements?`；${snapshot.totals.unknownRequirements} 项缺少历史要求`:''}</p>{snapshot.recap&&snapshot.recap.signature!==snapshot.signature&&<p role="status">已有 AI 建议依据的记录已变化，下方只作历史参考；可以重新生成。</p>}{snapshot.items.map(item=><article className="phase-card" key={item.id}><h3>{item.title}</h3><p>{status[item.status]||item.status} · 已保存 {(item.seconds/60).toFixed(1)} 分钟{item.timing?'（仍在计时，刷新可查看新检查点）':''}</p><p>计划：{item.conditions.map(c=>c.description).join('；')||'历史条件未记录'}</p><p>已记录原因：{item.skipReason||'未记录，不推断原因'}</p>{item.snoozedUntil&&<p>下一次约定：{new Date(item.snoozedUntil).toLocaleString('zh-CN')}</p>}<details><summary>查看交付与证据</summary><p style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{item.evidence||'没有文字证据'}</p>{item.references.map(ref=><details key={ref.id}><summary>{ref.title} · 版本 {ref.revision}{ref.invalid?' · 已失效':''}</summary><p style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{ref.invalid?'来源已删除或改版，不作为当前复盘依据。':ref.content}</p></details>)}</details>{snapshot.recap?.items.find(advice=>advice.runId===item.id)&&<div><strong>AI 下一步建议（需自行核对）</strong><p style={{whiteSpace:'pre-wrap'}}>{snapshot.recap.items.find(advice=>advice.runId===item.id)!.advice}</p></div>}<button className="btn secondary" onClick={()=>onOpen(item.id)}>查看本次任务记录</button></article>)}</>}</div></details>;
}
