import {useState} from 'react';
import {ApiError,post} from './api';
import {ErrorBanner,Modal} from './components';
import {openPetSource} from './PetReminderTable';
import type {Todo} from './types';
const key='shiguang-pending-todo-upgrade';
type Body={opId:string;revision:number;minutes:number;repeat:'once'|'daily';startTime:string;time:string;conditions:{id:string;kind:'evidence';required:true;description:string}[]};
export function pendingTodoUpgrade(){try{return JSON.parse(sessionStorage.getItem(key)||'null') as {todoId:string;body:Body}|null;}catch{return null;}}
export default function TodoUpgrade({todo,onClose,onRefresh}:{todo:Todo;onClose:()=>void;onRefresh:()=>Promise<void>}){
 const stored=pendingTodoUpgrade();const [pending,setPending]=useState<Body|null>(stored?.todoId===todo.id?stored.body:null),[revision]=useState(todo.revision),[conditions,setConditions]=useState(stored?.todoId===todo.id?stored.body.conditions:[{id:crypto.randomUUID(),kind:'evidence' as const,required:true as const,description:''}]),[minutes,setMinutes]=useState(stored?.todoId===todo.id?stored.body.minutes:30),[repeat,setRepeat]=useState<'once'|'daily'>(stored?.todoId===todo.id?stored.body.repeat:'once'),[startTime,setStartTime]=useState(stored?.todoId===todo.id?stored.body.startTime:'09:00'),[time,setTime]=useState(stored?.todoId===todo.id?stored.body.time:'20:00'),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function submit(){setBusy(true);setError('');try{const body=pending||{opId:crypto.randomUUID(),revision,conditions,minutes,repeat,startTime,time};sessionStorage.setItem(key,JSON.stringify({todoId:todo.id,body}));setPending(body);const result=await post<{taskId:string;runId:string}>('/todos/'+todo.id+'/upgrade',body);sessionStorage.removeItem(key);setPending(null);await onRefresh();onClose();openPetSource({sourceKind:'workRun',sourceId:result.runId,actionTarget:{page:'workTasks',id:result.taskId,runId:result.runId}});}catch(e){if(e instanceof ApiError&&e.status>=400&&e.status<500){sessionStorage.removeItem(key);setPending(null);}setError((e as Error).message);}finally{setBusy(false);}}
 return <Modal title="升级为监督任务" closeDisabled={busy||!!pending} onClose={onClose}><form className="phase-panel" onSubmit={e=>{e.preventDefault();void submit();}}><h3>{todo.title}</h3><p>从今天开始监督，原待办日期和历史保留。所有条件及最低投入都满足后，还需要你确认完成。这里只监督你的进展，不自动代办。</p><ErrorBanner message={error}/>{pending&&<p>升级请求尚待确认，重试不会重复建立任务。</p>}<fieldset disabled={busy||!!pending}>{conditions.map((condition,index)=><div key={condition.id}><label>完成要求 {index+1}<textarea required maxLength={4000} rows={2} value={condition.description} onChange={e=>setConditions(items=>items.map(item=>item.id===condition.id?{...item,description:e.target.value}:item))}/></label><button type="button" className="btn text" disabled={conditions.length===1} onClick={()=>setConditions(items=>items.filter(item=>item.id!==condition.id))}>移除要求 {index+1}</button></div>)}<button type="button" className="btn secondary" disabled={conditions.length>=20} onClick={()=>setConditions(items=>[...items,{id:crypto.randomUUID(),kind:'evidence',required:true,description:''}])}>添加要求</button><label>最低投入分钟<input type="number" min={0} max={1440} step="any" required value={minutes} onChange={e=>setMinutes(Number(e.target.value))}/></label><label>重复方式<select value={repeat} onChange={e=>setRepeat(e.target.value as 'once'|'daily')}><option value="once">仅这一次</option><option value="daily">每天（每天独立验收）</option></select></label><label>开始时间<input type="time" required value={startTime} onChange={e=>setStartTime(e.target.value)}/></label><label>检查时间<input type="time" required value={time} onChange={e=>setTime(e.target.value)}/></label></fieldset><button className="btn primary" disabled={busy}>{pending?'重试升级':'确认条件并开始监督'}</button></form></Modal>;
}
