// Public wire types are generated from the pinned xiaojiu-contracts protocol.
import type {components} from '../contracts/generated/types';
export type Attachment = components['schemas']['Attachment'];
export type Transcript = components['schemas']['Transcript'];
export type Note = components['schemas']['Note'];
export type Source = components['schemas']['Source'];
export type ConversationReference = components['schemas']['ConversationReference'];
export type Memory = components['schemas']['Memory'];
export type EventRecord = components['schemas']['EventRecord'];
export type Todo = components['schemas']['Todo'];
export type LedgerTransaction = components['schemas']['LedgerTransaction'];
export type AccountingBudget = components['schemas']['AccountingBudget'];
export type PetChatMessage = components['schemas']['PetChatMessage'];
export type PetChatReply = components['schemas']['PetChatReply'];
export type Artifact = components['schemas']['Artifact'];
export type MemoryProposal = components['schemas']['MemoryProposal'];
export type Conversation = components['schemas']['Conversation'];
export type Task = components['schemas']['Task'];
export type PendingMemoryBatch = components['schemas']['PendingMemoryBatch'];
export type Bootstrap = components['schemas']['Bootstrap'];
export type Settings = components['schemas']['Settings'];
export type Page='workTasks'|'library'|'assistant'|'events'|'artifacts'|'memories'|'settings'|'accounting';
